include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - lib/app/l10n/gen/**
    - build/**
    - android/**
    - ios/**
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    require_trailing_commas: false
    unawaited_futures: true
