// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    products,
    weightLogs,
    routines,
    routineSteps,
    usageLogs,
    dailyEntries,
    photos,
    tags,
    entryTags,
    productTags,
    appSettings,
    idxWeightLogsProduct,
    idxRoutineStepsRoutine,
    idxUsageLogsProduct,
    idxUsageLogsUsedAt,
    idxPhotosTakenAt,
  ];
  late final Shape0 products = Shape0(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 weightLogs = Shape1(
    source: i0.VersionedTable(
      entityName: 'weight_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_21,
        _column_22,
        _column_23,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 routines = Shape2(
    source: i0.VersionedTable(
      entityName: 'routines',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 routineSteps = Shape3(
    source: i0.VersionedTable(
      entityName: 'routine_steps',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_27,
        _column_21,
        _column_28,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 usageLogs = Shape4(
    source: i0.VersionedTable(
      entityName: 'usage_logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_21,
        _column_29,
        _column_30,
        _column_31,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 dailyEntries = Shape5(
    source: i0.VersionedTable(
      entityName: 'daily_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 photos = Shape6(
    source: i0.VersionedTable(
      entityName: 'photos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 tags = Shape7(
    source: i0.VersionedTable(
      entityName: 'tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(name, type)'],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 entryTags = Shape8(
    source: i0.VersionedTable(
      entityName: 'entry_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entry_id, tag_id)'],
      columns: [_column_48, _column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 productTags = Shape9(
    source: i0.VersionedTable(
      entityName: 'product_tags',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_id, tag_id)'],
      columns: [_column_21, _column_49],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 appSettings = Shape10(
    source: i0.VersionedTable(
      entityName: 'app_settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_50, _column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxWeightLogsProduct = i1.Index(
    'idx_weight_logs_product',
    'CREATE INDEX idx_weight_logs_product ON weight_logs (product_id, weighed_at)',
  );
  final i1.Index idxRoutineStepsRoutine = i1.Index(
    'idx_routine_steps_routine',
    'CREATE INDEX idx_routine_steps_routine ON routine_steps (routine_id, step_order)',
  );
  final i1.Index idxUsageLogsProduct = i1.Index(
    'idx_usage_logs_product',
    'CREATE INDEX idx_usage_logs_product ON usage_logs (product_id, used_at)',
  );
  final i1.Index idxUsageLogsUsedAt = i1.Index(
    'idx_usage_logs_used_at',
    'CREATE INDEX idx_usage_logs_used_at ON usage_logs (used_at)',
  );
  final i1.Index idxPhotosTakenAt = i1.Index(
    'idx_photos_taken_at',
    'CREATE INDEX idx_photos_taken_at ON photos (taken_at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get brand =>
      columnsByName['brand']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get price =>
      columnsByName['price']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get netContent =>
      columnsByName['net_content']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get netUnit =>
      columnsByName['net_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get purchasePlace =>
      columnsByName['purchase_place']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get purchaseDate =>
      columnsByName['purchase_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get openedDate =>
      columnsByName['opened_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get paoMonths =>
      columnsByName['pao_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get expiryDate =>
      columnsByName['expiry_date']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get startWeight =>
      columnsByName['start_weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get emptyBottleWeight =>
      columnsByName['empty_bottle_weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get repurchase =>
      columnsByName['repurchase']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get finishedDate =>
      columnsByName['finished_date']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'brand',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_6(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'price',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_7(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'net_content',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'net_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'g\'',
      defaultValue: const i1.CustomExpression('\'g\''),
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'purchase_place',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'purchase_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'opened_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pao_months',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'expiry_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'start_weight',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'empty_bottle_weight',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'in_use\'',
      defaultValue: const i1.CustomExpression('\'in_use\''),
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (rating BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'repurchase',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (repurchase IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finished_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get weighedAt =>
      columnsByName['weighed_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get weight =>
      columnsByName['weight']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'product_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES products(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'weighed_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get timeOfDay =>
      columnsByName['time_of_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reminderTime =>
      columnsByName['reminder_time']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reminderEnabled =>
      columnsByName['reminder_enabled']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'time_of_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reminder_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reminder_enabled',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (reminder_enabled IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get routineId =>
      columnsByName['routine_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stepOrder =>
      columnsByName['step_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'routine_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES routines(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'step_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get routineId =>
      columnsByName['routine_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get usedAt =>
      columnsByName['used_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get area =>
      columnsByName['area']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'routine_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES routines(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'used_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'area',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get date =>
      columnsByName['date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get scoreOil =>
      columnsByName['score_oil']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scoreMoisture =>
      columnsByName['score_moisture']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scoreAcne =>
      columnsByName['score_acne']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scoreRedness =>
      columnsByName['score_redness']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get scoreDullness =>
      columnsByName['score_dullness']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get sleepHours =>
      columnsByName['sleep_hours']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get stressLevel =>
      columnsByName['stress_level']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sunExposure =>
      columnsByName['sun_exposure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get periodPhase =>
      columnsByName['period_phase']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_oil',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (score_oil BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_moisture',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (score_moisture BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_acne',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (score_acne BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_redness',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (score_redness BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'score_dullness',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (score_dullness BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'sleep_hours',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stress_level',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (stress_level BETWEEN 1 AND 5)',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sun_exposure',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'period_phase',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dailyEntryId =>
      columnsByName['daily_entry_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get takenAt =>
      columnsByName['taken_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbPath =>
      columnsByName['thumb_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get session =>
      columnsByName['session']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'daily_entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES daily_entries(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'taken_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumb_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES daily_entries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'tag_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES tags(id)ON DELETE CASCADE',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get productId =>
      columnsByName['product_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get tagId =>
      columnsByName['tag_id']! as i1.GeneratedColumn<int>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
