"""Soothing actives and botanical extracts (including Thai herbs and sea plants)."""
from common import C, E, I, M, S, T

_CICA = ('บัวบก (Centella asiatica) สมุนไพรที่ใช้สมานแผลมาแต่โบราณ สารสำคัญ 4 ตัวคือ '
         'มาเดคาสโซไซด์ เอเชียติโคไซด์ กรดมาเดคาสสิก และกรดเอเชียติก')
_CICA_GOOD = 'ลดการอักเสบ รอยแดง ช่วยฟื้นฟูเกราะผิวและสมานผิว เหมาะกับผิวแพ้ง่าย ผิวเป็นสิว และหลังทำเลเซอร์'
_SOOTHE = 'ช่วยปลอบประโลมผิว ลดการระคายเคืองและรอยแดง'
_EXTRACT_TIPS = 'สารสกัดจากพืชแต่ละแบรนด์มีความเข้มข้นต่างกัน และพืชบางชนิดอาจก่อการแพ้ในบางคน'
_SEA = 'สารสกัดจากสาหร่ายทะเล มีพอลิแซ็กคาไรด์ แร่ธาตุ และกรดอะมิโน ให้ความชุ่มชื้นและต้านอนุมูลอิสระ'

ROWS = [
    I('Panthenol', 'แพนทีนอล (โปรวิตามินบี 5)', ['soothing', 'humectant'], [C, S, M, E, T],
      'โปรวิตามินบี 5 ที่ผิวเปลี่ยนเป็นกรดแพนโทเทนิก ดูดความชุ่มชื้นได้ดี', good='ให้ความชุ่มชื้น ลดการระคายเคือง ช่วยสมานผิวและฟื้นฟูเกราะผิว',
      tips='อ่อนโยนมาก ใช้ได้กับทุกสภาพผิว ความเข้มข้นที่พบ 1–5%', aka=['Vitamin B5', 'วิตามินบี 5', 'B5', 'Dexpanthenol', 'D-Panthenol'],
      en='Pro-vitamin B5: hydrating and healing', smi='CC(C)(CO)C(O)C(=O)NCCCO', f='C9H19NO4'),
    I('Allantoin', 'อัลลันโทอิน', 'soothing', [C, S, M, T], 'สารที่พบในต้นคอมฟรีย์และสังเคราะห์ได้ ช่วยให้ผิวนุ่มและสมานผิว',
      good=_SOOTHE + ' ช่วยให้เซลล์ผิวเก่าหลุดง่ายขึ้นเล็กน้อย ผิวเรียบนุ่ม', en='Soothing, softening skin protectant',
      smi='NC(=O)NC1NC(=O)NC1=O', f='C4H6N4O3'),
    I('Bisabolol', 'บิซาโบลอล', 'soothing', [S, M, E], 'สารสำคัญจากดอกคาโมมายล์ (หรือต้นแคนเดีย) ' + _SOOTHE,
      good=_SOOTHE + ' และช่วยให้สารอื่นซึมผ่านผิวได้ดีขึ้น', aka=['alpha-Bisabolol'], en='Chamomile-derived soother',
      smi='CC(C)=CCCC(C)(O)C1CCC(C)=CC1', f='C15H26O'),
    I('Dipotassium Glycyrrhizate', 'ไดโพแทสเซียมไกลไซร์ไรเซต', 'soothing', [C, S, M, T], 'เกลือของกรดไกลไซร์ไรซินจากรากชะเอม ' + _SOOTHE,
      good='ลดรอยแดงและการอักเสบ นิยมในผลิตภัณฑ์สำหรับผิวแพ้ง่ายของญี่ปุ่น', aka=['licorice', 'ชะเอม'], en='Licorice-derived anti-irritant'),
    I('Glycyrrhetinic Acid', 'กรดไกลไซร์เรทินิก', 'soothing', [M, E], 'สารจากรากชะเอมที่ลดการอักเสบคล้ายคอร์ติโซนอ่อนๆ', aka=['licorice', 'ชะเอม'],
      en='Licorice anti-inflammatory', smi='CC1(C)C(O)CCC2(C)C1CCC1(C)C2C(=O)C=C2C3CC(C)(CCC3(C)CCC21C)C(=O)O', f='C30H46O4'),
    I('Centella Asiatica Extract', 'สารสกัดใบบัวบก', 'soothing', [C, S, M, E, T], _CICA, good=_CICA_GOOD, tips='มักเขียนบนฉลากว่า Cica',
      aka=['Cica', 'ซิก้า', 'บัวบก', 'Gotu Kola'], en='Cica: soothing and repairing', kind='extract'),
    I('Centella Asiatica Leaf Water', 'น้ำใบบัวบก', ['soothing', 'solvent'], [T, E], 'น้ำที่ได้จากการกลั่นใบบัวบก ใช้แทนน้ำในสูตร ' + _SOOTHE,
      aka=['Cica', 'บัวบก'], en='Centella water', kind='extract'),
    I('Madecassoside', 'มาเดคาสโซไซด์', ['soothing', 'barrier'], [M, E], 'สารสำคัญจากใบบัวบก ' + _SOOTHE, good=_CICA_GOOD,
      aka=['Cica', 'บัวบก'], en='Key centella active'),
    I('Asiaticoside', 'เอเชียติโคไซด์', ['soothing', 'antiAging'], [M, E], 'สารสำคัญจากใบบัวบก ช่วยกระตุ้นการสร้างคอลลาเจนและสมานแผล', good=_CICA_GOOD,
      aka=['Cica', 'บัวบก'], en='Centella active (collagen, healing)'),
    I('Asiatic Acid', 'กรดเอเชียติก', ['soothing', 'antiAging'], [M, E], 'สารสำคัญจากใบบัวบก ' + _SOOTHE, good=_CICA_GOOD,
      aka=['Cica', 'บัวบก'], en='Centella active',
      smi='CC1CCC2(CCC3(C(=CCC4C3(CCC5C4(CC(C(C5(C)CO)O)O)C)C)C2C1C)C)C(=O)O', f='C30H48O5'),
    I('Madecassic Acid', 'กรดมาเดคาสสิก', ['soothing', 'antiAging'], [M, E], 'สารสำคัญจากใบบัวบก ' + _SOOTHE, good=_CICA_GOOD,
      aka=['Cica', 'บัวบก'], en='Centella active'),
    I('Ectoin', 'เอ็กโทอีน', ['soothing', 'humectant'], [M, E, S],
      'สารที่จุลินทรีย์ในทะเลทรายเกลือสร้างเพื่อปกป้องตัวเองจากความร้อน ความแห้ง และรังสี UV',
      good='ปกป้องผิวจากมลภาวะและสภาพแวดล้อม ลดการอักเสบ เติมความชุ่มชื้น', aka=['Ectoine'], en='Extremolyte protector',
      smi='CC1=NCCC(N1)C(=O)O', f='C6H10N2O2'),
    I('Beta-Glucan', 'เบต้ากลูแคน', ['soothing', 'humectant'], [M, E, T], 'พอลิแซ็กคาไรด์จากข้าวโอ๊ต ยีสต์ หรือเห็ด',
      good=_SOOTHE + ' ให้ความชุ่มชื้นได้ดี (บางงานวิจัยว่าดีกว่าไฮยาลูโรนิก) และช่วยสมานผิว', en='Soothing, hydrating polysaccharide',
      kind='polymer'),
    I('Avena Sativa Kernel Flour', 'ข้าวโอ๊ต (คอลลอยด์)', ['soothing', 'barrier'], [C, M],
      'ผงข้าวโอ๊ตบดละเอียดพิเศษ (colloidal oatmeal) เป็นสารปกป้องผิวที่ อย. สหรัฐฯ รับรอง',
      good=_SOOTHE + ' บรรเทาอาการคัน ผิวแห้งแตก ผิวอักเสบ (eczema)', aka=['Colloidal Oatmeal', 'Oat', 'โอ๊ต'],
      en='Colloidal oatmeal for itch and eczema', kind='extract'),
    I('Avena Sativa Kernel Extract', 'สารสกัดข้าวโอ๊ต', 'soothing', [C, M, T], 'สารสกัดข้าวโอ๊ตที่มีอเวแนนทราไมด์และเบต้ากลูแคน ' + _SOOTHE, aka=['Oat', 'โอ๊ต'],
      en='Oat extract', kind='extract'),
    I('Aloe Barbadensis Leaf Juice', 'ว่านหางจระเข้', ['soothing', 'humectant'], [C, S, M, T],
      'วุ้นจากใบว่านหางจระเข้ มีพอลิแซ็กคาไรด์ วิตามิน และเอนไซม์', good='ให้ความชุ่มชื้นและเย็นสบาย ช่วยบรรเทาผิวไหม้แดดและการระคายเคือง',
      aka=['Aloe Vera', 'อโลเวร่า', 'ว่านหางจระเข้'], en='Aloe vera: soothing and hydrating', kind='extract'),
    I('Aloe Barbadensis Leaf Extract', 'สารสกัดว่านหางจระเข้', ['soothing', 'humectant'], [C, M, T], 'สารสกัดจากใบว่านหางจระเข้ ' + _SOOTHE,
      aka=['Aloe Vera', 'อโลเวร่า'], en='Aloe extract', kind='extract'),
    I('Chamomilla Recutita Flower Extract', 'สารสกัดดอกคาโมมายล์', 'soothing', [C, M, T], 'สารสกัดคาโมมายล์เยอรมัน มีบิซาโบลอลและอะพิจีนิน ' + _SOOTHE,
      tips='ผู้แพ้พืชตระกูลเดซี่ (เช่น ดาวเรือง เก๊กฮวย) ควรระวัง', aka=['Chamomile', 'คาโมมายล์', 'Matricaria'], en='Chamomile: soothing',
      kind='extract'),
    I('Anthemis Nobilis Flower Extract', 'สารสกัดดอกโรมันคาโมมายล์', 'soothing', [M, T], 'สารสกัดคาโมมายล์โรมัน ' + _SOOTHE, aka=['Roman Chamomile'],
      en='Roman chamomile', kind='extract'),
    I('Calendula Officinalis Flower Extract', 'สารสกัดดอกดาวเรือง', 'soothing', [C, M, T], 'สารสกัดดาวเรือง (คาเลนดูล่า) ใช้สมานผิวมาแต่โบราณ ' + _SOOTHE,
      aka=['Calendula', 'คาเลนดูล่า', 'ดาวเรือง'], en='Calendula: soothing, healing', kind='extract'),
    I('Artemisia Vulgaris Extract', 'สารสกัดโกฐจุฬาลัมพา', ['soothing', 'antioxidant'], [C, E, T], 'สารสกัดมักเวิร์ต ' + _SOOTHE + ' และต้านอนุมูลอิสระ',
      aka=['Mugwort', 'มักเวิร์ต'], en='Mugwort: soothing', kind='extract'),
    I('Artemisia Princeps Extract', 'สารสกัดมักเวิร์ตเกาหลี', ['soothing', 'antioxidant'], [C, E, T], 'สารสกัดมักเวิร์ตสายพันธุ์เกาหลี (ซุก) นิยมในโทนเนอร์และมาส์ก ' + _SOOTHE,
      aka=['Mugwort', 'มักเวิร์ต', 'Ssuk'], en='Korean mugwort', kind='extract'),
    I('Houttuynia Cordata Extract', 'สารสกัดพลูคาว', ['soothing', 'antiAcne'], [C, E, T], 'สารสกัดพลูคาว (ผักคาวตอง) ต้านการอักเสบและเชื้อแบคทีเรีย',
      good=_SOOTHE + ' เหมาะกับผิวเป็นสิว', aka=['Heartleaf', 'พลูคาว', 'ผักคาวตอง'], en='Heartleaf: soothing, anti-blemish', kind='extract'),
    I('Propolis Extract', 'สารสกัดโพรโพลิส', ['soothing', 'antiAcne', 'antioxidant'], [E, M], 'ยางไม้ที่ผึ้งเก็บมาสร้างรัง มีฤทธิ์ต้านเชื้อแบคทีเรียและต้านอนุมูลอิสระ',
      good='ช่วยผิวเป็นสิว ผิวอักเสบ และให้ความชุ่มชื้น', tips='ผู้แพ้ผลิตภัณฑ์จากผึ้งควรระวัง', aka=['Propolis', 'พรอพอลิส'],
      en='Bee propolis: antibacterial, soothing', kind='extract'),
    I('Hamamelis Virginiana Water', 'น้ำวิชฮาเซล', ['soothing', 'antiAcne'], [T], 'น้ำกลั่นจากวิชฮาเซล มีแทนนินที่ช่วยกระชับผิว (astringent)',
      good='ช่วยลดความมันและการอักเสบ', tips='บางสูตรมีแอลกอฮอล์ปนอยู่ ผิวแห้งควรระวัง', aka=['Witch Hazel', 'วิชฮาเซล'],
      en='Witch hazel: astringent toner', kind='extract'),
    I('Hamamelis Virginiana Extract', 'สารสกัดวิชฮาเซล', ['soothing', 'antioxidant'], [T, E], 'สารสกัดวิชฮาเซลที่มีแทนนินสูง ช่วยกระชับรูขุมขน',
      aka=['Witch Hazel'], en='Witch hazel extract', kind='extract'),
    I('Rosa Damascena Flower Water', 'น้ำดอกกุหลาบ', ['soothing', 'fragrance'], [T], 'น้ำที่ได้จากการกลั่นดอกกุหลาบดามัสก์ ให้ความสดชื่นและกลิ่นหอม',
      aka=['Rose Water', 'น้ำกุหลาบ'], en='Rose water', kind='extract'),
    I('Cucumis Sativus Fruit Extract', 'สารสกัดแตงกวา', ['soothing', 'humectant'], [T, M], 'สารสกัดแตงกวา ให้ความชุ่มชื้นและเย็นสบาย', aka=['Cucumber', 'แตงกวา'],
      en='Cucumber extract', kind='extract'),
    I('Portulaca Oleracea Extract', 'สารสกัดผักเบี้ยใหญ่', 'soothing', [T, E, M], 'สารสกัดผักเบี้ยใหญ่ (purslane) ต้านการอักเสบ นิยมในเครื่องสำอางเกาหลี',
      aka=['Purslane', 'ผักเบี้ย'], en='Purslane: soothing', kind='extract'),
    I('Polygonum Cuspidatum Root Extract', 'สารสกัดรากโพลีโกนัม', ['antioxidant', 'soothing'], [E, T], 'สารสกัดที่มีเรสเวอราทรอลสูง ต้านอนุมูลอิสระ',
      aka=['Japanese Knotweed'], en='Resveratrol-rich extract', kind='extract'),
    I('Scutellaria Baicalensis Root Extract', 'สารสกัดรากแบคคาล สคัลแคป', ['soothing', 'antioxidant'], [E, T], 'สารสกัดที่มีไบคาลินและไบคาลีน ต้านการอักเสบและอนุมูลอิสระ',
      aka=['Baikal Skullcap'], en='Skullcap: soothing antioxidant', kind='extract'),
    I('Curcuma Longa Root Extract', 'สารสกัดขมิ้นชัน', ['antioxidant', 'soothing', 'antiAcne'], [C, M, E], 'สารสกัดขมิ้นชัน มีเคอร์คูมินที่ต้านการอักเสบและอนุมูลอิสระ',
      tips='อาจทำให้ผลิตภัณฑ์/ผิวมีสีเหลือง', aka=['Turmeric', 'ขมิ้น', 'ขมิ้นชัน'], en='Turmeric extract', kind='extract'),
    I('Garcinia Mangostana Peel Extract', 'สารสกัดเปลือกมังคุด', ['antioxidant', 'antiAcne'], [C, E, M], 'สารสกัดเปลือกมังคุด มีแซนโทนต้านอนุมูลอิสระและเชื้อแบคทีเรียสิว',
      aka=['Mangosteen', 'มังคุด'], en='Mangosteen peel: antioxidant, anti-blemish', kind='extract'),
    I('Clitoria Ternatea Flower Extract', 'สารสกัดดอกอัญชัน', 'antioxidant', [T, E, M], 'สารสกัดดอกอัญชัน มีแอนโทไซยานินต้านอนุมูลอิสระ',
      aka=['Butterfly Pea', 'อัญชัน'], en='Butterfly pea antioxidant', kind='extract'),
    I('Tamarindus Indica Seed Extract', 'สารสกัดเมล็ดมะขาม', ['humectant', 'filmFormer'], [M, E], 'สารสกัดเมล็ดมะขาม มีพอลิแซ็กคาไรด์ที่ให้ความชุ่มชื้นคล้ายไฮยาลูโรนิก',
      aka=['Tamarind', 'มะขาม'], en='Tamarind seed hydrator', kind='extract'),
    I('Tamarindus Indica Fruit Extract', 'สารสกัดเนื้อมะขาม', ['exfoliant', 'brightening'], [C, M], 'สารสกัดเนื้อมะขาม มีกรดทาร์ทาริก (AHA) ช่วยผลัดเซลล์อ่อนๆ',
      aka=['Tamarind', 'มะขาม'], en='Tamarind pulp (natural AHA)', kind='extract'),
    I('Moringa Oleifera Leaf Extract', 'สารสกัดใบมะรุม', 'antioxidant', [E, M, C], 'สารสกัดใบมะรุม มีวิตามินและโพลีฟีนอล ต้านอนุมูลอิสระและมลภาวะ',
      aka=['Moringa', 'มะรุม'], en='Moringa leaf antioxidant', kind='extract'),
    I('Zingiber Officinale Root Extract', 'สารสกัดขิง', ['antioxidant', 'soothing'], [C, M], 'สารสกัดขิง มีจินเจอรอลต้านอนุมูลอิสระและการอักเสบ', aka=['Ginger', 'ขิง'],
      en='Ginger extract', kind='extract'),
    I('Nelumbo Nucifera Flower Extract', 'สารสกัดดอกบัวหลวง', ['antioxidant', 'humectant'], [T, M], 'สารสกัดดอกบัว ให้ความชุ่มชื้นและต้านอนุมูลอิสระ',
      aka=['Lotus', 'บัว', 'บัวหลวง'], en='Lotus flower extract', kind='extract'),
    I('Morus Alba Leaf Extract', 'สารสกัดใบหม่อน', ['antioxidant', 'brightening'], [T, E], 'สารสกัดใบหม่อน ต้านอนุมูลอิสระ', aka=['Mulberry', 'หม่อน'],
      en='Mulberry leaf extract', kind='extract'),
    I('Calamine', 'คาลาไมน์', ['soothing', 'absorbent'], [M, C], 'ผงสีชมพูจากซิงค์ออกไซด์ผสมเหล็กออกไซด์เล็กน้อย บรรเทาอาการคันและดูดซับความมัน',
      aka=['คาลาไมน์'], en='Calamine: itch relief', kind='mineral'),
    I('Thermal Spring Water', 'น้ำแร่ธรรมชาติ', ['soothing', 'solvent'], [T, E, M], 'น้ำแร่จากแหล่งน้ำพุร้อน (เช่น Avène, La Roche-Posay) มีแร่ธาตุและซีลีเนียม ' + _SOOTHE,
      aka=['Thermal Water', 'Spring Water', 'Avene Aqua'], en='Thermal spring water', kind='mineral'),
    I('Ginkgo Biloba Leaf Extract', 'สารสกัดใบแปะก๊วย', 'antioxidant', [E, M], 'สารสกัดแปะก๊วย มีฟลาโวนอยด์ต้านอนุมูลอิสระและช่วยการไหลเวียน', aka=['Ginkgo', 'แปะก๊วย'],
      en='Ginkgo antioxidant', kind='extract'),
    I('Echinacea Purpurea Extract', 'สารสกัดเอ็กไคนาเซีย', 'soothing', [M, E], 'สารสกัดดอกเอ็กไคนาเซีย ' + _SOOTHE, aka=['Echinacea'], en='Echinacea',
      kind='extract'),
    I('Arnica Montana Flower Extract', 'สารสกัดดอกอาร์นิกา', 'soothing', [M], 'สารสกัดดอกอาร์นิกา ใช้ลดรอยช้ำและบวม', note='sensitize', aka=['Arnica'],
      en='Arnica for bruising', kind='extract'),
    I('Lonicera Japonica Flower Extract', 'สารสกัดดอกสายน้ำผึ้ง', ['soothing', 'preservative'], [E, M], 'สารสกัดดอกสายน้ำผึ้ง ต้านเชื้อจุลินทรีย์อ่อนๆ และลดการอักเสบ',
      aka=['Honeysuckle'], en='Honeysuckle extract', kind='extract'),
    I('Salvia Officinalis Leaf Extract', 'สารสกัดใบเสจ', ['antioxidant', 'antiAcne'], [T, C], 'สารสกัดเสจ ต้านอนุมูลอิสระ ช่วยกระชับและลดความมัน', aka=['Sage'],
      en='Sage extract', kind='extract'),
    I('Thymus Vulgaris Extract', 'สารสกัดไธม์', ['antiAcne', 'antioxidant'], [T, C], 'สารสกัดไธม์ มีไทมอลต้านเชื้อแบคทีเรีย', aka=['Thyme'], en='Thyme extract',
      kind='extract'),
    I('Mentha Piperita Leaf Extract', 'สารสกัดใบเปปเปอร์มินต์', ['soothing', 'fragrance'], [C, T], 'สารสกัดเปปเปอร์มินต์ ให้ความเย็นสดชื่น', aka=['Peppermint', 'มินต์'],
      note='menthol', en='Peppermint extract', kind='extract'),
    I('Cannabidiol', 'แคนนาบิไดออล (CBD)', ['soothing', 'antiAcne'], [M, E], 'สารจากกัญชง/กัญชาที่ไม่ทำให้มึนเมา งานวิจัยเบื้องต้นพบว่าช่วยลดการอักเสบและการผลิตซีบัม',
      tips='กฎหมายแต่ละประเทศต่างกัน ไทยอนุญาตในเครื่องสำอางตามเงื่อนไขของ อย.', aka=['CBD'], note='pregnancy', en='CBD: anti-inflammatory',
      smi='CCCCCc1cc(O)c(C2C=C(C)CCC2C(C)=C)c(O)c1', f='C21H30O2'),
    # ---------- Sea & mushrooms ----------
    I('Laminaria Digitata Extract', 'สารสกัดสาหร่ายเคลป์', ['humectant', 'antioxidant'], [M, E, T], _SEA, aka=['Kelp', 'สาหร่าย'], en='Kelp extract',
      kind='extract'),
    I('Fucus Vesiculosus Extract', 'สารสกัดสาหร่ายฟูคัส', ['humectant', 'antioxidant'], [M, E], _SEA, aka=['Bladderwrack', 'สาหร่าย'],
      en='Bladderwrack extract', kind='extract'),
    I('Spirulina Platensis Extract', 'สารสกัดสาหร่ายสไปรูลิน่า', ['antioxidant', 'humectant'], [M, E], 'สารสกัดสาหร่ายเกลียวทอง มีโปรตีนและวิตามินสูง', aka=['Spirulina'],
      en='Spirulina extract', kind='extract'),
    I('Chlorella Vulgaris Extract', 'สารสกัดคลอเรลลา', ['antioxidant', 'humectant'], [M, E], 'สารสกัดสาหร่ายคลอเรลลา มีเปปไทด์และวิตามิน', aka=['Chlorella'],
      en='Chlorella extract', kind='extract'),
    I('Algae Extract', 'สารสกัดสาหร่าย', ['humectant', 'antioxidant'], [M, E, T], _SEA, aka=['seaweed', 'สาหร่าย'], en='Algae extract', kind='extract'),
    I('Ganoderma Lucidum Extract', 'สารสกัดเห็ดหลินจือ', ['antioxidant', 'soothing'], [E, M], 'สารสกัดเห็ดหลินจือ มีพอลิแซ็กคาไรด์และไตรเทอร์ปีน ต้านอนุมูลอิสระ', aka=['Reishi', 'หลินจือ'],
      en='Reishi mushroom', kind='extract'),
    # ---------- Fruits & others ----------
    I('Citrus Junos Fruit Extract', 'สารสกัดส้มยูจา', ['antioxidant', 'brightening'], [T, E], 'สารสกัดส้มยูจาจากเกาหลี/ญี่ปุ่น มีวิตามินซีสูง', aka=['Yuja', 'Yuzu'],
      en='Yuja (yuzu) extract', kind='extract'),
    I('Carica Papaya Fruit Extract', 'สารสกัดมะละกอ', ['exfoliant', 'brightening'], [C, M], 'สารสกัดมะละกอ มีเอนไซม์ปาเปนช่วยผลัดเซลล์อ่อนๆ', aka=['Papaya', 'มะละกอ'],
      en='Papaya extract', kind='extract'),
    I('Ananas Sativus Fruit Extract', 'สารสกัดสับปะรด', 'exfoliant', [C, T], 'สารสกัดสับปะรด มีเอนไซม์โบรมีเลนช่วยผลัดเซลล์', aka=['Pineapple', 'สับปะรด'],
      en='Pineapple extract', kind='extract'),
    I('Opuntia Ficus-Indica Stem Extract', 'สารสกัดกระบองเพชร', ['humectant', 'soothing'], [M, T], 'สารสกัดกระบองเพชร ให้ความชุ่มชื้นและปลอบประโลมผิว', aka=['Cactus', 'Prickly Pear'],
      en='Cactus extract', kind='extract'),
    I('Hibiscus Sabdariffa Flower Extract', 'สารสกัดกระเจี๊ยบแดง', ['exfoliant', 'antioxidant'], [T, E], 'สารสกัดกระเจี๊ยบแดง มีกรดผลไม้ (AHA) และแอนโทไซยานิน',
      aka=['Roselle', 'กระเจี๊ยบ'], en='Roselle: natural AHAs', kind='extract'),
    I('Malus Domestica Fruit Cell Culture Extract', 'สารสกัดสเต็มเซลล์แอปเปิล', ['antiAging', 'antioxidant'], [E, M], 'สารสกัดจากการเพาะเลี้ยงเซลล์แอปเปิล นิยมในผลิตภัณฑ์ลดริ้วรอย',
      tips='หลักฐานว่าช่วยเพิ่มสเต็มเซลล์ผิวยังจำกัด', aka=['Apple Stem Cell'], en='Apple stem cell extract', kind='extract'),
    I('Solanum Lycopersicum Fruit Extract', 'สารสกัดมะเขือเทศ', 'antioxidant', [E, M], 'สารสกัดมะเขือเทศ มีไลโคปีนต้านอนุมูลอิสระ', aka=['Tomato', 'มะเขือเทศ'],
      en='Tomato extract', kind='extract'),
    I('Daucus Carota Sativa Root Extract', 'สารสกัดแครอท', 'antioxidant', [M], 'สารสกัดแครอท มีเบต้าแคโรทีน', aka=['Carrot', 'แครอท'], en='Carrot extract',
      kind='extract'),
    I('Bambusa Vulgaris Extract', 'สารสกัดไผ่', ['humectant', 'soothing'], [T, M], 'สารสกัด/น้ำจากไผ่ ให้ความชุ่มชื้น มีซิลิกาธรรมชาติ', aka=['Bamboo', 'ไผ่'],
      en='Bamboo extract', kind='extract'),
    I('Equisetum Arvense Extract', 'สารสกัดหญ้าหางม้า', ['soothing', 'antioxidant'], [T, M], 'สารสกัดหญ้าหางม้า มีซิลิกาและฟลาโวนอยด์', aka=['Horsetail'],
      en='Horsetail extract', kind='extract'),
    I('Glycine Max Seed Extract', 'สารสกัดเมล็ดถั่วเหลือง', ['antioxidant', 'brightening'], [E, M], 'สารสกัดถั่วเหลือง มีไอโซฟลาโวนและสารที่ช่วยลดการส่งเม็ดสี',
      aka=['Soy', 'ถั่วเหลือง'], en='Soy extract', kind='extract'),
    I('Morinda Citrifolia Fruit Extract', 'สารสกัดลูกยอ', 'antioxidant', [E, M], 'สารสกัดลูกยอ (โนนิ) ต้านอนุมูลอิสระ', aka=['Noni', 'ลูกยอ'], en='Noni extract',
      kind='extract'),
    I('Citrus Unshiu Peel Extract', 'สารสกัดเปลือกส้มยูชู', ['antioxidant', 'brightening'], [T, E], 'สารสกัดเปลือกส้มแมนดาริน มีวิตามินซีและเฮสเพอริดิน',
      aka=['Mandarin', 'ส้ม'], en='Mandarin peel extract', kind='extract'),
]
