"""Humectants: glycols, sugars, hyaluronic acid family, NMF components."""
from common import ALL, C, E, I, M, S, T

_HUM = 'สารดูดความชุ่มชื้น (humectant) ที่ดึงน้ำมากักเก็บไว้ในชั้นผิว ทำให้ผิวอิ่มน้ำ นุ่ม ไม่แห้งตึง'
_HUM_TIPS = 'ได้ผลดีที่สุดเมื่อทาบนผิวหมาดๆ แล้วตามด้วยครีมเพื่อล็อกความชุ่มชื้น'
_GLYCOL = ('ไกลคอลที่ทำหน้าที่ดูดความชุ่มชื้นและเป็นตัวทำละลาย ช่วยให้เนื้อผลิตภัณฑ์ลื่น '
           'ซึมไว และช่วยให้สารสำคัญตัวอื่นซึมผ่านผิวได้ดีขึ้น')
_GLYCOL_PRES = ' มีฤทธิ์ต้านจุลินทรีย์อ่อนๆ จึงช่วยลดปริมาณสารกันเสียที่ต้องใช้'
_HA = ('สารตามธรรมชาติในผิวและข้อต่อ (glycosaminoglycan) อุ้มน้ำได้มาก '
       'ทำให้ผิวดูอิ่มฟู ริ้วรอยจากความแห้งดูจางลง')
_HA_TIPS = ('ใช้กับผิวหมาดๆ หลังล้างหน้า แล้วตามด้วยมอยส์เจอไรเซอร์ทับ '
            'ในอากาศแห้งมากถ้าไม่ทาครีมทับอาจรู้สึกตึง')
_NMF = (' เป็นส่วนหนึ่งของ NMF (natural moisturizing factor) '
        'สารชุ่มชื้นที่ผิวสร้างเองตามธรรมชาติ')
_AA = 'กรดอะมิโนชนิดหนึ่ง' + _NMF + ' ช่วยให้ผิวชุ่มชื้นและแข็งแรง'
_SUGAR = 'น้ำตาล/แอลกอฮอล์น้ำตาลที่ดูดความชุ่มชื้น ให้ความรู้สึกนุ่ม ไม่เหนียวมาก'

ROWS = [
    # ---------- Glycerin & glycols ----------
    I('Glycerin', 'กลีเซอรีน', 'humectant', ALL,
      'สารดูดความชุ่มชื้นที่ใช้กันมากที่สุดในเครื่องสำอาง ได้จากไขมันพืช/สัตว์หรือสังเคราะห์ และยังเป็นส่วนประกอบในผิวตามธรรมชาติ',
      good='ดึงน้ำเข้าสู่ผิว ช่วยฟื้นฟูเกราะผิว ผิวนุ่มชุ่มชื้น งานวิจัยรองรับมาก ราคาถูก ปลอดภัยสูง',
      tips='ถ้าอยู่อันดับต้นๆ ของสูตรเยอะๆ อาจรู้สึกเหนียวเล็กน้อย ' + _HUM_TIPS,
      aka=['glycerol', 'กลีเซอรอล'], en='Most common, well-proven humectant',
      smi='OCC(O)CO', f='C3H8O3'),
    I('Diglycerin', 'ไดกลีเซอรีน', 'humectant', [M, T, E], _HUM + ' เป็นกลีเซอรีนสองโมเลกุลต่อกัน เหนียวน้อยกว่า',
      en='Less sticky glycerin dimer', smi='OCC(O)COCC(O)CO', f='C6H14O5'),
    I('Butylene Glycol', 'บิวทิลีนไกลคอล', ['humectant', 'solvent'], ALL, _GLYCOL,
      good='ทำให้เนื้อบางเบาซึมไว ใช้สกัดสารจากพืชด้วย', aka=['BG', '1,3-Butanediol'],
      en='Light humectant and solvent', smi='CC(O)CCO', f='C4H10O2'),
    I('Propylene Glycol', 'โพรพิลีนไกลคอล', ['humectant', 'solvent'], [C, M, T], _GLYCOL,
      tips='ปลอดภัยสำหรับคนส่วนใหญ่ แต่พบการแพ้ได้บ้างในผิวที่บอบบางมาก', aka=['PG'],
      en='Humectant and penetration enhancer', smi='CC(O)CO', f='C3H8O2'),
    I('Propanediol', 'โพรเพนไดออล', ['humectant', 'solvent'], [C, M, E, T],
      _GLYCOL + ' มักได้จากการหมักน้ำตาลข้าวโพด จึงนิยมใช้แทนโพรพิลีนไกลคอล', aka=['1,3-Propanediol', 'Zemea'],
      en='Plant-derived glycol humectant', smi='OCCCO', f='C3H8O2'),
    I('Pentylene Glycol', 'เพนทิลีนไกลคอล', ['humectant', 'preservative'], [M, E, T], _GLYCOL + _GLYCOL_PRES,
      en='Humectant with mild preservative boost', smi='CCCC(O)CO', f='C5H12O2'),
    I('1,2-Hexanediol', '1,2-เฮกเซนไดออล', ['humectant', 'preservative'], ALL, _GLYCOL + _GLYCOL_PRES + ' พบบ่อยมากในเครื่องสำอางเกาหลี',
      aka=['hexanediol'], en='Humectant that boosts preservation', smi='CCCCC(O)CO', f='C6H14O2'),
    I('Caprylyl Glycol', 'แคพริลิลไกลคอล', ['humectant', 'preservative'], ALL, _GLYCOL + _GLYCOL_PRES,
      aka=['1,2-Octanediol'], en='Humectant/emollient that boosts preservation', smi='CCCCCCC(O)CO', f='C8H18O2'),
    I('Dipropylene Glycol', 'ไดโพรพิลีนไกลคอล', ['solvent', 'humectant'], [S, M, T], _GLYCOL + ' ใช้ละลายน้ำหอมด้วย',
      aka=['DPG'], en='Solvent and humectant', smi='CC(O)COCC(C)O', f='C6H14O3'),
    I('Isopentyldiol', 'ไอโซเพนทิลไดออล', ['humectant', 'solvent'], [M, T, E], _GLYCOL + ' ให้สัมผัสลื่นไม่เหนียว',
      en='Light glycol humectant', smi='CC(C)(O)CCO', f='C5H12O2'),
    I('Methylpropanediol', 'เมทิลโพรเพนไดออล', ['solvent', 'humectant'], [M, T, E], _GLYCOL,
      en='Glycol solvent', smi='CC(CO)CO', f='C4H10O2'),
    I('Glycereth-26', 'กลีเซอเรท-26', 'humectant', [M, T, E], _HUM + ' เป็นกลีเซอรีนที่ต่อสาย PEG ให้สัมผัสไม่เหนียว',
      en='Non-sticky ethoxylated glycerin', kind='polymer'),
    I('PEG-8', 'พีอีจี-8', ['humectant', 'solvent'], [M, T, E], 'พอลิเอทิลีนไกลคอลสายสั้น ดูดความชุ่มชื้นและเป็นตัวทำละลาย',
      en='Short polyethylene glycol humectant', kind='polymer'),
    I('Methyl Gluceth-20', 'เมทิลกลูเซท-20', 'humectant', [C, M, T], _HUM + ' จากน้ำตาลกลูโคส ให้สัมผัสนุ่มลื่น',
      en='Glucose-derived humectant', kind='polymer'),
    # ---------- Hyaluronic acid family ----------
    I('Sodium Hyaluronate', 'โซเดียมไฮยาลูโรเนต', 'humectant', [S, M, E, T],
      'เกลือของกรดไฮยาลูโรนิก ' + _HA + ' โมเลกุลเล็กกว่ากรดเล็กน้อย จึงเป็นรูปแบบที่พบบ่อยที่สุดในเซรั่ม',
      good='เติมน้ำให้ผิว อิ่มฟู ลดความแห้งกร้าน ใช้ได้กับทุกสภาพผิว', tips=_HA_TIPS,
      aka=['hyaluronic', 'ไฮยา', 'HA'], en='Hydrating hyaluronic acid salt', kind='polymer'),
    I('Hyaluronic Acid', 'กรดไฮยาลูโรนิก', 'humectant', [M, E, T], _HA,
      good='เติมน้ำ ผิวอิ่มฟู นุ่มเรียบ', tips=_HA_TIPS, aka=['ไฮยา', 'HA', 'ไฮยาลูรอน'],
      en='Hydrating glycosaminoglycan', kind='polymer'),
    I('Hydrolyzed Hyaluronic Acid', 'ไฮยาลูโรนิกไฮโดรไลซ์', 'humectant', [M, E, T],
      'กรดไฮยาลูโรนิกที่ถูกย่อยให้โมเลกุลเล็กลง จึงซึมลงผิวชั้นบนได้ลึกกว่า', good='เติมน้ำในชั้นผิว', tips=_HA_TIPS,
      aka=['ไฮยา', 'HA', 'low molecular HA'], en='Low-molecular-weight hyaluronic acid', kind='polymer'),
    I('Sodium Acetylated Hyaluronate', 'โซเดียมอะซิทิเลตไฮยาลูโรเนต', 'humectant', [M, E],
      'ไฮยาลูโรนิกที่ดัดแปลงให้ชอบน้ำมันขึ้น เกาะผิวได้ดีและให้ความชุ่มชื้นนาน', tips=_HA_TIPS, aka=['ไฮยา'],
      en='Longer-lasting modified hyaluronate', kind='polymer'),
    I('Sodium Hyaluronate Crosspolymer', 'โซเดียมไฮยาลูโรเนตครอสพอลิเมอร์', 'humectant', [M, E],
      'ไฮยาลูโรนิกที่เชื่อมโยงกันเป็นตาข่าย สร้างฟิล์มชุ่มชื้นบนผิวได้นาน', tips=_HA_TIPS, aka=['ไฮยา'],
      en='Cross-linked hyaluronate film', kind='polymer'),
    I('Hydroxypropyltrimonium Hyaluronate', 'ไฮดรอกซีโพรพิลไตรโมเนียมไฮยาลูโรเนต', 'humectant', [M, E, C],
      'ไฮยาลูโรนิกที่มีประจุบวก จึงเกาะผิว/ผมได้ดีแม้ล้างออก', aka=['ไฮยา'], en='Cationic hyaluronate', kind='polymer'),
    I('Potassium Hyaluronate', 'โพแทสเซียมไฮยาลูโรเนต', 'humectant', [M, E], 'เกลือโพแทสเซียมของกรดไฮยาลูโรนิก ' + _HA,
      tips=_HA_TIPS, aka=['ไฮยา'], en='Hyaluronic acid salt', kind='polymer'),
    I('Sodium Polyglutamate', 'โซเดียมโพลีกลูตาเมต', 'humectant', [E, M],
      'พอลิเมอร์จากกรดกลูตามิกที่ได้จากการหมักถั่วเหลือง (นัตโตะ) อุ้มน้ำได้มากกว่าไฮยาลูโรนิก',
      good='เติมความชุ่มชื้นและสร้างฟิล์มนุ่มบนผิว ช่วยลดการสูญเสียน้ำ', tips='ใช้ร่วมกับไฮยาลูโรนิกได้ดี',
      aka=['PGA', 'polyglutamic acid'], en='Super-hydrating polyglutamic acid', kind='polymer'),
    I('Sodium Chondroitin Sulfate', 'โซเดียมคอนดรอยตินซัลเฟต', 'humectant', [M, E], 'สารในกลุ่มเดียวกับไฮยาลูโรนิก อุ้มน้ำและให้ความชุ่มชื้น',
      en='Hydrating glycosaminoglycan', kind='polymer'),
    I('Hydrolyzed Glycosaminoglycans', 'ไกลโคซามิโนไกลแคนไฮโดรไลซ์', 'humectant', [M, E], 'กลุ่มสารคล้ายไฮยาลูโรนิกที่ย่อยแล้ว ให้ความชุ่มชื้น',
      en='Hydrating glycosaminoglycans', kind='polymer'),
    # ---------- NMF components ----------
    I('Sodium PCA', 'โซเดียมพีซีเอ', 'humectant', [M, T, E], _HUM + _NMF + ' (เป็นตัวที่มีมากที่สุดใน NMF)',
      good='ชุ่มชื้นโดยไม่เหนียว', aka=['NMF', 'Sodium Pyroglutamate'], en='Key natural moisturising factor',
      smi='[O-]C(=O)C1CCC(=O)N1.[Na+]', f='C5H6NNaO3'),
    I('Urea', 'ยูเรีย', ['humectant', 'exfoliant'], [M],
      'สารชุ่มชื้นที่มีอยู่ใน NMF ของผิว ที่ความเข้มข้นต่ำ (2–10%) ให้ความชุ่มชื้น ที่ความเข้มข้นสูง (10–40%) ช่วยละลายเซลล์ผิวที่หนาแข็ง',
      good='เหมาะกับผิวแห้งมาก ผิวลอกเป็นขุย ส้นเท้าแตก และขนคุด', tips='ความเข้มข้นสูงอาจแสบบนผิวที่มีแผล',
      en='Hydrator that softens rough, thick skin', smi='NC(N)=O', f='CH4N2O'),
    I('Hydroxyethyl Urea', 'ไฮดรอกซีเอทิลยูเรีย', 'humectant', [M], _HUM + ' ให้ความชุ่มชื้นใกล้เคียงกลีเซอรีนแต่ไม่เหนียว',
      en='Non-sticky urea derivative humectant', smi='NC(=O)NCCO', f='C3H8N2O2'),
    I('Sodium Lactate', 'โซเดียมแลคเตต', ['humectant', 'phAdjuster'], [M, T, C], _HUM + _NMF,
      en='NMF humectant and buffer', smi='CC(O)C(=O)[O-].[Na+]', f='C3H5NaO3'),
    I('Ammonium Lactate', 'แอมโมเนียมแลคเตต', ['humectant', 'exfoliant'], [M],
      'เกลือของกรดแลคติก ให้ความชุ่มชื้นและผลัดเซลล์ผิวอย่างอ่อนโยน ใช้ในโลชั่นสำหรับผิวแห้งมาก/ขนคุด',
      en='Moisturising lactate for very dry skin', smi='CC(O)C(=O)[O-].[NH4+]', f='C3H9NO3'),
    I('Betaine', 'บีเทน', ['humectant', 'soothing'], [C, M, T],
      'สารจากหัวบีทน้ำตาล ช่วยรักษาสมดุลน้ำในเซลล์ (osmolyte) ให้ความชุ่มชื้นและช่วยลดการระคายเคืองของสารลดแรงตึงผิว',
      aka=['Trimethylglycine'], en='Hydrating, anti-irritant osmolyte',
      smi='C[N+](C)(C)CC(=O)[O-]', f='C5H11NO2'),
    I('Glycine', 'ไกลซีน', 'humectant', [M, E], _AA, en='Amino acid (NMF)', smi='NCC(=O)O', f='C2H5NO2'),
    I('Alanine', 'อะลานีน', 'humectant', [M, E], _AA, en='Amino acid (NMF)', smi='CC(N)C(=O)O', f='C3H7NO2'),
    I('Serine', 'เซรีน', 'humectant', [M, E], _AA, en='Amino acid (NMF)', smi='NC(CO)C(=O)O', f='C3H7NO3'),
    I('Proline', 'โพรลีน', ['humectant', 'antiAging'], [M, E], _AA + ' และเป็นส่วนประกอบสำคัญของคอลลาเจน',
      en='Amino acid; collagen building block', smi='OC(=O)C1CCCN1', f='C5H9NO2'),
    I('Threonine', 'ทรีโอนีน', 'humectant', [M, E], _AA, en='Amino acid (NMF)', smi='CC(O)C(N)C(=O)O', f='C4H9NO3'),
    I('Glutamic Acid', 'กรดกลูตามิก', 'humectant', [M, E], _AA, en='Amino acid (NMF)',
      smi='NC(CCC(=O)O)C(=O)O', f='C5H9NO4'),
    I('Aspartic Acid', 'กรดแอสปาร์ติก', 'humectant', [M, E], _AA, en='Amino acid (NMF)',
      smi='NC(CC(=O)O)C(=O)O', f='C4H7NO4'),
    I('Lysine', 'ไลซีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NCCCCC(N)C(=O)O', f='C6H14N2O2'),
    I('Histidine', 'ฮิสทิดีน', ['humectant', 'antioxidant'], [M, E], _AA + ' มีฤทธิ์ต้านอนุมูลอิสระเล็กน้อย',
      en='Amino acid', smi='NC(Cc1cnc[nH]1)C(=O)O', f='C6H9N3O2'),
    I('Taurine', 'ทอรีน', ['humectant', 'soothing'], [M, E, T], 'กรดอะมิโนซัลโฟนิกที่ช่วยรักษาสมดุลน้ำในเซลล์และปกป้องผิวจากความเครียด',
      en='Osmolyte amino acid', smi='NCCS(=O)(=O)O', f='C2H7NO3S'),
    I('Silk Amino Acids', 'กรดอะมิโนจากไหม', ['humectant', 'filmFormer'], [M, E], 'กรดอะมิโนจากโปรตีนไหม ให้ความชุ่มชื้นและสัมผัสนุ่มลื่น',
      en='Silk amino acids', kind='mixture'),
    # ---------- Sugars & polyols ----------
    I('Trehalose', 'ทรีฮาโลส', 'humectant', [M, E, T],
      'น้ำตาลจากธรรมชาติที่ช่วยให้สิ่งมีชีวิตทนแล้ง ปกป้องเซลล์ไม่ให้เสียน้ำ', good='ชุ่มชื้นและช่วยปกป้องผิวจากสภาพอากาศแห้ง',
      en='Protective hydrating sugar', smi='OCC1OC(OC2OC(CO)C(O)C(O)C2O)C(O)C(O)C1O', f='C12H22O11'),
    I('Sorbitol', 'ซอร์บิทอล', 'humectant', [C, M], _SUGAR, en='Sugar alcohol humectant',
      smi='OCC(O)C(O)C(O)C(O)CO', f='C6H14O6'),
    I('Xylitol', 'ไซลิทอล', 'humectant', [M, E], _SUGAR + ' ช่วยเสริมความชุ่มชื้นในชั้นผิว', en='Sugar alcohol humectant',
      smi='OCC(O)C(O)C(O)CO', f='C5H12O5'),
    I('Erythritol', 'อีริทริทอล', 'humectant', [M, T], _SUGAR, en='Sugar alcohol humectant',
      smi='OCC(O)C(O)CO', f='C4H10O4'),
    I('Inositol', 'อิโนซิทอล', 'humectant', [M, T], _SUGAR, en='Hydrating polyol',
      smi='OC1C(O)C(O)C(O)C(O)C1O', f='C6H12O6'),
    I('Glucose', 'กลูโคส', 'humectant', [M, T], _SUGAR, en='Hydrating sugar', smi='OCC1OC(O)C(O)C(O)C1O', f='C6H12O6'),
    I('Sucrose', 'ซูโครส', ['humectant', 'exfoliant'], [M, C], 'น้ำตาลทราย ให้ความชุ่มชื้น หรือใช้เป็นเม็ดสครับที่ละลายน้ำได้',
      en='Table sugar; humectant or scrub', smi='OCC1OC(OC2(CO)OC(CO)C(O)C2O)C(O)C(O)C1O', f='C12H22O11'),
    I('Glyceryl Glucoside', 'กลีเซอริลกลูโคไซด์', 'humectant', [M, E, T],
      'สารชุ่มชื้นจากกลีเซอรีนกับกลูโคส มีงานวิจัยว่าช่วยกระตุ้นช่องทางน้ำในผิว (aquaporin)', en='Hydrating glycerin-glucose',
      smi='OCC(O)COC1OC(CO)C(O)C(O)C1O', f='C9H18O8'),
    I('Saccharide Isomerate', 'แซคคาไรด์ไอโซเมอเรต', 'humectant', [M, E, T],
      'สารชุ่มชื้นจากน้ำตาลพืชที่ยึดเกาะกับเคราตินในผิว จึงให้ความชุ่มชื้นได้นานแม้ล้างหน้า', aka=['Pentavitin'],
      en='Long-lasting sugar humectant', kind='mixture'),
    I('Mel', 'น้ำผึ้ง', ['humectant', 'soothing'], [M, C], 'น้ำผึ้ง ดูดความชุ่มชื้นได้ดีและมีฤทธิ์ต้านเชื้อแบคทีเรียอ่อนๆ',
      aka=['Honey', 'น้ำผึ้ง'], en='Honey; humectant', kind='extract'),
    I('Tremella Fuciformis Sporocarp Extract', 'สารสกัดเห็ดหูหนูขาว', 'humectant', [M, E, T],
      'สารสกัดจากเห็ดหูหนูขาว มีพอลิแซ็กคาไรด์ที่อุ้มน้ำได้ใกล้เคียงไฮยาลูโรนิก', good='ชุ่มชื้น ผิวอิ่มน้ำ ไม่เหนียว',
      aka=['snow mushroom', 'เห็ดหูหนูขาว'], en='Snow mushroom; natural hyaluronic alternative', kind='extract'),
    I('Pullulan', 'พูลลูแลน', ['filmFormer', 'humectant'], [E, M], 'พอลิแซ็กคาไรด์จากการหมัก สร้างฟิล์มใสบนผิว ให้ความรู้สึกตึงกระชับชั่วคราว',
      en='Tightening film-forming polysaccharide', kind='polymer'),
    I('Polyquaternium-51', 'โพลีควอเทอร์เนียม-51', 'humectant', [M, E], 'พอลิเมอร์เลียนแบบเยื่อหุ้มเซลล์ ให้ความชุ่มชื้นยาวนาน (Lipidure)',
      aka=['Lipidure'], en='Biomimetic moisturising polymer', kind='polymer'),
    I('Hydrolyzed Silk', 'โปรตีนไหมไฮโดรไลซ์', ['humectant', 'filmFormer'], [M, E], 'โปรตีนไหมที่ย่อยแล้ว ให้ความชุ่มชื้นและสัมผัสเนียนลื่น',
      en='Hydrolysed silk protein', kind='protein'),
    I('Sericin', 'เซริซิน', ['humectant', 'filmFormer'], [M, E], 'โปรตีนกาวไหม ให้ความชุ่มชื้นและสร้างฟิล์มปกป้องผิว',
      en='Silk sericin protein', kind='protein'),
    I('Hydrolyzed Wheat Protein', 'โปรตีนข้าวสาลีไฮโดรไลซ์', ['filmFormer', 'humectant'], [M, C], 'โปรตีนข้าวสาลีที่ย่อยแล้ว ช่วยสร้างฟิล์มนุ่มและเพิ่มความชุ่มชื้น',
      tips='ผู้แพ้กลูเตนรุนแรงที่ผิวควรระวัง', en='Film-forming wheat protein', kind='protein'),
]
