"""Plant oils and butters (natural triglyceride mixtures)."""
from common import C, E, I, M, S, T

_LINOLEIC = ' อุดมด้วยกรดไลโนเลอิก (โอเมก้า 6) ที่ช่วยเสริมเกราะผิว เนื้อบางเบา ซึมเร็ว จึงเหมาะกับผิวมัน/ผิวเป็นสิวด้วย'
_OLEIC = ' อุดมด้วยกรดโอเลอิก (โอเมก้า 9) เนื้อค่อนข้างหนา ให้ความชุ่มชื้นมาก เหมาะกับผิวแห้ง'
_OIL_TIPS = 'ใช้ 2–3 หยดผสมครีมหรือทาเป็นขั้นตอนสุดท้าย ผิวมัน/เป็นสิวง่ายควรเลือกน้ำมันที่มีไลโนเลอิกสูง'
_BUTTER = 'เนยพืชที่เป็นของแข็งที่อุณหภูมิห้องและละลายเมื่อสัมผัสผิว'
_BUTTER_GOOD = 'ให้ความชุ่มชื้นและนุ่มลื่นยาวนาน เคลือบผิวลดการเสียน้ำ เหมาะกับผิวแห้งและบริเวณที่แห้งมาก เช่น ข้อศอก ริมฝีปาก'


def oil(inci, th, what, good=None, tips=_OIL_TIPS, aka=(), use=(M, E), fn='emollient', note=None, en=None):
    return I(inci, th, fn, list(use), what, good=good, tips=tips, aka=aka, note=note, en=en, kind='oil')


ROWS = [
    # ---------- Butters ----------
    oil('Butyrospermum Parkii Butter', 'เชียบัตเตอร์', _BUTTER + ' สกัดจากเมล็ดต้นเชียในแอฟริกา มีกรดโอเลอิกและสเตียริก พร้อมวิตามินอีและสารต้านการอักเสบ',
        good=_BUTTER_GOOD, use=(C, M), aka=['Shea Butter', 'เชีย'], en='Shea butter; rich, soothing'),
    oil('Theobroma Cacao Seed Butter', 'โกโก้บัตเตอร์', _BUTTER + ' จากเมล็ดโกโก้ เนื้อแข็ง กลิ่นหอมช็อกโกแลตอ่อนๆ',
        good=_BUTTER_GOOD, use=(M,), aka=['Cocoa Butter', 'โกโก้'], note='comedo', en='Cocoa butter; rich, may clog pores'),
    oil('Mangifera Indica Seed Butter', 'มะม่วงบัตเตอร์', _BUTTER + ' จากเมล็ดมะม่วง เนื้อนุ่มเบากว่าเชียเล็กน้อย',
        good=_BUTTER_GOOD, use=(M,), aka=['Mango Butter', 'มะม่วง'], en='Mango butter'),
    oil('Garcinia Indica Seed Butter', 'โคคุมบัตเตอร์', _BUTTER + ' จากเมล็ดโคคุม (พืชตระกูลมังคุด) แข็ง ไม่เหนอะ ไม่ค่อยอุดตัน',
        good=_BUTTER_GOOD, use=(M,), aka=['Kokum Butter'], en='Kokum butter; light for a butter'),
    oil('Astrocaryum Murumuru Seed Butter', 'มูรูมูรูบัตเตอร์', _BUTTER + ' จากปาล์มอเมซอน มีกรดลอริกและไมริสติก',
        good=_BUTTER_GOOD, use=(M,), aka=['Murumuru Butter'], en='Murumuru butter'),
    oil('Theobroma Grandiflorum Seed Butter', 'คูปัวซูบัตเตอร์', _BUTTER + ' จากผลคูปัวซู (ญาติโกโก้) อุ้มน้ำได้ดีเป็นพิเศษ',
        good=_BUTTER_GOOD, use=(M,), aka=['Cupuacu Butter'], en='Cupuaçu butter; very water-binding'),
    # ---------- Light, linoleic-rich oils ----------
    oil('Helianthus Annuus Seed Oil', 'น้ำมันเมล็ดทานตะวัน', 'น้ำมันจากเมล็ดทานตะวัน' + _LINOLEIC + ' มีวิตามินอีตามธรรมชาติ',
        good='ช่วยฟื้นฟูเกราะผิว มีงานวิจัยในทารกว่าช่วยลดการเสียน้ำของผิว', use=(C, M), aka=['Sunflower Seed Oil', 'ทานตะวัน'],
        en='Sunflower oil; barrier-supporting linoleic acid'),
    oil('Vitis Vinifera Seed Oil', 'น้ำมันเมล็ดองุ่น', 'น้ำมันจากเมล็ดองุ่น' + _LINOLEIC + ' มีสารต้านอนุมูลอิสระ (โพลีฟีนอล)',
        use=(C, M), aka=['Grape Seed Oil', 'องุ่น'], en='Grapeseed oil; light, linoleic'),
    oil('Carthamus Tinctorius Seed Oil', 'น้ำมันดอกคำฝอย', 'น้ำมันจากเมล็ดดอกคำฝอย' + _LINOLEIC,
        use=(M,), aka=['Safflower Seed Oil', 'คำฝอย'], en='Safflower oil; light, linoleic'),
    oil('Cannabis Sativa Seed Oil', 'น้ำมันเมล็ดกัญชง', 'น้ำมันจากเมล็ดกัญชง (ไม่มีสาร THC/CBD)' + _LINOLEIC + ' และมีโอเมก้า 3 ด้วย',
        use=(M, E), aka=['Hemp Seed Oil', 'กัญชง'], en='Hemp seed oil; omega 3/6, non-psychoactive'),
    oil('Oenothera Biennis Oil', 'น้ำมันอีฟนิ่งพริมโรส', 'น้ำมันจากเมล็ดดอกอีฟนิ่งพริมโรส' + _LINOLEIC + ' และมีกรดแกมมาไลโนเลนิก (GLA)',
        good='ช่วยผิวแห้ง ผิวอักเสบง่าย', use=(M, E), aka=['Evening Primrose Oil'], en='Evening primrose oil; GLA-rich'),
    oil('Borago Officinalis Seed Oil', 'น้ำมันโบราจ', 'น้ำมันจากเมล็ดโบราจ มีกรดแกมมาไลโนเลนิก (GLA) สูงที่สุดในน้ำมันพืช',
        good='ช่วยลดการอักเสบและผิวแห้งคัน', use=(M, E), aka=['Borage Oil'], en='Borage oil; richest GLA source'),
    oil('Rosa Canina Fruit Oil', 'น้ำมันโรสฮิป', 'น้ำมันจากผลกุหลาบป่า มีกรดไลโนเลอิกและไลโนเลนิกสูง และมีโปรวิตามินเอ (ทรานส์เรติโนอิกตามธรรมชาติปริมาณน้อย)',
        good='ช่วยให้ผิวดูกระจ่างใส รอยแผลเป็นและรอยดำดูจางลง', tips='เสื่อมง่าย ควรเก็บในที่เย็นและพ้นแสง ' + _OIL_TIPS,
        aka=['Rosehip Oil', 'โรสฮิป'], en='Rosehip oil; brightening, scar-fading'),
    oil('Rosa Rubiginosa Seed Oil', 'น้ำมันเมล็ดโรสฮิป', 'น้ำมันจากเมล็ดกุหลาบป่าอีกสายพันธุ์ คุณสมบัติคล้ายน้ำมันโรสฮิป',
        aka=['Rosehip Seed Oil'], en='Rosehip seed oil'),
    oil('Punica Granatum Seed Oil', 'น้ำมันเมล็ดทับทิม', 'น้ำมันจากเมล็ดทับทิม มีกรดพูนิซิก (โอเมก้า 5) ที่ต้านอนุมูลอิสระ',
        aka=['Pomegranate Seed Oil', 'ทับทิม'], en='Pomegranate seed oil; antioxidant'),
    oil('Rubus Idaeus Seed Oil', 'น้ำมันเมล็ดราสเบอร์รี่', 'น้ำมันจากเมล็ดราสเบอร์รี่' + _LINOLEIC + ' มีวิตามินอีสูง',
        aka=['Raspberry Seed Oil'], en='Raspberry seed oil'),
    oil('Nigella Sativa Seed Oil', 'น้ำมันเทียนดำ', 'น้ำมันจากเมล็ดเทียนดำ มีสารไทโมควิโนนที่ต้านการอักเสบและเชื้อแบคทีเรีย',
        good='ช่วยผิวที่เป็นสิวและอักเสบ', tips='กลิ่นค่อนข้างแรง ' + _OIL_TIPS, aka=['Black Cumin Seed Oil', 'เทียนดำ'],
        en='Black seed oil; anti-inflammatory'),
    oil('Plukenetia Volubilis Seed Oil', 'น้ำมันดาวอินคา', 'น้ำมันจากเมล็ดถั่วดาวอินคา มีโอเมก้า 3 สูงมาก', aka=['Sacha Inchi Oil', 'ดาวอินคา'],
        en='Sacha inchi oil; omega-3 rich'),
    oil('Salvia Hispanica Seed Oil', 'น้ำมันเมล็ดเจีย', 'น้ำมันจากเมล็ดเจีย มีโอเมก้า 3 สูง', aka=['Chia Seed Oil', 'เจีย'],
        en='Chia seed oil; omega-3 rich'),
    oil('Brassica Oleracea Italica Seed Oil', 'น้ำมันเมล็ดบรอกโคลี', 'น้ำมันจากเมล็ดบรอกโคลี ให้สัมผัสลื่นคล้ายซิลิโคนตามธรรมชาติ',
        aka=['Broccoli Seed Oil'], en='Broccoli seed oil; natural silicone-like feel'),
    oil('Cucurbita Pepo Seed Oil', 'น้ำมันเมล็ดฟักทอง', 'น้ำมันจากเมล็ดฟักทอง มีวิตามินอีและสังกะสี', aka=['Pumpkin Seed Oil'],
        en='Pumpkin seed oil'),
    oil('Passiflora Edulis Seed Oil', 'น้ำมันเมล็ดเสาวรส', 'น้ำมันจากเมล็ดเสาวรส' + _LINOLEIC, aka=['Passion Fruit Seed Oil', 'Maracuja Oil'],
        en='Passion fruit seed oil; light, linoleic'),
    oil('Glycine Soja Oil', 'น้ำมันถั่วเหลือง', 'น้ำมันจากถั่วเหลือง' + _LINOLEIC, use=(C, M), aka=['Soybean Oil', 'ถั่วเหลือง'],
        en='Soybean oil'),
    oil('Zea Mays Germ Oil', 'น้ำมันจมูกข้าวโพด', 'น้ำมันจากจมูกข้าวโพด' + _LINOLEIC, aka=['Corn Germ Oil'], en='Corn germ oil'),
    oil('Triticum Vulgare Germ Oil', 'น้ำมันจมูกข้าวสาลี', 'น้ำมันจากจมูกข้าวสาลี มีวิตามินอีสูงมาก ให้ความชุ่มชื้น', aka=['Wheat Germ Oil'],
        note='comedo', en='Wheat germ oil; vitamin E rich'),
    oil('Aleurites Moluccanus Seed Oil', 'น้ำมันคุกุย', 'น้ำมันจากเมล็ดต้นคุกุย (ฮาวาย)' + _LINOLEIC, aka=['Kukui Nut Oil'],
        en='Kukui nut oil'),
    # ---------- Balanced / richer oils ----------
    oil('Olea Europaea Fruit Oil', 'น้ำมันมะกอก', 'น้ำมันจากผลมะกอก' + _OLEIC + ' มีสควาลีนและโพลีฟีนอล',
        tips='อาจไม่เหมาะกับผิวแพ้ง่ายที่เกราะผิวอ่อนแอ เพราะกรดโอเลอิกสูงอาจทำให้เกราะผิวอ่อนลงถ้าใช้เดี่ยวๆ', use=(C, M),
        aka=['Olive Oil', 'มะกอก'], en='Olive oil; rich, oleic'),
    oil('Prunus Amygdalus Dulcis Oil', 'น้ำมันอัลมอนด์', 'น้ำมันจากเมล็ดอัลมอนด์หวาน' + _OLEIC + ' อ่อนโยน นิยมใช้นวดผิว',
        tips='ผู้แพ้ถั่วควรระวัง', use=(C, M), aka=['Sweet Almond Oil', 'อัลมอนด์'], en='Sweet almond oil; gentle, oleic'),
    oil('Prunus Armeniaca Kernel Oil', 'น้ำมันเมล็ดแอปริคอต', 'น้ำมันจากเมล็ดแอปริคอต' + _OLEIC + ' เนื้อเบากว่าอัลมอนด์', use=(C, M),
        aka=['Apricot Kernel Oil'], en='Apricot kernel oil'),
    oil('Prunus Persica Kernel Oil', 'น้ำมันเมล็ดพีช', 'น้ำมันจากเมล็ดพีช' + _OLEIC, aka=['Peach Kernel Oil'], en='Peach kernel oil'),
    oil('Persea Gratissima Oil', 'น้ำมันอะโวคาโด', 'น้ำมันจากผลอะโวคาโด' + _OLEIC + ' มีวิตามินและสเตอรอลจากพืช',
        good='เหมาะกับผิวแห้งมาก ผิวขาดความยืดหยุ่น', aka=['Avocado Oil', 'อะโวคาโด'], en='Avocado oil; rich'),
    oil('Macadamia Ternifolia Seed Oil', 'น้ำมันแมคาเดเมีย', 'น้ำมันจากถั่วแมคาเดเมีย มีกรดปาล์มิโทเลอิก (โอเมก้า 7) ใกล้เคียงไขมันผิวของคนอายุน้อย',
        aka=['Macadamia Oil'], en='Macadamia oil; omega-7'),
    oil('Argania Spinosa Kernel Oil', 'น้ำมันอาร์แกน', 'น้ำมันจากเมล็ดต้นอาร์แกนของโมร็อกโก มีกรดโอเลอิกและไลโนเลอิกพอๆ กัน และวิตามินอีสูง',
        good='ให้ความชุ่มชื้นสมดุล ไม่หนักเกินไป ใช้ได้ทั้งผิวและผม', aka=['Argan Oil', 'อาร์แกน'], en='Argan oil; balanced, vitamin E rich'),
    oil('Camellia Japonica Seed Oil', 'น้ำมันคาเมลเลีย (ซึบากิ)', 'น้ำมันจากเมล็ดดอกคาเมลเลียญี่ปุ่น' + _OLEIC + ' ซึมเร็วกว่าที่คิด',
        aka=['Tsubaki Oil', 'Camellia Oil'], en='Camellia (tsubaki) oil'),
    oil('Camellia Oleifera Seed Oil', 'น้ำมันเมล็ดชา', 'น้ำมันจากเมล็ดชา' + _OLEIC, aka=['Tea Seed Oil', 'Camellia Oil'], en='Tea seed oil'),
    oil('Sclerocarya Birrea Seed Oil', 'น้ำมันมารูลา', 'น้ำมันจากเมล็ดผลมารูลา (แอฟริกา)' + _OLEIC + ' แต่ซึมเร็ว มีสารต้านอนุมูลอิสระสูง',
        aka=['Marula Oil', 'มารูลา'], en='Marula oil; antioxidant-rich'),
    oil('Oryza Sativa Bran Oil', 'น้ำมันรำข้าว', 'น้ำมันจากรำข้าว มีแกมมาโอรีซานอลและวิตามินอี ต้านอนุมูลอิสระ', use=(C, M),
        aka=['Rice Bran Oil', 'รำข้าว'], en='Rice bran oil; antioxidant'),
    oil('Sesamum Indicum Seed Oil', 'น้ำมันงา', 'น้ำมันจากเมล็ดงา มีสารเซซามอลที่ต้านอนุมูลอิสระ', use=(C, M), aka=['Sesame Oil', 'งา'],
        en='Sesame oil'),
    oil('Moringa Oleifera Seed Oil', 'น้ำมันเมล็ดมะรุม', 'น้ำมันจากเมล็ดมะรุม' + _OLEIC + ' คงตัวสูง ไม่เหม็นหืนง่าย', aka=['Moringa Oil', 'มะรุม'],
        en='Moringa oil; very stable'),
    oil('Limnanthes Alba Seed Oil', 'น้ำมันเมโดว์โฟม', 'น้ำมันที่คงตัวสูงมาก มีกรดไขมันสายยาวพิเศษ ช่วยให้สูตรมีความคงตัว',
        aka=['Meadowfoam Seed Oil'], en='Meadowfoam oil; extremely stable'),
    oil('Adansonia Digitata Seed Oil', 'น้ำมันเมล็ดเบาบับ', 'น้ำมันจากเมล็ดต้นเบาบับ มีโอเมก้า 3, 6, 9 สมดุล', aka=['Baobab Oil'], en='Baobab oil'),
    oil('Calophyllum Inophyllum Seed Oil', 'น้ำมันทามานู (กระทิง)', 'น้ำมันจากเมล็ดต้นกระทิง เนื้อเข้ม กลิ่นแรง มีสารต้านการอักเสบ',
        good='ใช้ดูแลรอยแผลเป็นและผิวอักเสบ', aka=['Tamanu Oil', 'กระทิง'], note='sensitize', en='Tamanu oil; healing, strong scent'),
    oil('Hippophae Rhamnoides Fruit Oil', 'น้ำมันซีบัคธอร์น', 'น้ำมันสีส้มเข้มจากผลซีบัคธอร์น มีแคโรทีนอยด์และโอเมก้า 7 สูง',
        tips='สีเข้มอาจติดผ้าได้ ใช้ปริมาณน้อย', aka=['Sea Buckthorn Oil'], en='Sea buckthorn oil; carotenoid-rich'),
    oil('Ricinus Communis Seed Oil', 'น้ำมันละหุ่ง', 'น้ำมันจากเมล็ดละหุ่ง เนื้อหนืดเหนียว มีกรดริซิโนเลอิกสูง ใช้ในลิปสติก คลีนซิ่ง และบำรุงขนตา',
        tips='หนืดมาก มักใช้ผสมน้ำมันอื่น', use=(C, M), aka=['Castor Oil', 'ละหุ่ง'], en='Castor oil; thick and glossy'),
    oil('Simmondsia Chinensis Seed Oil', 'น้ำมันโจโจบา', 'ของเหลวจากเมล็ดโจโจบาที่จริงๆ แล้วเป็นแว็กซ์เอสเทอร์ (ไม่ใช่ไตรกลีเซอไรด์) โครงสร้างใกล้เคียงไขมันผิวมนุษย์มาก',
        good='ให้ความชุ่มชื้นสมดุล ไม่หนัก ไม่ค่อยอุดตัน คงตัวสูง เหมาะทุกสภาพผิว', use=(C, M), aka=['Jojoba Oil', 'โจโจบา'],
        en='Jojoba; sebum-like wax ester'),
    oil('Cocos Nucifera Oil', 'น้ำมันมะพร้าว', 'น้ำมันจากเนื้อมะพร้าว มีกรดลอริกสูง เป็นของแข็งที่อุณหภูมิต่ำ',
        good='ให้ความชุ่มชื้นกับผิวกาย ผม และละลายเมคอัพได้', tips='ไม่แนะนำสำหรับผิวหน้าที่เป็นสิวง่าย เพราะอุดตันได้', use=(C, M),
        aka=['Coconut Oil', 'มะพร้าว'], note='comedo', en='Coconut oil; can clog pores'),
    oil('Orbignya Oleifera Seed Oil', 'น้ำมันบาบาสสุ', 'น้ำมันจากปาล์มบาบาสสุ คล้ายน้ำมันมะพร้าวแต่ละลายเร็วและเบากว่า', use=(C, M),
        aka=['Babassu Oil'], en='Babassu oil; lighter coconut alternative'),
    oil('Elaeis Guineensis Oil', 'น้ำมันปาล์ม', 'น้ำมันจากผลปาล์ม ใช้ในสบู่และครีม', use=(C, M), aka=['Palm Oil', 'ปาล์ม'], en='Palm oil'),
    oil('Canola Oil', 'น้ำมันคาโนลา', 'น้ำมันจากเมล็ดคาโนลา' + _OLEIC, use=(C, M), en='Canola oil'),
    oil('Olus Oil', 'น้ำมันพืช', 'น้ำมันพืชรวม (vegetable oil) ที่ไม่ระบุชนิด ให้ความชุ่มชื้น', use=(C, M), aka=['Vegetable Oil'],
        en='Vegetable oil'),
    oil('Hydrogenated Vegetable Oil', 'น้ำมันพืชไฮโดรจีเนต', 'น้ำมันพืชที่เติมไฮโดรเจนจนแข็งขึ้น ใช้ปรับเนื้อบาล์มและครีม', use=(C, M),
        fn=['emollient', 'thickener'], en='Hardened vegetable oil'),
    oil('Shea Butter Ethyl Esters', 'เชียบัตเตอร์เอทิลเอสเทอร์', 'เชียบัตเตอร์ที่ดัดแปลงให้เป็นของเหลวเบา ซึมเร็ว ไม่มัน', aka=['Shea Oil'],
        en='Light liquid shea esters'),
]
