"""Emulsifiers, thickeners, gelling agents, film formers, powders and colorants."""
from common import ALL, C, E, I, M, S, T

_EMU = 'อิมัลซิไฟเออร์ ช่วยให้น้ำกับน้ำมันผสมกันเป็นครีม/โลชั่นที่เนียนและไม่แยกชั้น'
_EMU_NAT = _EMU + ' ทำจากวัตถุดิบธรรมชาติ (พืช/น้ำตาล)'
_GUM = 'สารเพิ่มความข้นจากธรรมชาติ (gum) ทำให้เนื้อเจล/เซรั่มข้นขึ้นและคงตัว'
_SYN = 'พอลิเมอร์สังเคราะห์ที่ทำให้เนื้อเจล/ครีมข้น ใส และคงตัว ใช้ปริมาณน้อย'
_CELL = 'อนุพันธ์เซลลูโลสจากพืช ใช้เพิ่มความข้นและทำเจลใส'
_FILMF = 'พอลิเมอร์สร้างฟิล์มบางๆ บนผิว/เส้นผม ช่วยให้ผลิตภัณฑ์ติดทน'
_PIG = 'เม็ดสีแร่ที่ใช้ในเครื่องสำอางสีและกันแดดสีเนื้อ'
_IRON = 'เหล็กออกไซด์ เม็ดสีแร่ที่ใช้ให้สีเนื้อ แดง เหลือง ดำ ในรองพื้นและกันแดด tinted ยังช่วยกรองแสงที่มองเห็น (visible light) ซึ่งกระตุ้นฝ้าได้'

ROWS = [
    # ---------- Emulsifiers ----------
    I('Glyceryl Stearate', 'กลีเซอริลสเตียเรต', ['emulsifier', 'emollient'], [C, S, M], _EMU + ' และให้ผิวนุ่ม',
      en='Common co-emulsifier', smi='CCCCCCCCCCCCCCCCCC(=O)OCC(O)CO', f='C21H42O4'),
    I('Glyceryl Stearate SE', 'กลีเซอริลสเตียเรต เอสอี', 'emulsifier', [M, S], _EMU + ' (SE = self-emulsifying มีสบู่ผสมเล็กน้อย)', en='Self-emulsifying glyceryl stearate',
      kind='mixture'),
    I('Glyceryl Stearate Citrate', 'กลีเซอริลสเตียเรตซิเตรต', 'emulsifier', [M, S], _EMU_NAT, en='Natural emulsifier', kind='mixture'),
    I('Glyceryl Oleate', 'กลีเซอริลโอลีเอต', ['emulsifier', 'emollient'], [M, C], _EMU + ' ชนิดละลายในน้ำมัน', en='Oil-soluble emulsifier',
      smi='CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(O)CO', f='C21H40O4'),
    I('Glyceryl Behenate', 'กลีเซอริลบีเฮเนต', ['thickener', 'emulsifier'], [M], 'สารเพิ่มความข้นให้เฟสน้ำมัน', en='Oil-phase thickener', kind='mixture'),
    I('PEG-100 Stearate', 'พีอีจี-100 สเตียเรต', 'emulsifier', [S, M], _EMU + ' มักคู่กับกลีเซอริลสเตียเรต', en='Classic emulsifier', kind='polymer'),
    I('PEG-40 Stearate', 'พีอีจี-40 สเตียเรต', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Ceteareth-20', 'ซีทีอาเรท-20', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Ceteareth-6', 'ซีทีอาเรท-6', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Steareth-2', 'สเตียเรท-2', 'emulsifier', [M, S], _EMU, en='Emulsifier', kind='polymer'),
    I('Steareth-20', 'สเตียเรท-20', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Steareth-21', 'สเตียเรท-21', 'emulsifier', [M, S], _EMU, en='Emulsifier', kind='polymer'),
    I('Cetearyl Olivate', 'ซีทีอาริลโอลิเวต', 'emulsifier', [M], _EMU_NAT + ' จากน้ำมันมะกอก สร้างโครงสร้างคล้ายเกราะผิว (liquid crystal)',
      tips='มักคู่กับซอร์บิแทนโอลิเวต (Olivem 1000)', en='Olive-derived emulsifier', kind='mixture'),
    I('Sorbitan Olivate', 'ซอร์บิแทนโอลิเวต', 'emulsifier', [M], _EMU_NAT + ' จากน้ำมันมะกอก', en='Olive-derived emulsifier', kind='mixture'),
    I('Sorbitan Stearate', 'ซอร์บิแทนสเตียเรต', 'emulsifier', [M, S], _EMU, aka=['Span 60'], en='Sorbitan emulsifier',
      smi='CCCCCCCCCCCCCCCCCC(=O)OCC(O)C1OCC(O)C1O', f='C24H46O6'),
    I('Sorbitan Oleate', 'ซอร์บิแทนโอลีเอต', 'emulsifier', [M], _EMU + ' ชนิดละลายในน้ำมัน', aka=['Span 80'], en='Oil-soluble sorbitan emulsifier',
      smi='CCCCCCCC/C=C\\CCCCCCCC(=O)OCC(O)C1OCC(O)C1O', f='C24H44O6'),
    I('Sorbitan Sesquioleate', 'ซอร์บิแทนเซสควิโอลีเอต', 'emulsifier', [M], _EMU + ' สำหรับครีมน้ำในน้ำมัน', en='W/O emulsifier', kind='mixture'),
    I('Sorbitan Isostearate', 'ซอร์บิแทนไอโซสเตียเรต', 'emulsifier', [M, S], _EMU + ' สำหรับครีมน้ำในน้ำมัน', en='W/O emulsifier', kind='mixture'),
    I('Polyglyceryl-3 Methylglucose Distearate', 'โพลีกลีเซอริล-3 เมทิลกลูโคสไดสเตียเรต', 'emulsifier', [S, M], _EMU_NAT, en='PEG-free emulsifier',
      kind='polymer'),
    I('Polyglyceryl-6 Distearate', 'โพลีกลีเซอริล-6 ไดสเตียเรต', 'emulsifier', [M], _EMU_NAT, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-4 Isostearate', 'โพลีกลีเซอริล-4 ไอโซสเตียเรต', 'emulsifier', [M, S], _EMU + ' สำหรับครีมน้ำในน้ำมัน', en='W/O emulsifier', kind='polymer'),
    I('Sodium Stearoyl Glutamate', 'โซเดียมสเตียรอยล์กลูตาเมต', 'emulsifier', [S, M], _EMU + ' จากกรดอะมิโน อ่อนโยน',
      en='Amino-acid emulsifier', smi='CCCCCCCCCCCCCCCCCC(=O)NC(CCC(=O)O)C(=O)[O-].[Na+]', f='C23H42NNaO5'),
    I('Cetearyl Glucoside', 'ซีทีอาริลกลูโคไซด์', 'emulsifier', [M, S], _EMU_NAT + ' จากน้ำตาลกลูโคส', en='Sugar-based emulsifier', kind='mixture'),
    I('Arachidyl Glucoside', 'อะราคิดิลกลูโคไซด์', 'emulsifier', [M], _EMU_NAT, en='Sugar-based emulsifier', kind='mixture'),
    I('Methyl Glucose Sesquistearate', 'เมทิลกลูโคสเซสควิสเตียเรต', 'emulsifier', [M], _EMU_NAT, en='Sugar-based emulsifier', kind='mixture'),
    I('Sucrose Stearate', 'ซูโครสสเตียเรต', 'emulsifier', [M], _EMU_NAT + ' จากน้ำตาลซูโครส', en='Sugar ester emulsifier', kind='mixture'),
    I('Sodium Cetearyl Sulfate', 'โซเดียมซีทีอาริลซัลเฟต', 'emulsifier', [M], _EMU, en='Anionic emulsifier', kind='mixture'),
    I('Cetyl Phosphate', 'ซีทิลฟอสเฟต', 'emulsifier', [M, S], _EMU, en='Phosphate emulsifier', smi='CCCCCCCCCCCCCCCCOP(=O)(O)O', f='C16H35O4P'),
    I('Isostearic Acid', 'กรดไอโซสเตียริก', ['emulsifier', 'emollient'], [M], 'กรดไขมันกิ่งที่เป็นของเหลว ช่วยการกระจายตัวและทำให้ผิวนุ่ม', en='Liquid branched fatty acid',
      kind='mixture'),
    I('Cetrimonium Chloride', 'ซีทริโมเนียมคลอไรด์', ['filmFormer', 'preservative'], [C], 'สารลดแรงตึงผิวประจุบวก พบในครีมนวดผม ทำให้ลื่นนุ่ม และต้านเชื้ออ่อนๆ',
      en='Cationic conditioning agent', smi='CCCCCCCCCCCCCCCC[N+](C)(C)C.[Cl-]', f='C19H42ClN'),
    I('Behentrimonium Methosulfate', 'บีเฮนไตรโมเนียมเมโทซัลเฟต', ['filmFormer', 'emulsifier'], [C], 'สารปรับสภาพประจุบวกที่อ่อนโยน ทำให้ผม/ผิวลื่นนุ่ม', en='Gentle conditioning agent',
      kind='mixture'),
    # ---------- Natural gums & starches ----------
    I('Xanthan Gum', 'แซนแทนกัม', 'thickener', ALL, _GUM + ' ได้จากการหมักน้ำตาลด้วยแบคทีเรีย ใช้มากที่สุดในกลุ่มนี้', en='Fermentation gum thickener', kind='polymer'),
    I('Sclerotium Gum', 'สเคลอโรเทียมกัม', 'thickener', [M, E], _GUM + ' ให้สัมผัสนุ่มลื่นไม่เหนียว', en='Silky natural gum', kind='polymer'),
    I('Gellan Gum', 'เจลแลนกัม', 'thickener', [E, T], _GUM + ' ใช้แขวนลอยเม็ดบีดส์/แคปซูลในเซรั่ม', en='Suspending gum', kind='polymer'),
    I('Cyamopsis Tetragonoloba Gum', 'กัวร์กัม', 'thickener', [C, M], _GUM + ' จากเมล็ดถั่วกัวร์', aka=['Guar Gum'], en='Guar gum', kind='polymer'),
    I('Caesalpinia Spinosa Gum', 'ทาราคัม', 'thickener', [M, E], _GUM, aka=['Tara Gum'], en='Tara gum', kind='polymer'),
    I('Ceratonia Siliqua Gum', 'โลคัสบีนกัม', 'thickener', [M], _GUM + ' จากเมล็ดแครอบ', aka=['Locust Bean Gum'], en='Locust bean gum', kind='polymer'),
    I('Acacia Senegal Gum', 'กัมอารบิก', ['thickener', 'filmFormer'], [M, E], _GUM, aka=['Gum Arabic'], en='Gum arabic', kind='polymer'),
    I('Agar', 'วุ้น (อะการ์)', 'thickener', [M, E], 'สารให้เจลจากสาหร่ายทะเล', aka=['วุ้น'], en='Seaweed gelling agent', kind='polymer'),
    I('Chondrus Crispus Extract', 'คาราจีแนน', ['thickener', 'humectant'], [M, E], 'สารให้ความข้นจากสาหร่ายไอริชมอส', aka=['Carrageenan', 'Irish Moss'],
      en='Carrageenan seaweed thickener', kind='extract'),
    I('Algin', 'อัลจิน (โซเดียมอัลจิเนต)', ['thickener', 'filmFormer'], [M, E], 'สารให้เจลจากสาหร่ายสีน้ำตาล ใช้ทำมาส์กยางแบบผสมผง (rubber mask)',
      aka=['Sodium Alginate'], en='Alginate (rubber masks)', kind='polymer'),
    I('Hydroxypropyl Starch Phosphate', 'ไฮดรอกซีโพรพิลสตาร์ชฟอสเฟต', 'thickener', [M], 'แป้งดัดแปรที่ช่วยให้ครีมข้นนุ่ม', en='Modified starch thickener', kind='polymer'),
    I('Tapioca Starch', 'แป้งมันสำปะหลัง', ['absorbent', 'thickener'], [M, S], 'แป้งจากมันสำปะหลัง ให้สัมผัสแห้งนุ่ม ลดความมัน', aka=['แป้งมัน'], en='Tapioca starch',
      kind='polymer'),
    # ---------- Cellulose ----------
    I('Hydroxyethylcellulose', 'ไฮดรอกซีเอทิลเซลลูโลส', 'thickener', [C, M, E], _CELL, aka=['HEC'], en='Cellulose thickener', kind='polymer'),
    I('Cellulose Gum', 'เซลลูโลสกัม', 'thickener', [C, M], _CELL, aka=['CMC', 'Carboxymethyl Cellulose'], en='Cellulose gum', kind='polymer'),
    I('Hydroxypropyl Methylcellulose', 'ไฮดรอกซีโพรพิลเมทิลเซลลูโลส', ['thickener', 'filmFormer'], [C, M], _CELL, aka=['HPMC'], en='Cellulose thickener',
      kind='polymer'),
    I('Cellulose', 'เซลลูโลส', ['absorbent', 'thickener'], [M, S], 'เส้นใยพืชบริสุทธิ์ ใช้เป็นผงดูดซับหรือเพิ่มความข้น', en='Plant fibre', kind='polymer'),
    # ---------- Synthetic thickeners ----------
    I('Carbomer', 'คาร์โบเมอร์', 'thickener', [C, S, M, E], _SYN + ' ต้องปรับ pH ด้วยด่างจึงจะข้นเป็นเจล', en='Classic gel-forming polymer', kind='polymer'),
    I('Acrylates/C10-30 Alkyl Acrylate Crosspolymer', 'อะคริเลต/ซี10-30 อัลคิลอะคริเลตครอสพอลิเมอร์', ['thickener', 'emulsifier'], [C, S, M, E],
      _SYN + ' และช่วยให้น้ำกับน้ำมันอยู่ด้วยกันได้', en='Carbomer-type thickener/stabiliser', kind='polymer'),
    I('Sodium Polyacrylate', 'โซเดียมโพลีอะคริเลต', 'thickener', [S, M], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Sodium Acrylates Copolymer', 'โซเดียมอะคริเลตโคพอลิเมอร์', 'thickener', [M], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Ammonium Acryloyldimethyltaurate/VP Copolymer', 'แอมโมเนียมอะคริโลอิลไดเมทิลทอเรต/วีพีโคพอลิเมอร์', 'thickener', [S, M, E],
      _SYN + ' ไม่ต้องปรับ pH ให้เนื้อเจลครีมนุ่ม', aka=['Aristoflex AVC'], en='Easy synthetic thickener', kind='polymer'),
    I('Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer', 'ไฮดรอกซีเอทิลอะคริเลต/โซเดียมอะคริโลอิลไดเมทิลทอเรตโคพอลิเมอร์',
      ['thickener', 'emulsifier'], [S, M], _SYN + ' และช่วยให้สูตรคงตัว', en='Thickener/stabiliser', kind='polymer'),
    I('Sodium Polyacryloyldimethyl Taurate', 'โซเดียมโพลีอะคริโลอิลไดเมทิลทอเรต', 'thickener', [M, E], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Polyacrylate-13', 'โพลีอะคริเลต-13', 'thickener', [M, S], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Polyacrylate Crosspolymer-6', 'โพลีอะคริเลตครอสพอลิเมอร์-6', 'thickener', [M, E], _SYN + ' ทนต่อเกลือและสารสำคัญหลายชนิด', en='Robust synthetic thickener',
      kind='polymer'),
    I('Polyacrylamide', 'โพลีอะคริลาไมด์', 'thickener', [M, E], _SYN + ' มักมาคู่กับ C13-14 ไอโซพาราฟินและลอเรท-7', en='Synthetic thickener', kind='polymer'),
    I('C13-14 Isoparaffin', 'ซี13-14 ไอโซพาราฟิน', ['emollient', 'solvent'], [M, E], 'น้ำมันไฮโดรคาร์บอนเบาที่เป็นตัวพาของสารเพิ่มความข้น', en='Light hydrocarbon carrier',
      kind='mixture'),
    I('Glyceryl Acrylate/Acrylic Acid Copolymer', 'กลีเซอริลอะคริเลต/อะคริลิกแอซิดโคพอลิเมอร์', ['humectant', 'thickener'], [M, E], 'พอลิเมอร์ที่อุ้มน้ำ ให้ความชุ่มชื้นและสัมผัสลื่น',
      en='Moisture-binding polymer', kind='polymer'),
    I('Magnesium Aluminum Silicate', 'แมกนีเซียมอะลูมิเนียมซิลิเกต', ['thickener', 'absorbent'], [C, M, S], 'ดินแร่ที่ช่วยเพิ่มความข้นและแขวนลอยผง', aka=['Veegum'],
      en='Clay thickener', kind='mineral'),
    # ---------- Film formers ----------
    I('Polyvinyl Alcohol', 'โพลีไวนิลแอลกอฮอล์', 'filmFormer', [C], _FILMF + ' เป็นตัวหลักของมาส์กลอก (peel-off mask)', aka=['PVA'], en='Peel-off mask polymer',
      kind='polymer'),
    I('PVP', 'พีวีพี', 'filmFormer', [C, M], _FILMF, aka=['Polyvinylpyrrolidone'], en='Film former', kind='polymer'),
    I('VP/VA Copolymer', 'วีพี/วีเอโคพอลิเมอร์', 'filmFormer', [M], _FILMF, en='Film former', kind='polymer'),
    I('Triacontanyl PVP', 'ไตรอะคอนทานิลพีวีพี', 'filmFormer', [S], _FILMF + ' ช่วยให้กันแดดกันน้ำ', en='Water-resistant film former', kind='polymer'),
    I('Polyurethane-34', 'โพลียูรีเทน-34', 'filmFormer', [S], _FILMF + ' ยืดหยุ่น ไม่แตก', en='Flexible film former', kind='polymer'),
    # ---------- Powders & pigments ----------
    I('Talc', 'ทัลคัม', 'absorbent', [M], 'แร่ทัลก์บดละเอียด ดูดซับความมันและให้สัมผัสลื่น', tips='เกรดเครื่องสำอางต้องปลอดจากแร่ใยหิน', aka=['Talcum'],
      en='Talc powder', kind='mineral', f='Mg3Si4O10(OH)2'),
    I('Magnesium Stearate', 'แมกนีเซียมสเตียเรต', ['absorbent', 'thickener'], [M], 'ผงที่ช่วยให้แป้งอัดเกาะตัวและเกาะผิว', en='Powder binder', kind='mixture'),
    I('Zinc Stearate', 'ซิงค์สเตียเรต', ['absorbent', 'thickener'], [M], 'ผงที่ช่วยให้แป้งเกาะผิวและกันน้ำ', en='Powder binder', kind='mixture'),
    I('Calcium Carbonate', 'แคลเซียมคาร์บอเนต', ['absorbent', 'exfoliant'], [C, M], 'ผงแร่ขาว ใช้ดูดซับความมันหรือขัดเบาๆ', aka=['Chalk'], en='Chalk powder',
      kind='mineral', f='CaCO3'),
    I('Magnesium Carbonate', 'แมกนีเซียมคาร์บอเนต', 'absorbent', [M], 'ผงแร่ดูดซับความมันและกลิ่น', en='Absorbent powder', kind='mineral', f='MgCO3'),
    I('Mica', 'ไมกา', 'colorant', [S, M], 'แร่ไมกาบดละเอียด ให้ประกายวิบวับ (shimmer) และช่วยให้ผิวดูเปล่งปลั่ง', aka=['CI 77019'], en='Shimmer mineral',
      kind='mineral'),
    I('Synthetic Fluorphlogopite', 'ฟลูออร์โฟลโกไพต์สังเคราะห์', 'colorant', [M], 'ไมกาสังเคราะห์ที่บริสุทธิ์และประกายใสกว่า', aka=['Synthetic Mica'], en='Synthetic mica',
      kind='mineral'),
    I('Iron Oxides', 'เหล็กออกไซด์', 'colorant', [S, M], _IRON, aka=['CI 77491', 'CI 77492', 'CI 77499'], en='Iron oxide pigments; also block visible light',
      kind='mineral'),
    I('Ultramarines', 'อัลตรามารีน', 'colorant', [M], _PIG + ' ให้สีน้ำเงิน/ม่วง', aka=['CI 77007'], en='Blue pigment', kind='mineral'),
    I('Tin Oxide', 'ทินออกไซด์', 'colorant', [M], 'ใช้เคลือบเม็ดสีประกายให้สีสดและคงตัว', aka=['CI 77861'], en='Pearlescent coating', kind='mineral', f='SnO2'),
    I('Bismuth Oxychloride', 'บิสมัทออกซีคลอไรด์', 'colorant', [M], 'ผงมุกที่ให้ความเงาและเกาะผิวดี', aka=['CI 77163'], tips='บางคนรู้สึกคันกับสารนี้',
      en='Pearly powder', kind='mineral', f='BiOCl'),
    I('CI 19140', 'สีเหลือง (ทาร์ทราซีน)', 'colorant', [C, T], 'สีสังเคราะห์สีเหลือง ใช้แต่งสีผลิตภัณฑ์', aka=['Tartrazine', 'Yellow 5'], note='sensitize',
      en='Yellow dye (tartrazine)', smi='[Na+].[Na+].[Na+].[O-]C(=O)C1=NN(C(=O)C1N=Nc1ccc(cc1)S([O-])(=O)=O)c1ccc(cc1)S([O-])(=O)=O', f='C16H9N4Na3O9S2'),
    I('CI 16035', 'สีแดง (อัลลูราเรด)', 'colorant', [C, T], 'สีสังเคราะห์สีแดง ใช้แต่งสีผลิตภัณฑ์', aka=['Red 40', 'Allura Red'], en='Red dye', smi='COc1cc(N=Nc2c(O)ccc3cc(ccc23)S(=O)(=O)[O-])c(C)cc1S(=O)(=O)[O-].[Na+].[Na+]', f='C18H14N2Na2O8S2'),
    I('CI 42090', 'สีน้ำเงิน (บริลเลียนต์บลู)', 'colorant', [C, T], 'สีสังเคราะห์สีน้ำเงิน ใช้แต่งสีผลิตภัณฑ์', aka=['Blue 1'], en='Blue dye'),
    I('CI 75470', 'คาร์มีน', 'colorant', [M], 'สีแดงธรรมชาติจากแมลงโคชินีล', aka=['Carmine'], note='sensitize', en='Natural red from cochineal', kind='extract'),
    I('Caramel', 'คาราเมล', 'colorant', [C, T], 'สีน้ำตาลจากน้ำตาลที่ถูกเผา ใช้แต่งสี', en='Brown colour', kind='mixture'),
    I('Chlorophyllin-Copper Complex', 'คลอโรฟิลลินคอปเปอร์', ['colorant', 'antioxidant'], [C, T], 'สีเขียวจากคลอโรฟิลล์ ต้านอนุมูลอิสระเล็กน้อย', aka=['CI 75810'],
      en='Green colour from chlorophyll'),
]
