"""Preservatives, chelating agents, pH adjusters, solvents and stabilisers."""
from common import ALL, C, E, I, M, S, T

_PRES = ('สารกันเสีย ป้องกันเชื้อแบคทีเรีย ยีสต์ และราไม่ให้เติบโตในผลิตภัณฑ์ที่มีน้ำ '
         'ซึ่งสำคัญมากต่อความปลอดภัย ผลิตภัณฑ์ที่ไม่มีสารกันเสียจะเสียเร็วและอาจทำให้ผิวติดเชื้อ')
_PRES_TIPS = 'ใช้ในปริมาณที่กฎหมายกำหนดถือว่าปลอดภัย ควรใช้ผลิตภัณฑ์ให้หมดภายในระยะเวลาหลังเปิด (PAO)'
_PARABEN = ('สารกันเสียกลุ่มพาราเบน ใช้มานานกว่า 70 ปี มีประสิทธิภาพดีและแพ้น้อย '
            'ที่ความเข้มข้นที่อนุญาตหน่วยงานในยุโรปประเมินว่าปลอดภัย')
_CHEL = ('สารคีเลต จับไอออนโลหะ (เช่น แคลเซียม เหล็ก) ในน้ำ ทำให้สารกันเสียทำงานดีขึ้น '
         'ผลิตภัณฑ์ไม่เปลี่ยนสี/กลิ่น และสบู่เกิดฟองดีแม้ในน้ำกระด้าง')
_PH = 'สารปรับค่าความเป็นกรด-ด่าง (pH) ให้เหมาะกับผิวและให้สารสำคัญทำงานได้ดี'
_PH_TIPS = 'ใส่ในปริมาณน้อยมาก ถ้าอยู่ท้ายส่วนผสมไม่ต้องกังวล'

ROWS = [
    # ---------- Preservatives ----------
    I('Phenoxyethanol', 'ฟีนอกซีเอทานอล', 'preservative', ALL, _PRES + ' ตัวนี้ใช้มากที่สุดในปัจจุบัน',
      tips='อนุญาตไม่เกิน 1% ' + _PRES_TIPS, en='Most common preservative', smi='OCCOc1ccccc1', f='C8H10O2'),
    I('Ethylhexylglycerin', 'เอทิลเฮกซิลกลีเซอรีน', ['preservative', 'emollient'], ALL,
      'สารเสริมการกันเสีย (มักคู่กับฟีนอกซีเอทานอล) ช่วยให้ใช้สารกันเสียน้อยลง และให้ความชุ่มชื้นเล็กน้อย', en='Preservative booster',
      smi='CCCCC(CC)COCC(O)CO', f='C11H24O3'),
    I('Methylparaben', 'เมทิลพาราเบน', 'preservative', [C, M], _PARABEN, tips=_PRES_TIPS, aka=['paraben', 'พาราเบน'], en='Paraben preservative',
      smi='COC(=O)c1ccc(O)cc1', f='C8H8O3'),
    I('Ethylparaben', 'เอทิลพาราเบน', 'preservative', [C, M], _PARABEN, tips=_PRES_TIPS, aka=['paraben', 'พาราเบน'], en='Paraben preservative',
      smi='CCOC(=O)c1ccc(O)cc1', f='C9H10O3'),
    I('Propylparaben', 'โพรพิลพาราเบน', 'preservative', [C, M], _PARABEN + ' EU จำกัดความเข้มข้นต่ำกว่าเมทิล/เอทิลพาราเบน', tips=_PRES_TIPS,
      aka=['paraben', 'พาราเบน'], en='Paraben preservative', smi='CCCOC(=O)c1ccc(O)cc1', f='C10H12O3'),
    I('Butylparaben', 'บิวทิลพาราเบน', 'preservative', [M], _PARABEN + ' EU จำกัดความเข้มข้นต่ำ', tips=_PRES_TIPS, aka=['paraben', 'พาราเบน'],
      en='Paraben preservative', smi='CCCCOC(=O)c1ccc(O)cc1', f='C11H14O3'),
    I('Sodium Benzoate', 'โซเดียมเบนโซเอต', 'preservative', [C, M, T], _PRES + ' ใช้ในอาหารด้วย ทำงานได้ดีในสูตรที่เป็นกรด', tips=_PRES_TIPS,
      en='Food-grade preservative', smi='[Na+].[O-]C(=O)c1ccccc1', f='C7H5NaO2'),
    I('Benzoic Acid', 'กรดเบนโซอิก', 'preservative', [C, M], _PRES, tips=_PRES_TIPS, en='Preservative acid', smi='OC(=O)c1ccccc1', f='C7H6O2'),
    I('Potassium Sorbate', 'โพแทสเซียมซอร์เบต', 'preservative', [C, M, T], _PRES + ' เด่นเรื่องยับยั้งเชื้อรา ใช้ในอาหารด้วย', tips=_PRES_TIPS,
      en='Food-grade antifungal preservative', smi='C/C=C/C=C/C(=O)[O-].[K+]', f='C6H7KO2'),
    I('Sorbic Acid', 'กรดซอร์บิก', 'preservative', [M], _PRES, tips=_PRES_TIPS, en='Preservative acid', smi='C/C=C/C=C/C(=O)O', f='C6H8O2'),
    I('Benzyl Alcohol', 'เบนซิลแอลกอฮอล์', ['preservative', 'solvent', 'fragrance'], [C, M], _PRES + ' พบในพืชหลายชนิด มีกลิ่นหอมอ่อนๆ',
      tips='เป็นสารแต่งกลิ่นที่ EU ให้ระบุบนฉลาก', en='Preservative with mild scent', smi='OCc1ccccc1', f='C7H8O'),
    I('Dehydroacetic Acid', 'กรดดีไฮโดรอะซิติก', 'preservative', [C, M], _PRES + ' เด่นเรื่องยับยั้งเชื้อรา', tips=_PRES_TIPS, en='Antifungal preservative',
      smi='CC(=O)C1C(=O)OC(C)=CC1=O', f='C8H8O4'),
    I('Sodium Dehydroacetate', 'โซเดียมดีไฮโดรอะซิเตต', 'preservative', [C, M], _PRES, tips=_PRES_TIPS, en='Antifungal preservative',
      smi='CC(=O)C1=C([O-])C=C(C)OC1=O.[Na+]', f='C8H7NaO4'),
    I('Chlorphenesin', 'คลอร์ฟีนีซิน', 'preservative', [C, S, M], _PRES, tips=_PRES_TIPS, en='Preservative', smi='OCC(O)COc1ccc(Cl)cc1', f='C9H11ClO3'),
    I('Glyceryl Caprylate', 'กลีเซอริลแคพริเลต', ['preservative', 'emollient', 'emulsifier'], [M, E], 'สารให้ความนุ่มจากน้ำมันมะพร้าวที่ช่วยต้านเชื้อ ใช้ในสูตร "ไม่มีสารกันเสีย"',
      en='Natural preservative booster', smi='CCCCCCCC(=O)OCC(O)CO', f='C11H22O4'),
    I('Glyceryl Undecylenate', 'กลีเซอริลอันเดซิลีเนต', ['preservative', 'emollient'], [M], 'สารจากน้ำมันละหุ่งที่ต้านเชื้อและให้ความนุ่ม', en='Natural preservative booster',
      smi='C=CCCCCCCCCC(=O)OCC(O)CO', f='C14H26O4'),
    I('Caprylhydroxamic Acid', 'แคพริลไฮดรอกซามิกแอซิด', ['preservative', 'chelating'], [M, E], 'สารกันเสียทางเลือกที่ทำงานได้ดีในสูตร pH เป็นกลาง', en='Alternative preservative',
      smi='CCCCCCCC(=O)NO', f='C8H17NO2'),
    I('Hydroxyacetophenone', 'ไฮดรอกซีอะซิโตฟีโนน', ['preservative', 'soothing', 'antioxidant'], [M, E, T], 'สารเสริมการกันเสียที่ยังช่วยลดการระคายเคืองและต้านอนุมูลอิสระ',
      aka=['SymSave H'], en='Soothing preservative booster', smi='CC(=O)c1ccc(O)cc1', f='C8H8O2'),
    I('Sodium Anisate', 'โซเดียมแอนิเซต', 'preservative', [M, T], 'สารกันเสียจากธรรมชาติ (โป๊ยกั๊ก) มักคู่กับโซเดียมเลฟูลิเนต', en='Natural preservative',
      smi='COc1ccc(cc1)C(=O)[O-].[Na+]', f='C8H7NaO3'),
    I('Sodium Levulinate', 'โซเดียมเลฟูลิเนต', 'preservative', [M, T], 'สารกันเสียจากธรรมชาติ (จากข้าวโพด/อ้อย)', en='Natural preservative',
      smi='CC(=O)CCC(=O)[O-].[Na+]', f='C5H7NaO3'),
    I('p-Anisic Acid', 'กรดพี-แอนิซิก', 'preservative', [M], 'สารกันเสียจากธรรมชาติ', en='Natural preservative', smi='COc1ccc(cc1)C(=O)O', f='C8H8O3'),
    I('Phenethyl Alcohol', 'ฟีเนทิลแอลกอฮอล์', ['preservative', 'fragrance'], [M, T], 'แอลกอฮอล์กลิ่นกุหลาบที่มีฤทธิ์ต้านเชื้อ', en='Rose-scented preservative booster',
      smi='OCCc1ccccc1', f='C8H10O'),
    I('o-Cymen-5-ol', 'โอ-ไซเมน-5-ออล', ['preservative', 'antiAcne'], [C, M], 'สารต้านเชื้อแบคทีเรียและเชื้อรา', en='Antimicrobial', smi='CC(C)c1ccc(O)cc1C', f='C10H14O'),
    I('Methylisothiazolinone', 'เมทิลไอโซไทอะโซลิโนน', 'preservative', [C], _PRES + ' ฤทธิ์แรง', aka=['MIT', 'MI'], note='mit', en='Preservative; frequent allergen',
      smi='CN1SC=CC1=O', f='C4H5NOS'),
    I('Methylchloroisothiazolinone', 'เมทิลคลอโรไอโซไทอะโซลิโนน', 'preservative', [C], _PRES + ' มักใช้คู่กับ MIT (Kathon)', aka=['MCI', 'Kathon'], note='mit',
      en='Preservative; frequent allergen', smi='CN1SC(Cl)=CC1=O', f='C4H4ClNOS'),
    I('DMDM Hydantoin', 'ดีเอ็มดีเอ็ม ไฮแดนโทอิน', 'preservative', [C], _PRES, note='formaldehyde', en='Formaldehyde-releasing preservative',
      smi='CC1(C)N(CO)C(=O)N(CO)C1=O', f='C7H12N2O4'),
    I('Sodium Hydroxymethylglycinate', 'โซเดียมไฮดรอกซีเมทิลไกลซิเนต', 'preservative', [C], _PRES, note='formaldehyde', en='Formaldehyde-releasing preservative',
      smi='OCNCC(=O)[O-].[Na+]', f='C3H6NNaO3'),
    I('Imidazolidinyl Urea', 'อิมิดาโซลิดินิลยูเรีย', 'preservative', [C, M], _PRES, note='formaldehyde', en='Formaldehyde-releasing preservative'),
    I('Diazolidinyl Urea', 'ไดอะโซลิดินิลยูเรีย', 'preservative', [C, M], _PRES, note='formaldehyde', en='Formaldehyde-releasing preservative', smi='OCNC(=O)N(CO)C1N(CO)C(=O)N(CO)C1=O', f='C8H14N4O7'),
    I('2-Bromo-2-Nitropropane-1,3-Diol', 'บรอนอพอล', 'preservative', [C], _PRES, aka=['Bronopol'], note='formaldehyde', en='Bronopol preservative',
      smi='OCC(Br)(CO)[N+](=O)[O-]', f='C3H6BrNO4'),
    I('Iodopropynyl Butylcarbamate', 'ไอโอโดโพรพินิลบิวทิลคาร์บาเมต', 'preservative', [C], _PRES + ' เด่นเรื่องเชื้อรา EU ห้ามในผลิตภัณฑ์สำหรับเด็กเล็ก', aka=['IPBC'],
      en='Antifungal preservative', smi='CCCCNC(=O)OCC#CI', f='C8H12INO2'),
    I('Triclosan', 'ไตรโคลซาน', ['preservative', 'antiAcne'], [C], 'สารต้านเชื้อแบคทีเรียที่ปัจจุบันถูกจำกัดการใช้ในหลายประเทศเพราะข้อกังวลเรื่องเชื้อดื้อยาและสิ่งแวดล้อม',
      en='Restricted antibacterial', smi='Oc1cc(Cl)ccc1Oc1ccc(Cl)cc1Cl', f='C12H7Cl3O2'),
    I('Polyaminopropyl Biguanide', 'โพลีอะมิโนโพรพิลไบกัวไนด์', 'preservative', [C, T], _PRES, aka=['PHMB'], en='Polymeric preservative', kind='polymer'),
    I('Leuconostoc/Radish Root Ferment Filtrate', 'หัวไชเท้าหมักลิวโคนอสตอก', 'preservative', [M, E, T], 'สารกันเสียจากธรรมชาติที่ได้จากการหมักหัวไชเท้า',
      en='Natural ferment preservative', kind='ferment'),
    # ---------- Chelating agents ----------
    I('Disodium EDTA', 'ไดโซเดียมอีดีทีเอ', 'chelating', ALL, _CHEL, tips=_PH_TIPS, aka=['EDTA'], en='Common chelating agent',
      smi='[Na+].[Na+].OC(=O)CN(CC([O-])=O)CCN(CC(O)=O)CC([O-])=O', f='C10H14N2Na2O8'),
    I('Tetrasodium EDTA', 'เตตระโซเดียมอีดีทีเอ', 'chelating', [C], _CHEL, tips=_PH_TIPS, aka=['EDTA'], en='Chelating agent',
      smi='[Na+].[Na+].[Na+].[Na+].[O-]C(=O)CN(CC([O-])=O)CCN(CC([O-])=O)CC([O-])=O', f='C10H12N2Na4O8'),
    I('Trisodium Ethylenediamine Disuccinate', 'ไตรโซเดียมเอทิลีนไดอะมีนไดซัคซิเนต', 'chelating', [C, S, M], _CHEL + ' ย่อยสลายได้ทางชีวภาพ ใช้แทน EDTA',
      aka=['EDDS'], en='Biodegradable chelator',
      smi='[Na+].[Na+].[Na+].[O-]C(=O)CC(NCCNC(CC(=O)O)C([O-])=O)C([O-])=O', f='C10H13N2Na3O8'),
    I('Tetrasodium Glutamate Diacetate', 'เตตระโซเดียมกลูตาเมตไดอะซิเตต', 'chelating', [C, M], _CHEL + ' ทำจากพืช ย่อยสลายได้', aka=['GLDA'],
      en='Plant-based chelator', smi='[O-]C(=O)CCC(N(CC([O-])=O)CC([O-])=O)C([O-])=O.[Na+].[Na+].[Na+].[Na+]', f='C9H9NNa4O8'),
    I('Sodium Phytate', 'โซเดียมไฟเตต', 'chelating', [C, M], _CHEL + ' จากรำข้าว/ธัญพืช', en='Natural chelator'),
    I('Phytic Acid', 'กรดไฟติก', ['chelating', 'exfoliant'], [C, M, E], _CHEL + ' และช่วยผลัดเซลล์อ่อนๆ', en='Natural chelator, mild exfoliant',
      smi='OP(=O)(O)OC1C(OP(=O)(O)O)C(OP(=O)(O)O)C(OP(=O)(O)O)C(OP(=O)(O)O)C1OP(=O)(O)O', f='C6H18O24P6'),
    I('Sodium Gluconate', 'โซเดียมกลูโคเนต', 'chelating', [C, M, T], _CHEL, en='Gentle chelator', smi='OCC(O)C(O)C(O)C(O)C(=O)[O-].[Na+]', f='C6H11NaO7'),
    I('Etidronic Acid', 'กรดเอทิโดรนิก', 'chelating', [C], _CHEL, en='Chelating agent', smi='CC(O)(P(=O)(O)O)P(=O)(O)O', f='C2H8O7P2'),
    # ---------- pH adjusters ----------
    I('Citric Acid', 'กรดซิตริก', ['phAdjuster', 'chelating', 'exfoliant'], [C, M, E, T], _PH + ' ได้จากผลไม้ตระกูลส้ม เป็น AHA ด้วยแต่ส่วนใหญ่ใส่ปริมาณน้อยเพื่อปรับ pH',
      tips=_PH_TIPS, en='pH adjuster from citrus', smi='OC(=O)CC(O)(CC(=O)O)C(=O)O', f='C6H8O7'),
    I('Sodium Citrate', 'โซเดียมซิเตรต', ['phAdjuster', 'chelating'], [C, M, T], _PH + ' (บัฟเฟอร์)', tips=_PH_TIPS, en='pH buffer',
      smi='[Na+].[Na+].[Na+].[O-]C(=O)CC(O)(CC([O-])=O)C([O-])=O', f='C6H5Na3O7'),
    I('Sodium Hydroxide', 'โซเดียมไฮดรอกไซด์', 'phAdjuster', [C, M, E], _PH + ' (ด่างแก่/โซดาไฟ) ใช้ปริมาณน้อยและถูกทำให้เป็นกลางในสูตรแล้ว จึงไม่กัดผิว',
      tips=_PH_TIPS, aka=['โซดาไฟ', 'Caustic Soda', 'Lye'], en='Neutralised alkali', kind='mineral', f='NaOH'),
    I('Potassium Hydroxide', 'โพแทสเซียมไฮดรอกไซด์', 'phAdjuster', [C, M], _PH + ' ในโฟมล้างหน้าใช้ทำปฏิกิริยากับกรดไขมันให้กลายเป็นสบู่', tips=_PH_TIPS,
      aka=['KOH'], en='Alkali; makes soap in cleansers', kind='mineral', f='KOH'),
    I('Triethanolamine', 'ไตรเอทาโนลามีน', ['phAdjuster', 'emulsifier'], [C, S, M], _PH + ' ใช้ทำให้คาร์โบเมอร์ข้นเป็นเจล', tips=_PH_TIPS, aka=['TEA'],
      en='pH adjuster for gels', smi='OCCN(CCO)CCO', f='C6H15NO3'),
    I('Tromethamine', 'โทรเมทามีน', 'phAdjuster', [S, M], _PH, tips=_PH_TIPS, aka=['Tris'], en='pH adjuster', smi='NC(CO)(CO)CO', f='C4H11NO3'),
    I('Arginine', 'อาร์จินีน', ['phAdjuster', 'humectant'], [C, M], _PH + ' และเป็นกรดอะมิโนที่ให้ความชุ่มชื้น', tips=_PH_TIPS, en='Amino acid pH adjuster',
      smi='NC(CCCNC(N)=N)C(=O)O', f='C6H14N4O2'),
    I('Aminomethyl Propanol', 'อะมิโนเมทิลโพรพานอล', 'phAdjuster', [S, M], _PH, tips=_PH_TIPS, aka=['AMP'], en='pH adjuster',
      smi='CC(C)(N)CO', f='C4H11NO'),
    I('Sodium Bicarbonate', 'โซเดียมไบคาร์บอเนต', ['phAdjuster', 'exfoliant'], [C], 'เบกกิ้งโซดา ปรับ pH และขัดเบาๆ', tips='เป็นด่าง ไม่ควรใช้ขัดหน้าบ่อย',
      aka=['Baking Soda', 'เบกกิ้งโซดา'], en='Baking soda', kind='mineral', f='NaHCO3'),
    I('Sodium Carbonate', 'โซเดียมคาร์บอเนต', 'phAdjuster', [C], _PH, tips=_PH_TIPS, en='Alkaline pH adjuster', kind='mineral', f='Na2CO3'),
    I('Phosphoric Acid', 'กรดฟอสฟอริก', 'phAdjuster', [C, M], _PH, tips=_PH_TIPS, en='pH adjuster', kind='mineral', f='H3PO4'),
    I('Disodium Phosphate', 'ไดโซเดียมฟอสเฟต', 'phAdjuster', [M, E], _PH + ' (บัฟเฟอร์)', tips=_PH_TIPS, en='pH buffer', kind='mineral', f='Na2HPO4'),
    # ---------- Solvents & stabilisers ----------
    I('Aqua', 'น้ำ', 'solvent', ALL, 'น้ำบริสุทธิ์ (ผ่านการกรองหรือกลั่น) เป็นตัวทำละลายหลักของสกินแคร์ส่วนใหญ่ ละลายสารที่ชอบน้ำและทำให้เนื้อสัมผัสบางเบา',
      aka=['Water', 'น้ำบริสุทธิ์', 'Eau'], en='Water, the main solvent', smi='O', f='H2O'),
    I('Ethoxydiglycol', 'เอทอกซีไดไกลคอล', ['solvent', 'humectant'], [E], 'ตัวทำละลายที่ช่วยให้สารสำคัญซึมผ่านผิวได้ดีขึ้น', aka=['Transcutol'],
      en='Penetration-enhancing solvent', smi='CCOCCOCCO', f='C6H14O3'),
    I('Isopropyl Alcohol', 'ไอโซโพรพิลแอลกอฮอล์', 'solvent', [T, C], 'แอลกอฮอล์ตัวทำละลายที่ระเหยเร็ว', note='alcohol', aka=['Isopropanol', 'IPA'],
      en='Isopropanol', smi='CC(C)O', f='C3H8O'),
    I('Dimethyl Isosorbide', 'ไดเมทิลไอโซซอร์ไบด์', 'solvent', [E], 'ตัวทำละลายจากพืชที่ช่วยให้สารสำคัญ (เช่น วิตามินซี) ซึมผ่านผิวได้ดีขึ้น', en='Plant-based carrier solvent',
      smi='COC1COC2C(OC)COC12', f='C8H14O4'),
    I('Propylene Carbonate', 'โพรพิลีนคาร์บอเนต', 'solvent', [M], 'ตัวทำละลายที่ใช้ช่วยให้เคลย์/ผงกระจายตัว', en='Solvent', smi='CC1COC(=O)O1', f='C4H6O3'),
    I('Sodium Metabisulfite', 'โซเดียมเมตาไบซัลไฟต์', 'antioxidant', [E, M], 'สารกันการเสื่อมสภาพ ช่วยป้องกันสารสำคัญ (เช่น วิตามินซี) จากการออกซิไดซ์',
      en='Stabilising antioxidant', kind='mineral', f='Na2S2O5'),
]
