"""Retinoids, peptides, growth factors and other anti-ageing actives."""
from common import C, E, I, M, S, T

_RET = ('เรตินอยด์ (อนุพันธ์วิตามินเอ) ทำงานผ่านตัวรับกรดเรติโนอิกในเซลล์ผิว '
        'กระตุ้นการผลัดเซลล์และการสร้างคอลลาเจน')
_RET_GOOD = 'ลดริ้วรอยและรอยเหี่ยวย่น ผิวเรียบเนียนขึ้น ลดสิวอุดตัน รูขุมขนดูเล็กลง จุดด่างดำจางลง'
_RET_TIPS = ('เริ่มใช้ 2–3 คืนต่อสัปดาห์ ปริมาณเท่าเมล็ดถั่วสำหรับทั้งหน้า แล้วค่อยๆ เพิ่ม '
             'ช่วงแรกอาจลอกแดง (retinization) ใช้คู่มอยส์เจอไรเซอร์และทากันแดดทุกวัน')
_RET_CHAIN = ' ผิวต้องเปลี่ยนเป็นกรดเรติโนอิกตามลำดับ: เรตินิลเอสเทอร์ → เรตินอล → เรตินัล → กรดเรติโนอิก ยิ่งอยู่ใกล้กรดเรติโนอิกยิ่งแรง'
_PEP = 'เปปไทด์ (กรดอะมิโนหลายตัวต่อกัน) ที่ทำหน้าที่เป็นสัญญาณให้เซลล์ผิว'
_PEP_TIPS = 'อ่อนโยน ใช้ได้ทั้งเช้าเย็นและร่วมกับสารอื่นได้แทบทุกตัว ผลลัพธ์ค่อยเป็นค่อยไป'
_RET_BASE = 'CC1=C(C(C)(C)CCC1)/C=C/C(C)=C/C=C/C(C)=C/'

ROWS = [
    I('Retinol', 'เรตินอล (วิตามินเอ)', ['retinoid', 'antiAging'], [E, M], _RET + _RET_CHAIN,
      good=_RET_GOOD, tips='ความเข้มข้นเริ่มต้น 0.1–0.3% ' + _RET_TIPS, aka=['Vitamin A', 'วิตามินเอ'], note='retinoid',
      en='Gold-standard OTC retinoid', smi=_RET_BASE + 'CO', f='C20H30O'),
    I('Retinal', 'เรตินัล', ['retinoid', 'antiAging', 'antiAcne'], [E, M], _RET + ' อยู่ห่างจากกรดเรติโนอิกเพียงขั้นเดียว จึงออกฤทธิ์เร็วกว่าเรตินอล และยังต้านเชื้อแบคทีเรียสิว',
      good=_RET_GOOD, tips='ความเข้มข้น 0.05–0.1% ' + _RET_TIPS, aka=['Retinaldehyde', 'วิตามินเอ'], note='retinoid',
      en='Faster-acting retinoid', smi=_RET_BASE + 'C=O', f='C20H28O'),
    I('Retinyl Palmitate', 'เรตินิลปาล์มิเตต', ['retinoid', 'antioxidant'], [M, S], _RET + _RET_CHAIN + ' ตัวนี้อ่อนที่สุดในกลุ่ม',
      good='ช่วยบำรุงผิวแบบอ่อนโยนมาก แต่ผลลัพธ์ต่อริ้วรอยน้อยกว่าเรตินอล', aka=['Vitamin A', 'วิตามินเอ'],
      en='Mildest retinyl ester', smi=_RET_BASE + 'COC(=O)CCCCCCCCCCCCCCC', f='C36H60O2'),
    I('Retinyl Acetate', 'เรตินิลอะซิเตต', 'retinoid', [M], _RET + _RET_CHAIN + ' อ่อนโยน', aka=['Vitamin A'], en='Mild retinyl ester',
      smi=_RET_BASE + 'COC(C)=O', f='C22H32O2'),
    I('Retinyl Propionate', 'เรตินิลโพรพิโอเนต', 'retinoid', [M, E], _RET + _RET_CHAIN + ' อ่อนโยนกว่าเรตินอล', aka=['Vitamin A'],
      en='Gentle retinyl ester', smi=_RET_BASE + 'COC(=O)CC', f='C23H34O2'),
    I('Hydroxypinacolone Retinoate', 'ไฮดรอกซีพินาโคโลนเรติโนเอต', ['retinoid', 'antiAging'], [E, M],
      'เอสเทอร์ของกรดเรติโนอิกที่จับกับตัวรับได้โดยตรงโดยไม่ต้องเปลี่ยนรูป แต่ระคายเคืองน้อยกว่า', good=_RET_GOOD, tips=_RET_TIPS,
      aka=['HPR', 'Granactive Retinoid'], note='retinoid', en='Gentle retinoic-acid ester',
      smi=_RET_BASE + 'C(=O)OCC(=O)C(C)(C)C', f='C26H38O3'),
    I('Retinoic Acid', 'กรดเรติโนอิก (ทรีทิโนอิน)', ['retinoid', 'antiAging', 'antiAcne'], [E],
      'รูปแบบออกฤทธิ์ของวิตามินเอ เป็นยาที่ต้องสั่งโดยแพทย์ ไม่อนุญาตในเครื่องสำอาง', good=_RET_GOOD, tips=_RET_TIPS,
      aka=['Tretinoin', 'ทรีทิโนอิน'], note='retinoid', en='Prescription retinoid (tretinoin)', smi=_RET_BASE + 'C(=O)O', f='C20H28O2'),
    I('Adapalene', 'อะดาพาลีน', ['retinoid', 'antiAcne'], [E], 'เรตินอยด์สังเคราะห์รุ่นที่ 3 ที่คงตัวและระคายเคืองน้อยกว่าทรีทิโนอิน เป็นยารักษาสิว',
      good='ลดสิวอุดตันและสิวอักเสบ', tips=_RET_TIPS, aka=['Differin'], note='retinoid', en='Retinoid acne medication',
      smi='COc1ccc(cc1C12CC3CC(CC(C3)C1)C2)-c1ccc2cc(ccc2c1)C(=O)O', f='C28H28O3'),
    I('Bakuchiol', 'บาคูชิออล', ['antiAging', 'antioxidant'], [E, M],
      'สารจากเมล็ดพืชบาบชี (Psoralea corylifolia) ไม่ใช่เรตินอยด์ แต่มีงานวิจัยว่าให้ผลคล้ายเรตินอลโดยระคายเคืองน้อยกว่า',
      good='ลดริ้วรอยและจุดด่างดำ ต้านอนุมูลอิสระ ใช้ได้ทั้งเช้าเย็น', tips='ทางเลือกสำหรับผิวแพ้ง่ายหรือคนที่ใช้เรตินอลไม่ได้',
      aka=['retinol alternative'], en='Plant retinol alternative', smi='CC(C)=CCCC(C)(C=C)/C=C/c1ccc(O)cc1', f='C18H24O'),
    I('Nephelium Lappaceum Leaf Extract', 'สารสกัดใบเงาะ', 'antiAging', [E, M], 'สารสกัดใบเงาะที่มีงานวิจัยว่าทำงานคล้ายเรตินอลแบบอ่อนโยน',
      aka=['Rambutan', 'เงาะ'], en='Rambutan; gentle retinol alternative', kind='extract'),
    I('Adenosine', 'อะดีโนซีน', ['antiAging', 'soothing'], [M, E, S], 'สารที่พบในเซลล์ทุกชนิด (ส่วนหนึ่งของ ATP) เกาหลีรับรองเป็นสารลดริ้วรอย',
      good='ช่วยให้ผิวเรียบและลดริ้วรอย ลดการอักเสบ', en='Wrinkle-smoothing nucleoside',
      smi='Nc1ncnc2c1ncn2C1OC(CO)C(O)C1O', f='C10H13N5O4'),
    I('Kinetin', 'ไคเนทิน', ['antiAging', 'antioxidant'], [E, M], 'ฮอร์โมนพืชกลุ่มไซโตไคนิน ช่วยชะลอความเสื่อมของเซลล์ อ่อนโยน', aka=['Furfuryladenine'],
      en='Gentle plant cytokinin', smi='c1coc(c1)CNc1ncnc2nc[nH]c12', f='C10H9N5O'),
    I('DMAE', 'ดีเอ็มเออี', 'antiAging', [E, M], 'สารที่ช่วยให้ผิวดูกระชับขึ้นชั่วคราว', aka=['Dimethyl MEA', 'Deanol'], en='Temporary firming',
      smi='CN(C)CCO', f='C4H11NO'),
    # ---------- Peptides ----------
    I('Palmitoyl Tripeptide-1', 'ปาล์มิทอยล์ไตรเปปไทด์-1', ['antiAging', 'barrier'], [E, M], _PEP + ' กระตุ้นการสร้างคอลลาเจน (signal peptide)',
      good='ช่วยให้ผิวกระชับ ลดริ้วรอย', tips=_PEP_TIPS, aka=['peptide', 'เปปไทด์', 'Matrixyl', 'Pal-GHK'], en='Collagen-signalling peptide',
      kind='peptide'),
    I('Palmitoyl Tetrapeptide-7', 'ปาล์มิทอยล์เตตระเปปไทด์-7', ['antiAging', 'soothing'], [E, M], _PEP + ' ลดสารก่อการอักเสบที่ทำลายคอลลาเจน',
      good='ใช้คู่กับปาล์มิทอยล์ไตรเปปไทด์-1 (Matrixyl 3000) เพื่อลดริ้วรอย', tips=_PEP_TIPS, aka=['peptide', 'เปปไทด์', 'Matrixyl 3000'],
      en='Anti-inflammatory signal peptide', kind='peptide'),
    I('Palmitoyl Pentapeptide-4', 'ปาล์มิทอยล์เพนตะเปปไทด์-4', 'antiAging', [E, M], _PEP + ' กระตุ้นการสร้างคอลลาเจนและอีลาสติน เป็นเปปไทด์ที่มีงานวิจัยมาก',
      good='ลดริ้วรอยและความหยาบกร้าน', tips=_PEP_TIPS, aka=['peptide', 'เปปไทด์', 'Matrixyl', 'Pal-KTTKS'], en='Well-studied collagen peptide',
      kind='peptide'),
    I('Palmitoyl Tripeptide-5', 'ปาล์มิทอยล์ไตรเปปไทด์-5', 'antiAging', [E, M], _PEP + ' เลียนแบบกลไกกระตุ้นคอลลาเจนของ TGF-β', tips=_PEP_TIPS,
      aka=['peptide', 'Syn-Coll'], en='Collagen-boosting peptide', kind='peptide'),
    I('Palmitoyl Tripeptide-38', 'ปาล์มิทอยล์ไตรเปปไทด์-38', 'antiAging', [E, M], _PEP + ' กระตุ้นการสร้างองค์ประกอบของผิวหลายชนิด', tips=_PEP_TIPS,
      aka=['peptide', 'Matrixyl Synthe\'6'], en='Matrix-boosting peptide', kind='peptide'),
    I('Palmitoyl Hexapeptide-12', 'ปาล์มิทอยล์เฮกซะเปปไทด์-12', 'antiAging', [E, M], _PEP + ' ช่วยเรื่องความยืดหยุ่นของผิว', tips=_PEP_TIPS,
      aka=['peptide'], en='Elasticity peptide', kind='peptide'),
    I('Acetyl Hexapeptide-8', 'อะซิทิลเฮกซะเปปไทด์-8', 'antiAging', [E, M], _PEP + ' ลดการหดตัวของกล้ามเนื้อเล็กน้อย (neurotransmitter-inhibiting peptide)',
      good='ช่วยให้ริ้วรอยจากการแสดงสีหน้า เช่น ตีนกา ดูตื้นขึ้นเล็กน้อย', tips=_PEP_TIPS,
      aka=['peptide', 'เปปไทด์', 'Argireline', 'Acetyl Hexapeptide-3'], en='"Botox-like" expression-line peptide', kind='peptide'),
    I('Acetyl Octapeptide-3', 'อะซิทิลออกตะเปปไทด์-3', 'antiAging', [E], _PEP + ' คล้ายอาร์จิรีลีนแต่ยาวกว่า', tips=_PEP_TIPS, aka=['peptide', 'SNAP-8'],
      en='Expression-line peptide', kind='peptide'),
    I('Pentapeptide-18', 'เพนตะเปปไทด์-18', 'antiAging', [E], _PEP + ' ช่วยลดริ้วรอยจากการแสดงสีหน้า', tips=_PEP_TIPS, aka=['peptide', 'Leuphasyl'],
      en='Expression-line peptide', kind='peptide'),
    I('Dipeptide Diaminobutyroyl Benzylamide Diacetate', 'ไดเปปไทด์ไดอะมิโนบิวทิรอยล์เบนซิลาไมด์ไดอะซิเตต', 'antiAging', [E],
      _PEP + ' เลียนแบบพิษงูวัด ช่วยให้ริ้วรอยจากการแสดงสีหน้าดูตื้นขึ้น', tips=_PEP_TIPS, aka=['peptide', 'SYN-AKE'],
      en='Snake-venom-like peptide', kind='peptide'),
    I('Copper Tripeptide-1', 'คอปเปอร์เปปไทด์', ['antiAging', 'soothing'], [E], 'เปปไทด์ GHK ที่จับกับทองแดง มีในร่างกายตามธรรมชาติ ช่วยในการสมานแผลและการสร้างคอลลาเจน',
      good='ผิวกระชับ ลดริ้วรอย ช่วยฟื้นฟูผิว', tips='ไม่ควรใช้พร้อมวิตามินซีบริสุทธิ์หรือกรดผลัดเซลล์ในขั้นตอนเดียวกัน',
      aka=['peptide', 'เปปไทด์', 'GHK-Cu', 'Copper Peptide'], en='Copper peptide for repair', kind='peptide'),
    I('Myristoyl Pentapeptide-17', 'ไมริสทอยล์เพนตะเปปไทด์-17', 'antiAging', [E], _PEP + ' นิยมในเซรั่มบำรุงขนตาให้ดูยาวและหนาขึ้น', aka=['peptide', 'lash serum'],
      en='Lash-enhancing peptide', kind='peptide'),
    I('sh-Oligopeptide-1', 'อีจีเอฟ (โอลิโกเปปไทด์-1)', ['antiAging', 'soothing'], [E], 'โปรตีนที่เลียนแบบปัจจัยการเจริญเติบโตของผิว (EGF) ผลิตด้วยเทคโนโลยีชีวภาพ ช่วยฟื้นฟูผิว',
      aka=['EGF', 'growth factor'], en='Epidermal growth factor', kind='protein'),
    I('sh-Polypeptide-1', 'บีเอฟจีเอฟ (โพลีเปปไทด์-1)', 'antiAging', [E], 'ปัจจัยการเจริญเติบโตชนิด bFGF ผลิตด้วยเทคโนโลยีชีวภาพ', aka=['bFGF', 'growth factor'],
      en='Fibroblast growth factor', kind='protein'),
    I('Hydrolyzed Collagen', 'คอลลาเจนไฮโดรไลซ์', ['humectant', 'filmFormer'], [M, E], 'คอลลาเจนที่ถูกย่อยเป็นชิ้นเล็ก',
      good='ให้ความชุ่มชื้นและสร้างฟิล์มนุ่มบนผิว', tips='โมเลกุลยังใหญ่เกินจะซึมไปเพิ่มคอลลาเจนในผิวได้ ทำหน้าที่หลักคือให้ความชุ่มชื้น',
      aka=['collagen', 'คอลลาเจน'], en='Hydrating collagen (does not add collagen to skin)', kind='protein'),
    I('Soluble Collagen', 'คอลลาเจนละลายน้ำ', ['humectant', 'filmFormer'], [M, E], 'คอลลาเจนโมเลกุลใหญ่ ให้ความชุ่มชื้นบนผิว', aka=['collagen', 'คอลลาเจน'],
      en='Moisturising collagen', kind='protein'),
    I('Hydrolyzed Elastin', 'อีลาสตินไฮโดรไลซ์', ['humectant', 'filmFormer'], [M], 'โปรตีนอีลาสตินที่ย่อยแล้ว ให้ความชุ่มชื้นและสัมผัสนุ่ม', aka=['elastin'],
      en='Moisturising elastin', kind='protein'),
    I('Sodium DNA', 'โซเดียมดีเอ็นเอ (PDRN)', ['antiAging', 'soothing'], [E, M], 'สารพันธุกรรมสายสั้นที่สกัดจากปลาแซลมอน (PDRN) นิยมในเกาหลี เชื่อว่าช่วยฟื้นฟูผิว',
      aka=['PDRN', 'Salmon DNA', 'Polydeoxyribonucleotide'], en='Salmon PDRN', kind='polymer'),
    I('Snail Secretion Filtrate', 'เมือกหอยทาก', ['humectant', 'soothing', 'antiAging'], [E, M],
      'เมือกหอยทากที่กรองแล้ว มีกรดไกลโคลิก ไฮยาลูโรนิก อัลลันโทอิน และเปปไทด์ตามธรรมชาติ', good='ให้ความชุ่มชื้น ช่วยฟื้นฟูผิวและรอยสิว',
      aka=['Snail Mucin', 'หอยทาก'], en='Snail mucin: hydrating and repairing', kind='extract'),
    I('Panax Ginseng Root Extract', 'สารสกัดโสม', ['antiAging', 'antioxidant'], [E, M, T], 'สารสกัดรากโสม มีจินเซนโนไซด์ ช่วยต้านอนุมูลอิสระและกระตุ้นผิวให้ดูสดใส',
      aka=['Ginseng', 'โสม'], en='Ginseng extract', kind='extract'),
    I('Royal Jelly Extract', 'สารสกัดนมผึ้ง', ['humectant', 'antiAging'], [M, E], 'สารสกัดนมผึ้งที่มีโปรตีน วิตามิน และกรดไขมันพิเศษ ให้ความชุ่มชื้น',
      aka=['นมผึ้ง'], en='Royal jelly', kind='extract'),
    I('Bee Venom', 'พิษผึ้ง', 'antiAging', [E], 'พิษผึ้งปริมาณน้อย เชื่อว่ากระตุ้นการไหลเวียนและทำให้ผิวดูกระชับ', note='sensitize',
      en='Bee venom; may sensitise', kind='extract'),
    I('Colloidal Gold', 'ทองคำคอลลอยด์', ['antiAging', 'colorant'], [E, M], 'อนุภาคทองคำขนาดเล็ก ใช้ในผลิตภัณฑ์หรูเพื่อความเปล่งประกาย หลักฐานด้านการบำรุงยังจำกัด',
      aka=['Gold', 'ทองคำ'], en='Gold particles (mostly marketing)', kind='mineral', f='Au'),
]
