"""Emollients (esters, hydrocarbons, fatty alcohols), silicones, occlusives, waxes."""
from common import ALL, C, E, I, M, S, T

_ESTER = ('เอสเทอร์ (emollient) ที่ช่วยเติมช่องว่างระหว่างเซลล์ผิว ทำให้ผิวนุ่ม เรียบ ลื่น '
          'และช่วยให้เนื้อครีมเกลี่ยง่าย')
_LIGHT = ' เนื้อบางเบา ซึมเร็ว ไม่มันเยิ้ม'
_RICH = ' เนื้อค่อนข้างหนา ให้ความนุ่มชุ่มชื้นมาก'
_FA_ALC = ('แอลกอฮอล์ไขมัน (fatty alcohol) จากพืช — ไม่ใช่แอลกอฮอล์ที่ทำให้ผิวแห้ง '
           'ช่วยให้ครีมข้น คงตัว และทำให้ผิวนุ่ม')
_FA_TIPS = 'ปลอดภัยสำหรับผิวส่วนใหญ่ ไม่ต้องกังวลแม้เห็นคำว่า alcohol บนฉลาก'
_SIL = ('ซิลิโคน ให้สัมผัสลื่นนุ่มเหมือนแพรไหม ช่วยให้เกลี่ยง่าย ไม่เหนียว '
        'และสร้างชั้นบางๆ ที่ระบายอากาศได้บนผิว')
_SIL_TIPS = 'ไม่อุดตันสำหรับคนส่วนใหญ่ ควรล้างหน้าให้สะอาด (double cleanse) ถ้าใช้หลายชั้น'
_VOL = ' ระเหยได้หลังทา จึงทิ้งความรู้สึกแห้งเบา'
_OCC = 'สารเคลือบกักความชุ่มชื้น (occlusive) สร้างชั้นปกป้องบนผิว ลดการระเหยของน้ำออกจากผิว (TEWL)'
_OCC_GOOD = 'เหมาะกับผิวแห้งมาก ผิวลอก ผิวแพ้ง่ายที่เกราะผิวเสีย และใช้ทาเป็นชั้นสุดท้ายตอนกลางคืน (slugging)'
_WAX = 'ขี้ผึ้ง/แว็กซ์ที่ช่วยให้ผลิตภัณฑ์เป็นเนื้อแท่งหรือบาล์ม และเคลือบปกป้องผิว'
_HC = 'น้ำมันไฮโดรคาร์บอน (ไม่มีออกซิเจนในโมเลกุล) คงตัวสูง ไม่เหม็นหืน'

ROWS = [
    # ---------- Squalane & hydrocarbons ----------
    I('Squalane', 'สควาเลน', 'emollient', [C, S, M, E],
      'น้ำมันที่ได้จากการเติมไฮโดรเจนให้สควาลีน (ไขมันตามธรรมชาติในผิว) ปัจจุบันส่วนใหญ่ได้จากอ้อยหรือมะกอก คงตัว ไม่เหม็นหืน',
      good='ให้ความชุ่มชื้นใกล้เคียงไขมันผิว' + _LIGHT + ' ไม่ค่อยอุดตัน เหมาะกับแทบทุกสภาพผิวรวมถึงผิวมัน',
      tips='หยดผสมกับครีมหรือใช้เป็นขั้นตอนสุดท้ายเพื่อเพิ่มความชุ่มชื้น', en='Skin-identical light oil',
      smi='CC(C)CCCC(C)CCCC(C)CCCCC(C)CCCC(C)CCCC(C)C', f='C30H62'),
    I('Squalene', 'สควาลีน', ['emollient', 'antioxidant'], [M, E],
      'ไขมันที่ผิวสร้างเองตามธรรมชาติ (ราว 12% ของซีบัม) แต่ไม่คงตัว เสื่อมง่ายเมื่อโดนแสง/อากาศ จึงนิยมใช้สควาเลนมากกว่า',
      tips='สควาลีนที่ถูกออกซิไดซ์อาจกระตุ้นการเกิดสิวได้', en='Natural but unstable skin lipid',
      smi='CC(C)=CCCC(C)=CCCC(C)=CCCC=C(C)CCC=C(C)CCC=C(C)C', f='C30H50'),
    I('Hemisqualane', 'เฮมิสควาเลน', 'emollient', [M, E, S], _HC + ' เป็นสควาเลนครึ่งโมเลกุล เบาและระเหยได้เล็กน้อย ใช้แทนซิลิโคน',
      en='Light plant-based silicone alternative', smi='CC(C)CCCC(C)CCCC(C)CC', f='C15H32'),
    I('Undecane', 'อันเดเคน', ['emollient', 'solvent'], [M, S], _HC + _VOL + ' มักใช้คู่กับไตรเดเคนแทนซิลิโคนระเหย',
      en='Volatile plant-based hydrocarbon', smi='CCCCCCCCCCC', f='C11H24'),
    I('Tridecane', 'ไตรเดเคน', ['emollient', 'solvent'], [M, S], _HC + _VOL, en='Volatile plant-based hydrocarbon',
      smi='CCCCCCCCCCCCC', f='C13H28'),
    I('Coconut Alkanes', 'โคโคนัทอัลเคน', 'emollient', [M, S], _HC + ' จากมะพร้าว ใช้แทนซิลิโคนระเหย', en='Coconut-derived alkanes',
      kind='mixture'),
    I('C13-15 Alkane', 'ซี13-15 อัลเคน', 'emollient', [M, S, E], _HC + ' จากพืช เนื้อบางเบา ใช้แทนซิลิโคน', en='Plant-based light alkanes',
      kind='mixture'),
    I('Hydrogenated Polyisobutene', 'โพลีไอโซบิวทีนไฮโดรจีเนต', 'emollient', [C, M], _HC + ' ให้ความลื่นคล้ายสควาเลน มักใช้แทนน้ำมันแร่',
      en='Synthetic squalane-like emollient', kind='polymer'),
    I('Hydrogenated Polydecene', 'โพลีดีซีนไฮโดรจีเนต', 'emollient', [M], _HC + ' เนื้อลื่น ไม่มัน', en='Synthetic hydrocarbon emollient',
      kind='polymer'),
    I('Polybutene', 'โพลีบิวทีน', ['emollient', 'filmFormer'], [M], 'พอลิเมอร์ไฮโดรคาร์บอนเหนียวหนืด ช่วยให้เกาะติดและเงา', en='Sticky film-forming hydrocarbon',
      kind='polymer'),
    # ---------- Esters ----------
    I('Caprylic/Capric Triglyceride', 'แคพริลิก/แคพริกไตรกลีเซอไรด์', 'emollient', [C, S, M, E],
      'น้ำมันที่ได้จากกรดไขมันสายกลางของมะพร้าวรวมกับกลีเซอรีน (MCT) คงตัวสูง',
      good='ให้ความนุ่ม' + _LIGHT + ' ช่วยละลายสารสำคัญที่ละลายในน้ำมัน', aka=['MCT', 'Fractionated Coconut Oil'],
      en='Light, stable coconut-derived oil', kind='mixture'),
    I('Isopropyl Myristate', 'ไอโซโพรพิลไมริสเตต', 'emollient', [C, M], _ESTER + _LIGHT + ' ช่วยให้สารอื่นซึมผ่านผิวได้ดีขึ้น',
      aka=['IPM'], note='comedo', en='Light ester; can be comedogenic',
      smi='CCCCCCCCCCCCCC(=O)OC(C)C', f='C17H34O2'),
    I('Isopropyl Palmitate', 'ไอโซโพรพิลปาล์มิเตต', 'emollient', [C, M], _ESTER + _LIGHT, aka=['IPP'], note='comedo',
      en='Light ester; can be comedogenic', smi='CCCCCCCCCCCCCCCC(=O)OC(C)C', f='C19H38O2'),
    I('Ethylhexyl Palmitate', 'เอทิลเฮกซิลปาล์มิเตต', 'emollient', [C, M, S], _ESTER + ' ให้สัมผัสคล้ายซิลิโคน ใช้ละลายเม็ดสีในเมคอัพ',
      aka=['Octyl Palmitate'], en='Dry-feel ester', smi='CCCCCCCCCCCCCCCC(=O)OCC(CC)CCCC', f='C24H48O2'),
    I('Ethylhexyl Stearate', 'เอทิลเฮกซิลสเตียเรต', 'emollient', [M, C], _ESTER + _LIGHT, en='Light ester',
      smi='CCCCCCCCCCCCCCCCCC(=O)OCC(CC)CCCC', f='C26H52O2'),
    I('Ethylhexyl Isononanoate', 'เอทิลเฮกซิลไอโซโนนาโนเอต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light ester',
      smi='CCCCC(CC)COC(=O)CC(C)CC(C)(C)C', f='C17H34O2'),
    I('Isononyl Isononanoate', 'ไอโซโนนิลไอโซโนนาโนเอต', 'emollient', [S, M], _ESTER + ' สัมผัสแห้งนุ่ม เหมือนผง',
      en='Dry-touch ester', smi='CC(CC(C)(C)C)CCOC(=O)CC(C)CC(C)(C)C', f='C18H36O2'),
    I('Triethylhexanoin', 'ไตรเอทิลเฮกซาโนอิน', 'emollient', [C, S, M], _ESTER + ' ไม่มัน ละลายเมคอัพได้ดี จึงพบในคลีนซิ่งด้วย',
      en='Non-greasy ester; dissolves makeup',
      smi='CCCCC(CC)C(=O)OCC(COC(=O)C(CC)CCCC)OC(=O)C(CC)CCCC', f='C27H50O6'),
    I('Coco-Caprylate/Caprate', 'โคโคแคพริเลต/แคพเรต', 'emollient', [S, M, C], _ESTER + ' จากมะพร้าว' + _LIGHT + ' มักใช้แทนซิลิโคน',
      en='Coconut ester; silicone alternative', kind='mixture'),
    I('Coco-Caprylate', 'โคโคแคพริเลต', 'emollient', [S, M], _ESTER + ' จากมะพร้าว' + _LIGHT, en='Light coconut ester', kind='mixture'),
    I('Caprylyl Caprylate/Caprate', 'แคพริลิลแคพริเลต/แคพเรต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light ester', kind='mixture'),
    I('Cetearyl Ethylhexanoate', 'ซีทีอาริลเอทิลเฮกซาโนเอต', 'emollient', [M, S, C], _ESTER + ' ไม่มัน กระจายตัวดี', en='Non-oily ester',
      kind='mixture'),
    I('Cetearyl Isononanoate', 'ซีทีอาริลไอโซโนนาโนเอต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light ester', kind='mixture'),
    I('Cetyl Palmitate', 'ซีทิลปาล์มิเตต', ['emollient', 'thickener'], [M], 'เอสเทอร์แว็กซ์ที่ช่วยให้ครีมข้น นุ่ม และคงตัว',
      en='Wax ester thickener', smi='CCCCCCCCCCCCCCCC(=O)OCCCCCCCCCCCCCCCC', f='C32H64O2'),
    I('Myristyl Myristate', 'ไมริสทิลไมริสเตต', ['emollient', 'thickener'], [M], 'เอสเทอร์แว็กซ์ที่ละลายที่อุณหภูมิผิว ให้สัมผัสนุ่มเหมือนแป้ง',
      note='comedo', en='Melting wax ester', smi='CCCCCCCCCCCCCC(=O)OCCCCCCCCCCCCCC', f='C28H56O2'),
    I('Isostearyl Isostearate', 'ไอโซสเตียริลไอโซสเตียเรต', 'emollient', [M], _ESTER + _RICH, en='Rich ester', kind='mixture'),
    I('Isopropyl Isostearate', 'ไอโซโพรพิลไอโซสเตียเรต', 'emollient', [M], _ESTER + _LIGHT, note='comedo', en='Light ester',
      kind='mixture'),
    I('Diisostearyl Malate', 'ไดไอโซสเตียริลมาเลต', 'emollient', [M], _ESTER + ' หนืดเงา นิยมในลิปสติกและบาล์ม', en='Glossy rich ester',
      kind='mixture'),
    I('Neopentyl Glycol Diheptanoate', 'นีโอเพนทิลไกลคอลไดเฮปทาโนเอต', 'emollient', [M, S, E], _ESTER + _LIGHT + ' ใช้แทนซิลิโคนได้',
      en='Silicone-like light ester', smi='CCCCCCC(=O)OCC(C)(C)COC(=O)CCCCCC', f='C19H36O4'),
    I('Propanediol Dicaprylate', 'โพรเพนไดออลไดแคพริเลต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light plant-based ester',
      smi='CCCCCCCC(=O)OCCCOC(=O)CCCCCCC', f='C19H36O4'),
    I('Diisopropyl Adipate', 'ไดไอโซโพรพิลอะดิเพต', ['emollient', 'solvent'], [S, M], _ESTER + ' เบามาก ใช้ละลายสารกันแดด',
      en='Very light ester solvent', smi='CC(C)OC(=O)CCCCC(=O)OC(C)C', f='C12H22O4'),
    I('Isoamyl Laurate', 'ไอโซเอมิลลอเรต', 'emollient', [M, S], _ESTER + ' จากพืช' + _LIGHT + ' ใช้แทนซิลิโคน', en='Plant-based silicone alternative',
      smi='CCCCCCCCCCCC(=O)OCCC(C)C', f='C17H34O2'),
    I('Heptyl Undecylenate', 'เฮปทิลอันเดซิลีเนต', 'emollient', [M, S], _ESTER + ' จากน้ำมันละหุ่ง' + _LIGHT, en='Light castor-derived ester',
      smi='C=CCCCCCCCCC(=O)OCCCCCCC', f='C18H34O2'),
    I('Decyl Oleate', 'เดซิลโอลีเอต', 'emollient', [M], _ESTER, en='Emollient ester',
      smi='CCCCCCCCC=CCCCCCCCC(=O)OCCCCCCCCCC', f='C28H54O2'),
    I('Lauryl Lactate', 'ลอริลแลคเตต', 'emollient', [M, C], _ESTER + _LIGHT, en='Light lactate ester',
      smi='CCCCCCCCCCCCOC(=O)C(C)O', f='C15H30O3'),
    I('Myristyl Lactate', 'ไมริสทิลแลคเตต', 'emollient', [M], _ESTER, note='comedo', en='Emollient lactate ester',
      smi='CCCCCCCCCCCCCCOC(=O)C(C)O', f='C17H34O3'),
    I('Pentaerythrityl Tetraisostearate', 'เพนตะอีริทริทิลเตตระไอโซสเตียเรต', 'emollient', [M], _ESTER + _RICH + ' เงา ติดทน',
      en='Rich glossy ester', kind='mixture'),
    I('Bis-Diglyceryl Polyacyladipate-2', 'บิสไดกลีเซอริลโพลีอะซิลอะดิเพต-2', ['emollient', 'occlusive'], [M],
      'สารคล้ายลาโนลินแต่ไม่ได้มาจากสัตว์ เนื้อหนืดนุ่ม ให้ความชุ่มชื้นสูง', en='Vegan lanolin alternative', kind='mixture'),
    I('Phytosteryl/Octyldodecyl Lauroyl Glutamate', 'ไฟโตสเตียริล/ออกทิลโดเดซิลลอรอยล์กลูตาเมต', ['emollient', 'barrier'], [M],
      'สารให้ความชุ่มชื้นที่เลียนแบบไขมันระหว่างเซลล์ผิว ช่วยเสริมเกราะผิว', en='Barrier-mimicking emollient', kind='mixture'),
    I('Octyldodecanol', 'ออกทิลโดเดคานอล', ['emollient', 'solvent'], [M, S], 'แอลกอฮอล์ไขมันเหลว ให้ความนุ่ม ใช้ละลายสารอื่น',
      en='Liquid fatty alcohol emollient', smi='OCC(CCCCCCCC)CCCCCCCCCC', f='C20H42O'),
    I('Oleyl Alcohol', 'โอเลอิลแอลกอฮอล์', 'emollient', [M], _FA_ALC + ' เป็นของเหลว', en='Liquid fatty alcohol',
      smi='CCCCCCCCC=CCCCCCCCCO', f='C18H36O'),
    # ---------- Fatty alcohols ----------
    I('Cetyl Alcohol', 'ซีทิลแอลกอฮอล์', ['emollient', 'thickener', 'emulsifier'], [C, S, M], _FA_ALC, tips=_FA_TIPS,
      aka=['fatty alcohol', 'Hexadecanol'], en='Fatty alcohol thickener (not drying)',
      smi='CCCCCCCCCCCCCCCCO', f='C16H34O'),
    I('Cetearyl Alcohol', 'ซีทีอาริลแอลกอฮอล์', ['emollient', 'thickener', 'emulsifier'], [C, S, M],
      _FA_ALC + ' เป็นส่วนผสมของซีทิลกับสเตียริลแอลกอฮอล์', tips=_FA_TIPS, aka=['fatty alcohol', 'Cetostearyl Alcohol'],
      en='Fatty alcohol thickener (not drying)', kind='mixture'),
    I('Stearyl Alcohol', 'สเตียริลแอลกอฮอล์', ['emollient', 'thickener'], [C, M], _FA_ALC, tips=_FA_TIPS,
      aka=['fatty alcohol'], en='Fatty alcohol thickener', smi='CCCCCCCCCCCCCCCCCCO', f='C18H38O'),
    I('Behenyl Alcohol', 'บีเฮนิลแอลกอฮอล์', ['emollient', 'thickener'], [S, M], _FA_ALC, tips=_FA_TIPS,
      aka=['fatty alcohol'], en='Fatty alcohol thickener', smi='CCCCCCCCCCCCCCCCCCCCCCO', f='C22H46O'),
    I('Myristyl Alcohol', 'ไมริสทิลแอลกอฮอล์', ['emollient', 'thickener'], [M, C], _FA_ALC, tips=_FA_TIPS,
      aka=['fatty alcohol'], en='Fatty alcohol', smi='CCCCCCCCCCCCCCO', f='C14H30O'),
    I('Arachidyl Alcohol', 'อะราคิดิลแอลกอฮอล์', ['emollient', 'thickener'], [M], _FA_ALC, tips=_FA_TIPS,
      aka=['fatty alcohol'], en='Fatty alcohol', smi='CCCCCCCCCCCCCCCCCCCCO', f='C20H42O'),
    # ---------- Silicones ----------
    I('Dimethicone', 'ไดเมทิโคน', ['occlusive', 'emollient'], [C, S, M, E], _SIL + ' เป็นซิลิโคนที่ใช้มากที่สุด',
      good='ลดการระเหยของน้ำจากผิว เติมร่องรูขุมขนให้ดูเรียบ เป็นสารปกป้องผิว (skin protectant) ที่ อย. สหรัฐฯ รับรอง',
      tips=_SIL_TIPS, aka=['silicone', 'ซิลิโคน', 'Polydimethylsiloxane', 'PDMS'], en='Most common silicone; smoothing and protective',
      kind='polymer'),
    I('Dimethiconol', 'ไดเมทิโคนอล', ['emollient', 'filmFormer'], [M, S], _SIL, tips=_SIL_TIPS, aka=['silicone', 'ซิลิโคน'],
      en='Silicone film former', kind='polymer'),
    I('Amodimethicone', 'อะโมไดเมทิโคน', 'filmFormer', [C], 'ซิลิโคนประจุบวกที่เกาะผม/ผิวได้ดี พบในครีมนวดและบางคลีนเซอร์',
      aka=['silicone', 'ซิลิโคน'], en='Conditioning silicone', kind='polymer'),
    I('Cyclopentasiloxane', 'ไซโคลเพนตะไซลอกเซน', ['emollient', 'solvent'], [S, M], _SIL + _VOL,
      tips='EU จำกัดการใช้ในผลิตภัณฑ์ที่ล้างออกเพราะประเด็นสิ่งแวดล้อม', aka=['silicone', 'ซิลิโคน', 'D5', 'Cyclomethicone'],
      en='Volatile silicone (D5)', smi='C[Si]1(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O1', f='C10H30O5Si5'),
    I('Cyclohexasiloxane', 'ไซโคลเฮกซะไซลอกเซน', ['emollient', 'solvent'], [S, M], _SIL + _VOL,
      aka=['silicone', 'ซิลิโคน', 'D6'], en='Volatile silicone (D6)',
      smi='C[Si]1(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O[Si](C)(C)O1', f='C12H36O6Si6'),
    I('Disiloxane', 'ไดไซลอกเซน', ['emollient', 'solvent'], [S], _SIL + ' ระเหยเร็วมาก', aka=['silicone', 'ซิลิโคน'],
      en='Very volatile silicone', smi='C[Si](C)(C)O[Si](C)(C)C', f='C6H18OSi2'),
    I('Trisiloxane', 'ไตรไซลอกเซน', ['emollient', 'solvent'], [S, M], _SIL + _VOL, aka=['silicone', 'ซิลิโคน'],
      en='Volatile silicone', smi='C[Si](C)(C)O[Si](C)(C)O[Si](C)(C)C', f='C8H24O2Si3'),
    I('Phenyl Trimethicone', 'ฟีนิลไตรเมทิโคน', 'emollient', [M, S], _SIL + ' ให้ความเงางาม', aka=['silicone', 'ซิลิโคน'],
      en='Glossy silicone', smi='C[Si](C)(C)O[Si](O[Si](C)(C)C)(O[Si](C)(C)C)c1ccccc1', f='C15H32O3Si4'),
    I('Cetyl Dimethicone', 'ซีทิลไดเมทิโคน', 'emollient', [M, S], _SIL, aka=['silicone', 'ซิลิโคน'], en='Alkyl silicone',
      kind='polymer'),
    I('Dimethicone Crosspolymer', 'ไดเมทิโคนครอสพอลิเมอร์', ['thickener', 'absorbent'], [S, M, E],
      'ซิลิโคนที่เชื่อมเป็นตาข่ายคล้ายเจล ให้สัมผัสนุ่มเหมือนกำมะหยี่ เบลอรูขุมขน (พบในไพรเมอร์)', aka=['silicone', 'ซิลิโคน'],
      en='Silicone elastomer gel', kind='polymer'),
    I('Dimethicone/Vinyl Dimethicone Crosspolymer', 'ไดเมทิโคน/ไวนิลไดเมทิโคนครอสพอลิเมอร์', ['thickener', 'absorbent'], [S, M],
      'ผงซิลิโคนยืดหยุ่น ให้สัมผัสนุ่มแห้ง ลดความมันวาว', aka=['silicone'], en='Silicone elastomer powder', kind='polymer'),
    I('Vinyl Dimethicone/Methicone Silsesquioxane Crosspolymer', 'ไวนิลไดเมทิโคน/เมทิโคนซิลเซสควิออกเซนครอสพอลิเมอร์', 'absorbent',
      [S, M], 'ผงซิลิโคนทรงกลมนุ่ม ช่วยเบลอรูขุมขนและให้สัมผัสแห้ง', aka=['silicone'], en='Soft-focus silicone powder',
      kind='polymer'),
    # ---------- Occlusives & waxes ----------
    I('Petrolatum', 'ปิโตรลาทัม', 'occlusive', [M], 'ไขมันจากปิโตรเลียมที่ผ่านการกลั่นบริสุทธิ์สำหรับเครื่องสำอาง เป็นสารเคลือบผิวที่มีประสิทธิภาพสูงที่สุด ลดการเสียน้ำได้กว่า 98%',
      good=_OCC_GOOD + ' ช่วยให้แผลถลอกและริมฝีปากแห้งแตกหายเร็วขึ้น', tips='เกรดเครื่องสำอางปลอดภัย แทบไม่ก่อการแพ้ แต่เนื้อหนักอาจไม่ชอบสำหรับผิวมัน',
      aka=['vaseline', 'วาสลีน', 'Petroleum Jelly'], en='Most effective occlusive', kind='mixture'),
    I('Paraffinum Liquidum', 'น้ำมันแร่', ['occlusive', 'emollient'], [C, M], 'น้ำมันแร่ที่กลั่นบริสุทธิ์ ' + _OCC + ' และละลายเมคอัพได้ดี',
      good='อ่อนโยน ไม่ก่อการแพ้ คงตัว ราคาถูก', aka=['Mineral Oil', 'มิเนอรัลออยล์', 'Paraffin Oil'],
      en='Gentle, non-allergenic occlusive oil', kind='mixture'),
    I('Paraffin', 'พาราฟิน', ['occlusive', 'thickener'], [M], 'ขี้ผึ้งพาราฟินแข็ง ' + _WAX, en='Paraffin wax', kind='mixture'),
    I('Microcrystalline Wax', 'ไมโครคริสตัลลีนแว็กซ์', ['occlusive', 'thickener'], [M], _WAX + ' จากปิโตรเลียม ยืดหยุ่น', en='Flexible petroleum wax',
      kind='mixture'),
    I('Ceresin', 'เซเรซิน', ['occlusive', 'thickener'], [M], _WAX + ' จากแร่', en='Mineral wax', kind='mixture'),
    I('Ozokerite', 'โอโซเคอไรต์', ['occlusive', 'thickener'], [M], _WAX + ' จากแร่ธรรมชาติ', en='Mineral wax', kind='mixture'),
    I('Lanolin', 'ลาโนลิน', ['occlusive', 'emollient'], [M], 'ไขขนแกะ เป็นไขมันธรรมชาติที่คล้ายไขมันผิวมนุษย์ เคลือบปกป้องและให้ความชุ่มชื้นสูง',
      good=_OCC_GOOD + ' นิยมในลิปบาล์มและครีมทาหัวนม', tips='บางคนแพ้ลาโนลิน ถ้าแพ้ขนสัตว์ควรทดสอบก่อน',
      aka=['Wool Wax', 'Adeps Lanae'], en='Sheep wool wax; rich occlusive', kind='mixture'),
    I('Lanolin Alcohol', 'ลาโนลินแอลกอฮอล์', ['emollient', 'emulsifier'], [M], 'ส่วนแอลกอฮอล์ของลาโนลิน ช่วยให้ครีมคงตัวและให้ความชุ่มชื้น',
      note='sensitize', en='Lanolin fraction; emulsifier', kind='mixture'),
    I('Cera Alba', 'ขี้ผึ้ง', ['occlusive', 'thickener'], [M], 'ขี้ผึ้งจากรังผึ้ง ' + _WAX, aka=['Beeswax', 'ขี้ผึ้งแท้'],
      en='Beeswax', kind='mixture'),
    I('Synthetic Beeswax', 'ขี้ผึ้งสังเคราะห์', ['occlusive', 'thickener'], [M], _WAX + ' เลียนแบบขี้ผึ้งแท้', en='Synthetic beeswax', kind='mixture'),
    I('Euphorbia Cerifera Cera', 'แว็กซ์แคนเดลิลลา', ['occlusive', 'thickener'], [M], _WAX + ' จากพืช ใช้แทนขี้ผึ้งในสูตรวีแกน',
      aka=['Candelilla Wax'], en='Vegan candelilla wax', kind='mixture'),
    I('Copernicia Cerifera Cera', 'แว็กซ์คาร์นอบา', ['occlusive', 'thickener'], [M], _WAX + ' จากใบปาล์มบราซิล แข็งและเงา', aka=['Carnauba Wax'],
      en='Hard, glossy carnauba wax', kind='mixture'),
    I('Oryza Sativa Bran Wax', 'แว็กซ์รำข้าว', ['occlusive', 'thickener'], [M], _WAX + ' จากรำข้าว', aka=['Rice Bran Wax'],
      en='Rice bran wax', kind='mixture'),
    I('Hydrogenated Castor Oil', 'น้ำมันละหุ่งไฮโดรจีเนต', ['thickener', 'occlusive'], [M], 'น้ำมันละหุ่งที่เติมไฮโดรเจนจนเป็นแว็กซ์แข็ง ช่วยให้บาล์มและแท่งคงรูป',
      aka=['Castor Wax'], en='Castor wax', kind='oil'),
]
