"""Antioxidants and vitamins."""
from common import C, E, I, M, S, T

_AOX = 'สารต้านอนุมูลอิสระ ช่วยปกป้องผิวจากความเสียหายของแสงแดด มลภาวะ และควันบุหรี่ ซึ่งเป็นสาเหตุของริ้วรอยและจุดด่างดำ'
_AOX_TIPS = 'เหมาะใช้ตอนเช้าใต้กันแดดเพื่อเสริมการปกป้อง'
_VITC = ('วิตามินซีช่วยต้านอนุมูลอิสระ กระตุ้นการสร้างคอลลาเจน และลดการสร้างเม็ดสี '
         'ทำให้ผิวกระจ่างใส จุดด่างดำจาง และริ้วรอยลดลง')
_VITC_DERIV = ' เป็นอนุพันธ์วิตามินซีที่คงตัวกว่าและอ่อนโยนกว่ารูปแบบบริสุทธิ์ ผิวจะค่อยๆ เปลี่ยนเป็นวิตามินซี แต่ฤทธิ์อ่อนกว่า'
_PLANT = 'โพลีฟีนอลจากพืช'

ROWS = [
    I('Ascorbic Acid', 'วิตามินซี (แอสคอร์บิก)', ['antioxidant', 'brightening', 'antiAging'], [E],
      'วิตามินซีรูปแบบบริสุทธิ์ (L-ascorbic acid) ฤทธิ์แรงที่สุดและมีงานวิจัยมากที่สุด',
      good=_VITC, tips='ได้ผลดีที่ความเข้มข้น 10–20% ที่ pH ต่ำ (ราว 3.5) อาจแสบในผิวแพ้ง่าย เสื่อมง่ายเมื่อโดนแสง/อากาศ ถ้าสีเปลี่ยนเป็นส้มเข้มควรเลิกใช้ ' + _AOX_TIPS,
      aka=['Vitamin C', 'วิตามินซี', 'L-Ascorbic Acid', 'LAA'], note='stain', en='Pure vitamin C: antioxidant, brightening, collagen',
      smi='O=C1OC(C(O)CO)C(O)=C1O', f='C6H8O6'),
    I('Sodium Ascorbyl Phosphate', 'โซเดียมแอสคอร์บิลฟอสเฟต', ['antioxidant', 'brightening', 'antiAcne'], [E, M, T],
      'อนุพันธ์วิตามินซีที่ละลายน้ำ' + _VITC_DERIV + ' มีงานวิจัยว่าช่วยลดสิวด้วย', good=_VITC, aka=['Vitamin C', 'วิตามินซี', 'SAP'],
      en='Stable vitamin C derivative; also anti-blemish',
      smi='O=C1OC(C(O)CO)C(OP(=O)([O-])[O-])=C1[O-].[Na+].[Na+].[Na+]', f='C6H6Na3O9P'),
    I('Magnesium Ascorbyl Phosphate', 'แมกนีเซียมแอสคอร์บิลฟอสเฟต', ['antioxidant', 'brightening'], [E, M],
      'อนุพันธ์วิตามินซีที่ละลายน้ำ' + _VITC_DERIV + ' และให้ความชุ่มชื้น', good=_VITC, aka=['Vitamin C', 'วิตามินซี', 'MAP'],
      en='Gentle vitamin C derivative'),
    I('Ascorbyl Glucoside', 'แอสคอร์บิลกลูโคไซด์', ['brightening', 'antioxidant'], [E, M, T],
      'วิตามินซีที่จับกับน้ำตาลกลูโคส' + _VITC_DERIV, good=_VITC, aka=['Vitamin C', 'วิตามินซี', 'AA2G'],
      en='Stable vitamin C glucoside', smi='OCC1OC(OC2=C(O)C(=O)OC2C(O)CO)C(O)C(O)C1O', f='C12H18O11'),
    I('3-O-Ethyl Ascorbic Acid', 'เอทิลแอสคอร์บิกแอซิด', ['brightening', 'antioxidant'], [E, M],
      'อนุพันธ์วิตามินซีที่ละลายได้ทั้งน้ำและน้ำมันบางส่วน คงตัวดี ซึมผ่านผิวได้ดี' , good=_VITC, aka=['Vitamin C', 'วิตามินซี', 'Ethyl Ascorbic Acid'],
      en='Stable, well-absorbed vitamin C ether', smi='O=C1OC(C(O)CO)C(OCC)=C1O', f='C8H12O6'),
    I('Tetrahexyldecyl Ascorbate', 'เตตระเฮกซิลเดซิลแอสคอร์เบต', ['antioxidant', 'brightening'], [E, M],
      'อนุพันธ์วิตามินซีที่ละลายในน้ำมัน คงตัวมาก อ่อนโยน ไม่แสบ', good=_VITC,
      aka=['Vitamin C', 'วิตามินซี', 'THD', 'Ascorbyl Tetraisopalmitate'], en='Oil-soluble gentle vitamin C', kind='mixture'),
    I('Ascorbyl Palmitate', 'แอสคอร์บิลปาล์มิเตต', 'antioxidant', [S, M], 'วิตามินซีที่จับกับกรดปาล์มิติก ละลายในน้ำมัน ส่วนใหญ่ใช้ป้องกันน้ำมันในสูตรไม่ให้เหม็นหืน',
      aka=['Vitamin C', 'วิตามินซี'], en='Oil-soluble vitamin C ester (formula antioxidant)',
      smi='CCCCCCCCCCCCCCCC(=O)OCC(O)C1OC(=O)C(O)=C1O', f='C22H38O7'),
    I('Tocopherol', 'โทโคฟีรอล (วิตามินอี)', 'antioxidant', [C, S, M, E],
      'วิตามินอีรูปแบบธรรมชาติที่ละลายในน้ำมัน ' + _AOX, good='ปกป้องไขมันในผิวและในสูตรไม่ให้ถูกออกซิไดซ์ ช่วยให้วิตามินซีคงตัวและทำงานดีขึ้น',
      tips='ใช้คู่วิตามินซีและกรดเฟรูลิกจะเสริมกัน', aka=['Vitamin E', 'วิตามินอี'], en='Vitamin E antioxidant',
      smi='CC(C)CCCC(C)CCCC(C)CCCC1(C)CCc2c(C)c(O)c(C)c(C)c2O1', f='C29H50O2'),
    I('Tocopheryl Acetate', 'โทโคฟีริลอะซิเตต (วิตามินอี)', 'antioxidant', [S, M], 'วิตามินอีรูปแบบเอสเทอร์ที่คงตัวกว่า ผิวจะเปลี่ยนเป็นวิตามินอีได้บางส่วน',
      aka=['Vitamin E', 'วิตามินอี'], en='Stable vitamin E ester',
      smi='CC(=O)Oc1c(C)c(C)c2OC(C)(CCCC(C)CCCC(C)CCCC(C)C)CCc2c1C', f='C31H52O3'),
    I('Ferulic Acid', 'กรดเฟรูลิก', 'antioxidant', [E], _PLANT + ' จากรำข้าวและธัญพืช ' + _AOX,
      good='ช่วยให้วิตามินซีและอีคงตัว และเพิ่มการปกป้องจากแสงแดดเป็นสองเท่า (สูตร C E Ferulic)', tips=_AOX_TIPS,
      en='Antioxidant that stabilises vitamins C and E', smi='COc1cc(/C=C/C(=O)O)ccc1O', f='C10H10O4'),
    I('Resveratrol', 'เรสเวอราทรอล', ['antioxidant', 'antiAging'], [E, M], _PLANT + ' จากเปลือกองุ่นแดง ' + _AOX,
      tips='เหมาะใช้กลางคืน เพราะไวต่อแสง', en='Grape-skin antioxidant', smi='Oc1ccc(/C=C/c2cc(O)cc(O)c2)cc1', f='C14H12O3'),
    I('Caffeine', 'คาเฟอีน', ['antioxidant', 'soothing'], [E, M], 'สารจากกาแฟและชา ทำให้หลอดเลือดหดตัวชั่วคราว และต้านอนุมูลอิสระ',
      good='ช่วยลดอาการบวมและคล้ำใต้ตาชั่วคราว', tips='นิยมในอายครีม/เซรั่มรอบดวงตา', en='De-puffing antioxidant',
      smi='Cn1cnc2c1c(=O)n(C)c(=O)n2C', f='C8H10N4O2'),
    I('Ubiquinone', 'โคเอนไซม์คิวเท็น', 'antioxidant', [M, E], 'สารต้านอนุมูลอิสระที่ร่างกายสร้างเองและลดลงตามอายุ ช่วยปกป้องเซลล์ผิว',
      aka=['Coenzyme Q10', 'CoQ10', 'Q10'], en='Coenzyme Q10',
      smi='COC1=C(OC)C(=O)C(C/C=C(\\C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)CCC=C(C)C)=C(C)C1=O',
      f='C59H90O4'),
    I('Idebenone', 'ไอเดบีโนน', 'antioxidant', [E], 'อนุพันธ์สังเคราะห์ของโคคิวเท็น โมเลกุลเล็กกว่า ต้านอนุมูลอิสระได้แรง', en='Potent CoQ10 analogue',
      smi='COC1=C(OC)C(=O)C(CCCCCCCCCCO)=C(C)C1=O', f='C19H30O5'),
    I('Astaxanthin', 'แอสตาแซนธิน', 'antioxidant', [E, M], 'แคโรทีนอยด์สีแดงจากสาหร่ายฮีมาโตคอคคัส เป็นสารต้านอนุมูลอิสระที่แรงมาก',
      tips='สีแดงส้มอาจทำให้ผลิตภัณฑ์มีสี', aka=['Haematococcus Pluvialis Extract'], en='Powerful carotenoid antioxidant',
      smi='CC1=C(C(C)(C)CC(O)C1=O)/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C1=C(C)C(=O)C(O)CC1(C)C',
      f='C40H52O4'),
    I('Beta-Carotene', 'เบต้าแคโรทีน', ['antioxidant', 'colorant'], [M], 'แคโรทีนอยด์สีส้มที่เป็นโปรวิตามินเอ ต้านอนุมูลอิสระ', en='Provitamin A carotenoid',
      smi='CC1=C(C(C)(C)CCC1)/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C1=C(C)CCCC1(C)C', f='C40H56'),
    I('Ergothioneine', 'เออร์โกไทโอนีน', 'antioxidant', [E, M], 'สารต้านอนุมูลอิสระจากเห็ด ทำงานในไมโทคอนเดรียของเซลล์', en='Mushroom-derived antioxidant',
      smi='C[N+](C)(C)C(Cc1c[nH]c(=S)[nH]1)C(=O)[O-]', f='C9H15N3O2S'),
    I('Thioctic Acid', 'กรดอัลฟาไลโปอิก', 'antioxidant', [E, M], 'สารต้านอนุมูลอิสระที่ละลายได้ทั้งในน้ำและน้ำมัน', aka=['Alpha Lipoic Acid', 'ALA'],
      en='Alpha-lipoic acid', smi='OC(=O)CCCCC1CCSS1', f='C8H14O2S2'),
    I('Carnosine', 'คาร์โนซีน', ['antioxidant', 'antiAging'], [E, M], 'ไดเปปไทด์ธรรมชาติที่ช่วยยับยั้งกระบวนการไกลเคชัน (น้ำตาลทำลายคอลลาเจน)',
      en='Anti-glycation dipeptide', smi='NCCC(=O)NC(Cc1cnc[nH]1)C(=O)O', f='C9H14N4O3'),
    I('Superoxide Dismutase', 'ซูเปอร์ออกไซด์ดิสมิวเทส', 'antioxidant', [E, M], 'เอนไซม์ต้านอนุมูลอิสระตามธรรมชาติของร่างกาย', aka=['SOD'],
      en='Antioxidant enzyme', kind='protein'),
    I('Epigallocatechin Gallate', 'อีพิแกลโลคาเทชินแกลเลต', ['antioxidant', 'soothing'], [E, M], 'สารสำคัญจากชาเขียว (EGCG) ' + _AOX,
      good='ต้านอนุมูลอิสระ ลดการอักเสบ ควบคุมความมัน', aka=['EGCG', 'ชาเขียว'], en='Green tea EGCG',
      smi='Oc1cc(O)c2c(c1)OC(c1cc(O)c(O)c(O)c1)C(OC(=O)c1cc(O)c(O)c(O)c1)C2', f='C22H18O11'),
    I('Phloretin', 'ฟลอเรติน', 'antioxidant', [E], _PLANT + ' จากเปลือกแอปเปิล ' + _AOX, tips='มักใช้คู่วิตามินซีและกรดเฟรูลิก',
      en='Apple-derived antioxidant', smi='Oc1ccc(CCC(=O)c2c(O)cc(O)cc2O)cc1', f='C15H14O5'),
    I('Quercetin', 'เควอซิทิน', 'antioxidant', [E], _PLANT + ' ' + _AOX, en='Flavonoid antioxidant',
      smi='O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12', f='C15H10O7'),
    I('Rosmarinic Acid', 'กรดโรสมารินิก', ['antioxidant', 'soothing'], [E, M], _PLANT + ' จากโรสแมรี่ ' + _AOX, en='Rosemary antioxidant',
      smi='OC(=O)C(Cc1ccc(O)c(O)c1)OC(=O)/C=C/c1ccc(O)c(O)c1', f='C18H16O8'),
    I('Hydroxytyrosol', 'ไฮดรอกซีไทโรซอล', 'antioxidant', [E, M], _PLANT + ' จากมะกอก ต้านอนุมูลอิสระได้แรง', en='Olive antioxidant',
      smi='OCCc1ccc(O)c(O)c1', f='C8H10O3'),
    I('Biotin', 'ไบโอติน (วิตามินบี 7)', 'other', [M], 'วิตามินบี 7 ที่สำคัญต่อเส้นผมและเล็บ ในเครื่องสำอางช่วยปรับสภาพผิว', aka=['Vitamin B7', 'Vitamin H'],
      en='Vitamin B7', smi='OC(=O)CCCCC1SCC2NC(=O)NC12', f='C10H16N2O3S'),
    I('Pyridoxine', 'ไพริดอกซีน (วิตามินบี 6)', 'other', [M, C], 'วิตามินบี 6 ช่วยปรับสมดุลความมันของผิว', aka=['Vitamin B6'],
      en='Vitamin B6', smi='Cc1ncc(CO)c(CO)c1O', f='C8H11NO3'),
    I('Phytonadione', 'วิตามินเค', ['soothing', 'other'], [E, M], 'วิตามินเค 1 นิยมในครีมใต้ตาเพื่อช่วยรอยคล้ำจากเส้นเลือดและรอยช้ำ',
      aka=['Vitamin K', 'วิตามินเค'], en='Vitamin K for dark circles/bruising',
      smi='CC(C)CCCC(C)CCCC(C)CCCC(C)=CCC1=C(C)C(=O)c2ccccc2C1=O', f='C31H46O2'),
    I('BHT', 'บีเอชที', 'antioxidant', [M, S], 'สารต้านอนุมูลอิสระสังเคราะห์ที่ใช้ปริมาณน้อยเพื่อป้องกันน้ำมันในสูตรไม่ให้เหม็นหืน',
      aka=['Butylated Hydroxytoluene'], en='Formula antioxidant', smi='Cc1cc(C(C)(C)C)c(O)c(C(C)(C)C)c1', f='C15H24O'),
    I('BHA', 'บีเอชเอ (สารกันหืน)', 'antioxidant', [M], 'สารต้านอนุมูลอิสระสังเคราะห์ป้องกันสูตรเหม็นหืน (ไม่ใช่กรด BHA ผลัดเซลล์)',
      aka=['Butylated Hydroxyanisole'], en='Formula antioxidant (not the exfoliant)', smi='COc1ccc(O)c(C(C)(C)C)c1', f='C11H16O2'),
    I('Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate', 'เพนตะอีริทริทิลเตตระไดบิวทิลไฮดรอกซีไฮโดรซินนาเมต', 'antioxidant', [M, S],
      'สารต้านการเหม็นหืนในสูตร โมเลกุลใหญ่ คงตัว', en='Formula antioxidant'),
    I('Camellia Sinensis Leaf Extract', 'สารสกัดชาเขียว', ['antioxidant', 'soothing'], [C, S, M, E, T],
      'สารสกัดจากใบชา มีคาเทชินโดยเฉพาะ EGCG ' + _AOX, good='ต้านอนุมูลอิสระ ลดการอักเสบ และช่วยควบคุมความมัน',
      aka=['Green Tea', 'ชาเขียว'], en='Green tea: antioxidant, soothing', kind='extract'),
    I('Vitis Vinifera Fruit Extract', 'สารสกัดผลองุ่น', 'antioxidant', [E, M, T], 'สารสกัดองุ่นที่มีโพลีฟีนอลและเรสเวอราทรอล', aka=['Grape'],
      en='Grape antioxidant extract', kind='extract'),
    I('Punica Granatum Extract', 'สารสกัดทับทิม', 'antioxidant', [E, M, T], 'สารสกัดทับทิมที่มีกรดเอลลาจิกและโพลีฟีนอล', aka=['Pomegranate', 'ทับทิม'],
      en='Pomegranate antioxidant extract', kind='extract'),
    I('Coffea Arabica Seed Extract', 'สารสกัดเมล็ดกาแฟ', 'antioxidant', [E, M], 'สารสกัดกาแฟที่มีคาเฟอีนและกรดคลอโรจีนิก', aka=['Coffee', 'กาแฟ'],
      en='Coffee extract', kind='extract'),
    I('Theobroma Cacao Extract', 'สารสกัดโกโก้', 'antioxidant', [M], 'สารสกัดโกโก้ที่มีฟลาโวนอยด์', aka=['Cocoa'], en='Cocoa extract', kind='extract'),
    I('Lycium Barbarum Fruit Extract', 'สารสกัดเก๋ากี้', 'antioxidant', [E, M], 'สารสกัดเก๋ากี้ที่มีพอลิแซ็กคาไรด์และแคโรทีนอยด์', aka=['Goji', 'เก๋ากี้'],
      en='Goji extract', kind='extract'),
    I('Vaccinium Myrtillus Fruit Extract', 'สารสกัดบิลเบอร์รี่', ['antioxidant', 'exfoliant'], [E, T], 'สารสกัดบิลเบอร์รี่ที่มีแอนโทไซยานินและกรดผลไม้', aka=['Bilberry'],
      en='Bilberry extract', kind='extract'),
    I('Citrus Limon Fruit Extract', 'สารสกัดผลมะนาว', ['antioxidant', 'exfoliant'], [T, C], 'สารสกัดมะนาวที่มีวิตามินซีและกรดซิตริกเล็กน้อย', aka=['Lemon'],
      en='Lemon extract', kind='extract'),
    I('Rosmarinus Officinalis Leaf Extract', 'สารสกัดใบโรสแมรี่', 'antioxidant', [M, C], 'สารสกัดโรสแมรี่ ใช้ต้านอนุมูลอิสระและป้องกันน้ำมันในสูตรเหม็นหืน',
      aka=['Rosemary', 'โรสแมรี่'], en='Rosemary antioxidant extract', kind='extract'),
]
