"""Skin-identical lipids (ceramides, cholesterol, fatty acids), lecithin, ferments."""
from common import C, E, I, M, S, T

_CER = ('เซราไมด์คือไขมันหลักระหว่างเซลล์ผิว (ราว 50%) ทำหน้าที่เหมือน "ปูน" ยึดเซลล์ผิวที่เป็น "อิฐ" '
        'ให้เกราะผิวแน่นหนา กักน้ำไว้และกันสิ่งระคายเคือง')
_CER_GOOD = 'ฟื้นฟูเกราะผิวที่อ่อนแอ ลดความแห้ง แดง แสบง่าย เหมาะกับผิวแห้ง ผิวแพ้ง่าย และช่วงใช้กรดหรือเรตินอยด์'
_CER_TIPS = 'ได้ผลดีที่สุดเมื่อใช้ร่วมกับคอเลสเตอรอลและกรดไขมันในสัดส่วนใกล้เคียงผิว (ประมาณ 3:1:1)'
_FERMENT = 'ผลิตภัณฑ์จากการหมักจุลินทรีย์ ประกอบด้วยกรดอะมิโน วิตามิน และสารที่จุลินทรีย์สร้างขึ้น'
_POSTBIOTIC = ' (เป็น postbiotic คือเชื้อที่ไม่มีชีวิตแล้วหรือสารที่เชื้อสร้าง) ช่วยเสริมความแข็งแรงของเกราะผิวและสมดุลจุลินทรีย์บนผิว'

ROWS = [
    I('Ceramide NP', 'เซราไมด์ เอ็นพี', 'barrier', [M, E, S], _CER + ' ตัวนี้เป็นเซราไมด์ที่มีมากในผิวและพบบ่อยที่สุดในเครื่องสำอาง',
      good=_CER_GOOD, tips=_CER_TIPS, aka=['ceramide', 'เซราไมด์', 'Ceramide 3'], en='Most common skin-identical ceramide',
      smi='CCCCCCCCCCCCCCCCCC(=O)NC(CO)C(O)C(O)CCCCCCCCCCCCCC', f='C36H73NO4'),
    I('Ceramide AP', 'เซราไมด์ เอพี', 'barrier', [M, E], _CER, good=_CER_GOOD, tips=_CER_TIPS,
      aka=['ceramide', 'เซราไมด์', 'Ceramide 6 II'], en='Skin-identical ceramide',
      smi='CCCCCCCCCCCCCCCCC(O)C(=O)NC(CO)C(O)C(O)CCCCCCCCCCCCCC', f='C36H73NO5'),
    I('Ceramide NS', 'เซราไมด์ เอ็นเอส', 'barrier', [M], _CER, good=_CER_GOOD, tips=_CER_TIPS,
      aka=['ceramide', 'เซราไมด์', 'Ceramide 2'], en='Skin-identical ceramide',
      smi='CCCCCCCCCCCCCCCCCC(=O)NC(CO)C(O)/C=C/CCCCCCCCCCCCC', f='C36H71NO3'),
    I('Ceramide EOP', 'เซราไมด์ อีโอพี', 'barrier', [M, E],
      _CER + ' ตัวนี้มีสายไขมันยาวพิเศษที่เชื่อมชั้นไขมันเข้าด้วยกัน สำคัญมากต่อโครงสร้างเกราะผิว', good=_CER_GOOD,
      tips=_CER_TIPS, aka=['ceramide', 'เซราไมด์', 'Ceramide 1'], en='Long-chain ceramide that links lipid layers',
      kind='mixture'),
    I('Ceramide AS', 'เซราไมด์ เอเอส', 'barrier', [M], _CER, good=_CER_GOOD, aka=['ceramide', 'เซราไมด์', 'Ceramide 5'],
      en='Skin-identical ceramide', kind='mixture'),
    I('Ceramide NG', 'เซราไมด์ เอ็นจี', 'barrier', [M], _CER, good=_CER_GOOD, aka=['ceramide', 'เซราไมด์'],
      en='Skin-identical ceramide', kind='mixture'),
    I('Hydroxypropyl Bispalmitamide MEA', 'ไฮดรอกซีโพรพิลบิสปาล์มิตาไมด์ เอ็มอีเอ', 'barrier', [M],
      'เซราไมด์เทียม (pseudo-ceramide) ที่ออกแบบให้ทำงานคล้ายเซราไมด์ในผิว ราคาถูกกว่าและคงตัว', good=_CER_GOOD,
      aka=['pseudo-ceramide', 'เซราไมด์เทียม'], en='Pseudo-ceramide'),
    I('Cetyl-PG Hydroxyethyl Palmitamide', 'ซีทิล-พีจี ไฮดรอกซีเอทิลปาล์มิตาไมด์', 'barrier', [M],
      'เซราไมด์เทียมที่พัฒนาในญี่ปุ่น ช่วยฟื้นฟูเกราะผิวคล้ายเซราไมด์ธรรมชาติ', good=_CER_GOOD,
      aka=['pseudo-ceramide', 'เซราไมด์เทียม'], en='Pseudo-ceramide'),
    I('Phytosphingosine', 'ไฟโตสฟิงโกซีน', ['barrier', 'antiAcne'], [M, E],
      'สารตั้งต้นของเซราไมด์ที่ผิวใช้สร้างเซราไมด์ มีฤทธิ์ต้านเชื้อแบคทีเรียที่ทำให้เกิดสิวและลดการอักเสบ',
      good='เสริมเกราะผิวและช่วยผิวที่เป็นสิว/แดงง่าย', en='Ceramide precursor; anti-blemish',
      smi='CCCCCCCCCCCCCCC(O)C(O)C(N)CO', f='C18H39NO3'),
    I('Sphingolipids', 'สฟิงโกลิพิด', 'barrier', [M], 'กลุ่มไขมันที่รวมถึงเซราไมด์ ช่วยเสริมเกราะผิว', en='Barrier lipids',
      kind='mixture'),
    I('Cholesterol', 'คอเลสเตอรอล', 'barrier', [M],
      'ไขมันสำคัญอันดับสองในเกราะผิว (ราว 25%) ช่วยให้ชั้นไขมันระหว่างเซลล์ยืดหยุ่น', good='ทำงานร่วมกับเซราไมด์และกรดไขมันเพื่อซ่อมแซมเกราะผิว',
      tips=_CER_TIPS, en='Barrier lipid partner of ceramides',
      smi='CC(C)CCCC(C)C1CCC2C1(C)CCC1C2CC=C2CC(O)CCC12C', f='C27H46O'),
    I('Phytosterols', 'ไฟโตสเตอรอล', ['barrier', 'soothing'], [M], 'สเตอรอลจากพืชที่คล้ายคอเลสเตอรอล ช่วยเสริมเกราะผิวและลดการอักเสบ',
      en='Plant sterols', kind='mixture'),
    I('Beta-Sitosterol', 'เบต้าซิโทสเตอรอล', ['barrier', 'soothing'], [M], 'สเตอรอลหลักจากพืช ช่วยเสริมเกราะผิวและลดการระคายเคือง',
      en='Main plant sterol', smi='CCC(CCC(C)C1CCC2C1(C)CCC1C2CC=C2CC(O)CCC12C)C(C)C', f='C29H50O'),
    I('Linoleic Acid', 'กรดไลโนเลอิก', ['barrier', 'antiAcne'], [M, E],
      'กรดไขมันจำเป็นโอเมก้า 6 ที่ผิวใช้สร้างเซราไมด์ คนที่เป็นสิวมักมีกรดนี้ในซีบัมต่ำ', good='เสริมเกราะผิวและอาจช่วยลดสิวอุดตัน',
      aka=['omega 6', 'โอเมก้า 6', 'Vitamin F'], en='Omega-6 fatty acid for the barrier',
      smi='CCCCC/C=C\\C/C=C\\CCCCCCCC(=O)O', f='C18H32O2'),
    I('Linolenic Acid', 'กรดไลโนเลนิก', 'barrier', [M, E], 'กรดไขมันจำเป็นโอเมก้า 3 ช่วยลดการอักเสบและเสริมเกราะผิว', aka=['omega 3', 'โอเมก้า 3'],
      en='Omega-3 fatty acid', smi='CC/C=C\\C/C=C\\C/C=C\\CCCCCCCC(=O)O', f='C18H30O2'),
    I('Oleic Acid', 'กรดโอเลอิก', 'emollient', [M], 'กรดไขมันโอเมก้า 9 ที่พบมากในน้ำมันมะกอก ช่วยให้สารอื่นซึมผ่านผิวได้ดีขึ้น',
      tips='ปริมาณมากอาจทำให้เกราะผิวอ่อนแอลงในผิวแพ้ง่าย', aka=['omega 9', 'โอเมก้า 9'], en='Omega-9 fatty acid',
      smi='CCCCCCCC/C=C\\CCCCCCCC(=O)O', f='C18H34O2'),
    I('Lecithin', 'เลซิติน', ['emulsifier', 'barrier'], [M, E], 'ฟอสโฟลิพิดจากถั่วเหลืองหรือทานตะวัน เป็นอิมัลซิไฟเออร์ธรรมชาติและให้ความชุ่มชื้น ใช้ทำไลโปโซมห่อหุ้มสารสำคัญ',
      en='Natural phospholipid emulsifier', kind='mixture'),
    I('Hydrogenated Lecithin', 'เลซิตินไฮโดรจีเนต', ['emulsifier', 'barrier'], [M, E, S], 'เลซิตินที่เติมไฮโดรเจนให้คงตัว ใช้สร้างอิมัลชันคล้ายโครงสร้างเกราะผิว (lamellar)',
      en='Stable phospholipid emulsifier', kind='mixture'),
    I('Glycosphingolipids', 'ไกลโคสฟิงโกลิพิด', 'barrier', [M], 'ไขมันที่มีน้ำตาลเกาะ ช่วยเสริมเกราะผิว', en='Barrier lipids', kind='mixture'),
    # ---------- Ferments, pre/probiotics ----------
    I('Bifida Ferment Lysate', 'ไบฟิดาเฟอร์เมนต์ไลเสท', 'barrier', [E, M], _FERMENT + ' จากเชื้อไบฟิโดแบคทีเรีย' + _POSTBIOTIC,
      good='ช่วยให้ผิวทนต่อสิ่งกระตุ้นมากขึ้น ลดความไวของผิว', aka=['Bifida', 'probiotic', 'โพรไบโอติก'], en='Postbiotic for barrier and sensitivity',
      kind='ferment'),
    I('Lactobacillus Ferment', 'แลคโตบาซิลลัสเฟอร์เมนต์', 'barrier', [E, M, C], _FERMENT + ' จากแลคโตบาซิลลัส' + _POSTBIOTIC,
      aka=['probiotic', 'โพรไบโอติก'], en='Lactobacillus postbiotic', kind='ferment'),
    I('Lactobacillus Ferment Lysate', 'แลคโตบาซิลลัสเฟอร์เมนต์ไลเสท', 'barrier', [E, M], _FERMENT + _POSTBIOTIC,
      aka=['probiotic', 'โพรไบโอติก'], en='Lactobacillus lysate', kind='ferment'),
    I('Lactococcus Ferment Lysate', 'แลคโตคอคคัสเฟอร์เมนต์ไลเสท', 'barrier', [E, M], _FERMENT + _POSTBIOTIC,
      aka=['probiotic', 'โพรไบโอติก'], en='Lactococcus lysate', kind='ferment'),
    I('Streptococcus Thermophilus Ferment', 'สเตรปโตคอคคัสเทอร์โมฟิลัสเฟอร์เมนต์', 'barrier', [E, M],
      _FERMENT + ' มีงานวิจัยว่าช่วยเพิ่มเซราไมด์ในผิว', aka=['probiotic'], en='Ferment that may boost ceramides', kind='ferment'),
    I('Saccharomyces Ferment Filtrate', 'แซคคาโรไมซิสเฟอร์เมนต์ฟิลเทรต', ['humectant', 'brightening'], [E, T],
      _FERMENT + ' จากยีสต์ ให้ความชุ่มชื้นและช่วยให้ผิวดูกระจ่างใส', aka=['yeast ferment', 'ยีสต์'], en='Yeast ferment', kind='ferment'),
    I('Aspergillus/Rice Ferment Extract', 'สารสกัดข้าวหมักแอสเปอร์จิลลัส', ['brightening', 'humectant'], [E, T],
      _FERMENT + ' ข้าวหมักแบบเดียวกับการทำสาเก มีกรดอะมิโนและกรดโคจิกตามธรรมชาติ', aka=['Sake', 'สาเก', 'Koji'],
      en='Sake-style rice ferment', kind='ferment'),
    I('Lactobacillus/Soybean Ferment Extract', 'สารสกัดถั่วเหลืองหมักแลคโตบาซิลลัส', ['soothing', 'barrier'], [E, M], _FERMENT,
      aka=['probiotic'], en='Soy ferment', kind='ferment'),
    I('Inulin', 'อินูลิน', ['humectant', 'barrier'], [M, E, C], 'ใยอาหารจากพืช ทำหน้าที่เป็นพรีไบโอติก (อาหารของจุลินทรีย์ดีบนผิว) และให้ความชุ่มชื้น',
      aka=['prebiotic', 'พรีไบโอติก'], en='Prebiotic fibre', kind='polymer'),
    I('Alpha-Glucan Oligosaccharide', 'อัลฟากลูแคนโอลิโกแซคคาไรด์', ['humectant', 'barrier'], [M, E, C],
      'น้ำตาลสายสั้นที่เป็นพรีไบโอติก ช่วยสนับสนุนจุลินทรีย์ดีบนผิว', aka=['prebiotic', 'พรีไบโอติก'], en='Prebiotic sugar',
      kind='polymer'),
]
