"""UV filters and the ingredients that give sunscreens their texture."""
from common import C, E, I, M, S, T

_CHEM = 'สารกันแดดชนิดดูดซับรังสี UV (chemical/organic filter) เปลี่ยนพลังงานแสงเป็นความร้อนเล็กน้อย'
_UVB = ' ดูดซับ UVB เป็นหลัก (ต้นเหตุผิวไหม้แดด)'
_UVA = ' ดูดซับ UVA (ต้นเหตุฝ้า กระ ผิวแก่ก่อนวัย)'
_BROAD = ' ดูดซับได้ทั้ง UVA และ UVB (broad spectrum)'
_MODERN = ' เป็นสารกันแดดรุ่นใหม่ที่คงตัวต่อแสงดี โมเลกุลใหญ่จึงซึมผ่านผิวน้อย ระคายเคืองน้อย'
_TIPS = 'ทาให้ทั่วประมาณ 2 ข้อนิ้ว (ราว 1/4 ช้อนชา) สำหรับใบหน้าและลำคอ และทาซ้ำทุก 2 ชั่วโมงเมื่ออยู่กลางแจ้ง'
_FILM = 'พอลิเมอร์สร้างฟิล์มบางๆ ช่วยให้กันแดดเกาะผิว กันน้ำ/เหงื่อได้นานขึ้น และช่วยให้ค่า SPF สม่ำเสมอ'
_ESTER = 'เอสเทอร์ให้ความลื่น เนื้อบางเบา ช่วยละลายสารกันแดดชนิดผง (คริสตัล) ให้กระจายตัวดี'

ROWS = [
    # ---------- Mineral filters ----------
    I('Zinc Oxide', 'ซิงค์ออกไซด์', ['uvMineral', 'soothing'], [S, M],
      'สารกันแดดชนิดแร่ (mineral/physical filter) อนุภาคสีขาวที่สะท้อน กระจาย และดูดซับรังสี UV',
      good='ป้องกันได้กว้างทั้ง UVB และ UVA รวมถึง UVA ช่วงยาว คงตัวต่อแสง อ่อนโยน เหมาะกับผิวแพ้ง่ายและเด็ก มีฤทธิ์ช่วยลดการระคายเคืองด้วย',
      tips='อาจทิ้งคราบขาว (white cast) สูตรอนุภาคนาโนจะใสกว่า ' + _TIPS,
      aka=['ZnO', 'mineral sunscreen', 'กันแดดแร่', 'CI 77947'], en='Broad-spectrum mineral UV filter',
      kind='mineral', f='ZnO'),
    I('Titanium Dioxide', 'ไทเทเนียมไดออกไซด์', ['uvMineral', 'colorant'], [S, M],
      'สารกันแดดชนิดแร่อนุภาคสีขาว และยังใช้เป็นเม็ดสีขาวในเครื่องสำอาง (CI 77891)',
      good='ป้องกัน UVB และ UVA ช่วงสั้นได้ดี คงตัว อ่อนโยน มักใช้คู่กับซิงค์ออกไซด์',
      tips='ป้องกัน UVA ช่วงยาวได้น้อยกว่าซิงค์ จึงควรมีสารกันแดดตัวอื่นร่วมด้วย',
      aka=['TiO2', 'mineral sunscreen', 'กันแดดแร่', 'CI 77891'], en='Mineral UV filter and white pigment',
      kind='mineral', f='TiO2'),
    # ---------- Classic organic filters ----------
    I('Ethylhexyl Methoxycinnamate', 'ออกทิน็อกเซต', 'uvChemical', [S],
      _CHEM + _UVB + ' เป็นสารกันแดดที่ใช้แพร่หลายที่สุดตัวหนึ่ง',
      good='ป้องกันผิวไหม้แดด เนื้อสัมผัสดี', tips='เสื่อมสลายเมื่อโดนแดดได้บ้าง จึงมักใช้คู่กับสารกันแดดที่คงตัวกว่า',
      aka=['Octinoxate', 'Octyl Methoxycinnamate', 'OMC', 'Uvinul MC 80', 'Parsol MCX'], note='reef',
      en='Widely used UVB filter', smi='CCCCC(CC)COC(=O)/C=C/c1ccc(OC)cc1', f='C18H26O3'),
    I('Benzophenone-3', 'ออกซีเบนโซน', 'uvChemical', [S],
      _CHEM + ' ดูดซับ UVB และ UVA ช่วงสั้น', good='ช่วยขยายการป้องกันไปถึง UVA ช่วงสั้น',
      tips='ซึมผ่านผิวได้ค่อนข้างมาก หลายแบรนด์จึงเลิกใช้ ถ้ากังวลให้เลือกสูตรที่ไม่มี',
      aka=['Oxybenzone', 'BP-3'], note='reef', en='UVB/UVA2 filter, now avoided by many brands',
      smi='COc1ccc(C(=O)c2ccccc2)c(O)c1', f='C14H12O3'),
    I('Benzophenone-4', 'ซัลลิโซเบนโซน', ['uvChemical', 'other'], [S, C],
      _CHEM + ' ละลายน้ำได้ ดูดซับ UVB/UVA ช่วงสั้น มักใช้ปกป้องสีและกลิ่นของผลิตภัณฑ์จากแสง',
      aka=['Sulisobenzone', 'BP-4'], en='Water-soluble UV absorber',
      smi='COc1cc(O)c(C(=O)c2ccccc2)cc1S(=O)(=O)O', f='C14H12O6S'),
    I('Benzophenone-8', 'ไดออกซีเบนโซน', 'uvChemical', [S],
      _CHEM + ' ดูดซับ UVB และ UVA ช่วงสั้น ใช้น้อยในปัจจุบัน', aka=['Dioxybenzone', 'BP-8'],
      en='Older UVB/UVA2 filter', smi='COc1ccc(C(=O)c2ccccc2O)c(O)c1', f='C14H12O4'),
    I('Homosalate', 'โฮโมซาเลต', 'uvChemical', [S], _CHEM + _UVB + ' กลุ่มซาลิไซเลต',
      good='ช่วยละลายสารกันแดดตัวอื่นและเพิ่ม SPF', tips='EU จำกัดความเข้มข้นในหน้าไม่เกิน 7.34%',
      aka=['HMS'], en='UVB filter (salicylate)', smi='CC1CC(CC(C)(C)C1)OC(=O)c1ccccc1O', f='C16H22O3'),
    I('Ethylhexyl Salicylate', 'ออกทิซาเลต', 'uvChemical', [S], _CHEM + _UVB + ' กลุ่มซาลิไซเลต',
      good='คงตัว เนื้อบางเบา ช่วยละลายอโวเบนโซน', aka=['Octisalate', 'Octyl Salicylate'],
      en='UVB filter (salicylate)', smi='CCCCC(CC)COC(=O)c1ccccc1O', f='C15H22O3'),
    I('Octocrylene', 'ออกโทคริลีน', 'uvChemical', [S], _CHEM + _UVB + ' และ UVA ช่วงสั้นเล็กน้อย',
      good='ช่วยให้อโวเบนโซนคงตัวขึ้น (photostabilizer) และกันน้ำได้ดี',
      tips='มีรายงานการแพ้สัมผัส/แพ้แสงในบางคน และอาจเสื่อมเป็นเบนโซฟีโนนเมื่อเก็บนาน',
      aka=['OCR'], en='UVB filter that stabilises avobenzone',
      smi='CCCCC(CC)COC(=O)C(C#N)=C(c1ccccc1)c1ccccc1', f='C24H27NO2'),
    I('Butyl Methoxydibenzoylmethane', 'อโวเบนโซน', 'uvChemical', [S],
      _CHEM + _UVA + ' ครอบคลุม UVA ช่วงยาวได้ดีที่สุดในกลุ่มสารเคมีรุ่นเก่า',
      good='ป้องกันฝ้า กระ และผิวแก่จากแดด',
      tips='เสื่อมเร็วเมื่อโดนแดดถ้าอยู่ลำพัง ต้องมีตัวช่วยคงตัว เช่น ออกโทคริลีน หรือทิโนซอร์บ เอส และไม่ควรคู่กับซิงค์/ไทเทเนียมที่ไม่เคลือบผิว',
      aka=['Avobenzone', 'Parsol 1789'], en='Key UVA filter; needs photostabilisers',
      smi='COc1ccc(C(=O)CC(=O)c2ccc(C(C)(C)C)cc2)cc1', f='C20H22O3'),
    I('Ethylhexyl Dimethyl PABA', 'พาดิเมต โอ', 'uvChemical', [S], _CHEM + _UVB + ' อนุพันธ์ PABA รุ่นเก่า',
      aka=['Padimate O'], note='sensitize', en='Older UVB filter (PABA derivative)',
      smi='CCCCC(CC)COC(=O)c1ccc(N(C)C)cc1', f='C17H27NO2'),
    I('PABA', 'พาบา (กรดพาราอะมิโนเบนโซอิก)', 'uvChemical', [S], _CHEM + _UVB + ' เป็นสารกันแดดยุคแรก ปัจจุบันแทบไม่ใช้แล้ว',
      aka=['4-Aminobenzoic Acid'], note='sensitize', en='Early UVB filter, rarely used today',
      smi='Nc1ccc(C(=O)O)cc1', f='C7H7NO2'),
    I('Menthyl Anthranilate', 'เมราดิเมต', 'uvChemical', [S], _CHEM + ' ดูดซับ UVA ช่วงสั้น',
      aka=['Meradimate'], en='UVA2 filter', smi='CC(C)C1CCC(C)CC1OC(=O)c1ccccc1N', f='C17H25NO2'),
    I('Isoamyl p-Methoxycinnamate', 'อะมิล็อกเซต', 'uvChemical', [S], _CHEM + _UVB,
      aka=['Amiloxate', 'Neo Heliopan E1000'], en='UVB filter (cinnamate)',
      smi='CC(C)CCOC(=O)/C=C/c1ccc(OC)cc1', f='C15H20O3'),
    I('Cinoxate', 'ซินอกเซต', 'uvChemical', [S], _CHEM + _UVB + ' กลุ่มซินนาเมตรุ่นเก่า',
      en='Older UVB filter', smi='CCOCCOC(=O)/C=C/c1ccc(OC)cc1', f='C14H18O4'),
    I('4-Methylbenzylidene Camphor', 'เอนซาคามีน', 'uvChemical', [S], _CHEM + _UVB,
      tips='EU เลิกอนุญาตให้ใช้แล้ว (ตั้งแต่ปี 2025) เพราะข้อกังวลด้านฮอร์โมน',
      aka=['Enzacamene', '4-MBC'], en='UVB filter, no longer allowed in the EU',
      smi='Cc1ccc(/C=C2/C3CCC(C)(C2=O)C3(C)C)cc1', f='C18H22O'),
    I('Phenylbenzimidazole Sulfonic Acid', 'เอนซูลิโซล', 'uvChemical', [S],
      _CHEM + _UVB + ' ละลายน้ำได้ ให้เนื้อบางเบาไม่เหนียว นิยมในกันแดดเนื้อเจล',
      aka=['Ensulizole', 'PBSA'], en='Water-soluble UVB filter for light gels',
      smi='OS(=O)(=O)c1ccc2nc([nH]c2c1)-c1ccccc1', f='C13H10N2O3S'),
    I('Disodium Phenyl Dibenzimidazole Tetrasulfonate', 'บิสดิซูลิโซล ไดโซเดียม', 'uvChemical', [S],
      _CHEM + _UVA + ' ละลายน้ำได้ ใช้คู่กับตัวที่ละลายในน้ำมันเพื่อเพิ่มการป้องกัน UVA',
      aka=['Bisdisulizole Disodium', 'Neo Heliopan AP'], en='Water-soluble UVA filter', kind='mixture'),
    I('Terephthalylidene Dicamphor Sulfonic Acid', 'เอแคมซูล (เม็กโซริล เอสเอ็กซ์)', 'uvChemical', [S],
      _CHEM + _UVA + ' ละลายน้ำได้ คงตัวต่อแสงดี พัฒนาโดยลอรีอัล',
      aka=['Ecamsule', 'Mexoryl SX'], en='Photostable water-soluble UVA filter',
      smi='CC1(C)C2CCC1(CS(=O)(=O)O)C(=O)/C2=C/c1ccc(/C=C2/C3CCC(CS(=O)(=O)O)(C2=O)C3(C)C)cc1',
      f='C28H34O8S2'),
    I('Drometrizole Trisiloxane', 'เม็กโซริล เอ็กซ์แอล', 'uvChemical', [S],
      _CHEM + _BROAD + ' ละลายในน้ำมัน คงตัวต่อแสง มักใช้คู่กับเม็กโซริล เอสเอ็กซ์',
      aka=['Mexoryl XL'], en='Photostable broad-spectrum filter',
      smi='Cc1cc(CC(C)C[Si](C)(O[Si](C)(C)C)O[Si](C)(C)C)c(O)c(c1)-n1nc2ccccc2n1',
      f='C24H39N3O3Si3'),
    I('Methoxypropylamino Cyclohexenylidene Ethoxyethylcyanoacetate', 'เม็กโซริล 400', 'uvChemical', [S],
      _CHEM + ' ออกแบบมาเพื่อดูดซับ UVA ช่วงยาวพิเศษ (ultra-long UVA 380–400 nm)' + _MODERN,
      aka=['Mexoryl 400', 'MCE'], en='Ultra-long UVA filter',
      smi='COCCCNC1=CC(=C(C#N)C(=O)OCCOCC)CCC1'),
    # ---------- Modern broad-spectrum filters ----------
    I('Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', 'บีโมทริซินอล (ทิโนซอร์บ เอส)', 'uvChemical', [S],
      _CHEM + _BROAD + _MODERN,
      good='ป้องกันได้กว้างและช่วยให้อโวเบนโซนคงตัว เป็นหนึ่งในสารกันแดดที่ดีที่สุดในปัจจุบัน',
      tips='พบมากในกันแดดยุโรป/เอเชีย ยังไม่ได้รับอนุญาตในสหรัฐฯ', aka=['Bemotrizinol', 'Tinosorb S', 'BEMT'],
      en='Excellent photostable broad-spectrum filter',
      smi='CCCCC(CC)COc1ccc(c(O)c1)-c1nc(nc(n1)-c1ccc(OCC(CC)CCCC)cc1O)-c1ccc(OC)cc1',
      f='C38H49N3O5'),
    I('Methylene Bis-Benzotriazolyl Tetramethylbutylphenol', 'บิสออกทริโซล (ทิโนซอร์บ เอ็ม)', ['uvChemical', 'uvMineral'],
      [S], 'สารกันแดดอนุภาคอินทรีย์ขนาดเล็กที่ทั้งดูดซับและกระจายแสง' + _BROAD + _MODERN,
      aka=['Bisoctrizole', 'Tinosorb M', 'MBBT'], en='Hybrid particulate broad-spectrum filter',
      smi='CC(C)(C)CC(C)(C)c1cc(Cc2cc(cc(c2O)-n2nc3ccccc3n2)C(C)(C)CC(C)(C)C)c(O)c(c1)-n1nc2ccccc2n1',
      f='C41H50N6O2'),
    I('Ethylhexyl Triazone', 'เอทิลเฮกซิลไตรอะโซน', 'uvChemical', [S],
      _CHEM + _UVB + ' ประสิทธิภาพสูงมาก ใช้ปริมาณน้อยก็ได้ SPF สูง' + _MODERN,
      aka=['Uvinul T 150', 'Octyl Triazone'], en='Highly efficient UVB filter',
      smi='CCCCC(CC)COC(=O)c1ccc(Nc2nc(Nc3ccc(cc3)C(=O)OCC(CC)CCCC)nc(Nc3ccc(cc3)C(=O)OCC(CC)CCCC)n2)cc1',
      f='C48H66N6O6'),
    I('Diethylamino Hydroxybenzoyl Hexyl Benzoate', 'ยูวินูล เอ พลัส', 'uvChemical', [S],
      _CHEM + _UVA + ' คงตัวต่อแสงดี มักใช้แทนอโวเบนโซน', aka=['Uvinul A Plus', 'DHHB'],
      en='Photostable UVA filter',
      smi='CCCCCCOC(=O)c1ccccc1C(=O)c1ccc(N(CC)CC)cc1O', f='C24H31NO4'),
    I('Diethylhexyl Butamido Triazone', 'ไอสโคทริซินอล', 'uvChemical', [S], _CHEM + _UVB + _MODERN,
      aka=['Iscotrizinol', 'Uvasorb HEB'], en='Photostable UVB filter',
      smi='CC(C)(C)NC(=O)c1ccc(Nc2nc(Nc3ccc(cc3)C(=O)OCC(CC)CCCC)nc(Nc3ccc(cc3)C(=O)OCC(CC)CCCC)n2)cc1',
      f='C44H59N7O5'),
    I('Tris-Biphenyl Triazine', 'ทิโนซอร์บ เอ2บี', ['uvChemical', 'uvMineral'], [S],
      'สารกันแดดอนุภาคอินทรีย์ที่ดูดซับและกระจายแสง ป้องกัน UVB และ UVA ช่วงสั้นได้ดีมาก' + _MODERN,
      aka=['Tinosorb A2B'], en='Particulate UVB/UVA2 filter',
      smi='c1ccc(cc1)-c1ccc(cc1)-c1nc(nc(n1)-c1ccc(cc1)-c1ccccc1)-c1ccc(cc1)-c1ccccc1',
      f='C39H27N3'),
    I('Phenylene Bis-Diphenyltriazine', 'ไตรอะซอร์บ', ['uvChemical', 'uvMineral'], [S],
      'สารกันแดดอนุภาคอินทรีย์รุ่นใหม่ ป้องกันได้กว้างรวมถึงแสงสีฟ้า (HEV) บางส่วน' + _MODERN,
      aka=['TriAsorB'], en='New particulate filter, also covers some blue light',
      smi='c1ccc(cc1)-c1nc(nc(n1)-c1ccc(cc1)-c1nc(nc(n1)-c1ccccc1)-c1ccccc1)-c1ccccc1',
      f='C36H24N6'),
    I('Polysilicone-15', 'โพลีซิลิโคน-15', 'uvChemical', [S],
      'สารกันแดดชนิดพอลิเมอร์ซิลิโคน' + _UVB + ' โมเลกุลใหญ่มากจึงแทบไม่ซึมผ่านผิว', aka=['Parsol SLX'],
      en='Polymeric UVB filter', kind='polymer'),
    I('Ethylhexyl Methoxycrylene', 'เอทิลเฮกซิลเมทอกซีคริลีน', ['uvChemical', 'other'], [S],
      'สารช่วยให้สารกันแดดตัวอื่น (โดยเฉพาะอโวเบนโซน) คงตัวเมื่อโดนแสง (photostabilizer)',
      aka=['SolaStay S1'], en='Photostabiliser for avobenzone',
      smi='CCCCC(CC)COC(=O)C(C#N)=C(c1ccccc1)c1ccc(OC)cc1', f='C25H29NO3'),
    I('Diethylhexyl 2,6-Naphthalate', 'ไดเอทิลเฮกซิลแนฟทาเลต', ['emollient', 'other'], [S],
      'เอสเทอร์ที่ช่วยละลายและทำให้สารกันแดดคงตัวต่อแสง', aka=['Corapan TQ'],
      en='Photostabilising ester', smi='CCCCC(CC)COC(=O)c1ccc2cc(ccc2c1)C(=O)OCC(CC)CCCC',
      f='C28H40O4'),
    I('Diethylhexyl Syringylidenemalonate', 'ไดเอทิลเฮกซิลไซริงจิลิดีนมาโลเนต', ['antioxidant', 'other'], [S],
      'สารต้านอนุมูลอิสระที่ช่วยให้สูตรกันแดดคงตัวต่อแสง', aka=['Oxynex ST'], en='Photostabilising antioxidant',
      smi='CCCCC(CC)COC(=O)C(=Cc1cc(OC)c(O)c(OC)c1)C(=O)OCC(CC)CCCC', f='C28H44O7'),
    # ---------- Esters / solvents for filters ----------
    I('Butyloctyl Salicylate', 'บิวทิลออกทิลซาลิไซเลต', ['emollient', 'other'], [S],
      _ESTER + ' และช่วยเพิ่ม SPF เล็กน้อย', en='Ester that dissolves and boosts UV filters',
      smi='CCCCCCC(CCCC)COC(=O)c1ccccc1O', f='C19H30O3'),
    I('C12-15 Alkyl Benzoate', 'ซี12-15 อัลคิลเบนโซเอต', 'emollient', [S, M], _ESTER + ' ให้สัมผัสแห้งไม่เหนอะ',
      en='Light ester; dissolves UV filters', kind='mixture'),
    I('Dibutyl Adipate', 'ไดบิวทิลอะดิเพต', ['emollient', 'solvent'], [S], _ESTER + ' เนื้อเบามาก',
      en='Very light ester solvent for UV filters', smi='CCCCOC(=O)CCCCC(=O)OCCCC', f='C14H26O4'),
    I('Diisopropyl Sebacate', 'ไดไอโซโพรพิลเซบาเคต', ['emollient', 'solvent'], [S], _ESTER,
      en='Light ester solvent', smi='CC(C)OC(=O)CCCCCCCCC(=O)OC(C)C', f='C16H30O4'),
    I('Dicaprylyl Carbonate', 'ไดแคพริลิลคาร์บอเนต', 'emollient', [S, M, C], _ESTER + ' ซึมเร็ว สัมผัสแห้งนุ่มเหมือนแป้ง',
      en='Fast-spreading dry emollient', smi='CCCCCCCCOC(=O)OCCCCCCCC', f='C17H34O3'),
    I('Phenethyl Benzoate', 'ฟีนีทิลเบนโซเอต', ['emollient', 'solvent'], [S], _ESTER,
      en='Ester solvent for UV filters', smi='O=C(OCCc1ccccc1)c1ccccc1', f='C15H14O2'),
    I('Isododecane', 'ไอโซโดเดเคน', ['emollient', 'solvent'], [S, C],
      'น้ำมันไฮโดรคาร์บอนเบาที่ระเหยได้ ช่วยให้เนื้อบางเบา แห้งไว ไม่มัน พบในกันแดดและเมคอัพติดทน',
      en='Volatile light hydrocarbon', smi='CC(CC(C)(C)C)CC(C)(C)C', f='C12H26'),
    I('Isohexadecane', 'ไอโซเฮกซะเดเคน', 'emollient', [S, M, C], 'น้ำมันไฮโดรคาร์บอนเบา ให้สัมผัสลื่นไม่มัน',
      en='Light hydrocarbon emollient', kind='mixture'),
    # ---------- Coatings, powders, film formers ----------
    I('Triethoxycaprylylsilane', 'ไตรเอทอกซีแคพริลิลไซเลน', 'other', [S],
      'สารเคลือบผิวอนุภาคซิงค์/ไทเทเนียม ช่วยให้กระจายตัวในน้ำมันได้ดีและลดการทำปฏิกิริยากับแสง',
      aka=['coating'], en='Coating for mineral UV filters',
      smi='CCCCCCCC[Si](OCC)(OCC)OCC', f='C14H32O3Si'),
    I('Alumina', 'อะลูมินา', ['other', 'absorbent'], [S], 'อะลูมิเนียมออกไซด์ ใช้เคลือบอนุภาคไทเทเนียมไดออกไซด์เพื่อลดปฏิกิริยาแสง',
      aka=['coating'], en='Coating for TiO2', kind='mineral', f='Al2O3'),
    I('Aluminum Hydroxide', 'อะลูมิเนียมไฮดรอกไซด์', 'other', [S], 'ใช้เคลือบอนุภาคไทเทเนียมไดออกไซด์และปรับเนื้อสัมผัส',
      aka=['coating'], en='Coating for TiO2', kind='mineral', f='Al(OH)3'),
    I('Silica', 'ซิลิกา', ['absorbent', 'thickener'], [S, M, C],
      'ผงซิลิกอนไดออกไซด์ทรงกลมละเอียด ดูดซับความมัน ทำให้หน้าดูแมตต์และเกลี่ยง่าย', aka=['oil control', 'คุมมัน'],
      en='Oil-absorbing silica powder', kind='mineral', f='SiO2'),
    I('Hydrated Silica', 'ไฮเดรตซิลิกา', ['absorbent', 'exfoliant'], [S, C], 'ซิลิกาที่มีน้ำในโครงสร้าง ดูดซับความมัน หรือใช้เป็นเม็ดขัดละเอียด',
      en='Absorbent silica', kind='mineral'),
    I('Silica Dimethyl Silylate', 'ซิลิกาไดเมทิลไซลิเลต', 'thickener', [S], 'ซิลิกาที่เคลือบผิวให้ชอบน้ำมัน ช่วยเพิ่มความข้นของเฟสน้ำมันและดูดซับความมัน',
      en='Oil-phase thickener', kind='mineral'),
    I('Polymethylsilsesquioxane', 'โพลีเมทิลซิลเซสควิออกเซน', 'absorbent', [S, M], 'ผงซิลิโคนทรงกลมละเอียด ให้สัมผัสนุ่มลื่นเหมือนแป้ง เบลอรูขุมขน',
      aka=['silky powder'], en='Silky silicone powder', kind='polymer'),
    I('Methyl Methacrylate Crosspolymer', 'เมทิลเมทาคริเลตครอสพอลิเมอร์', 'absorbent', [S], 'ผงพอลิเมอร์ทรงกลม ช่วยลดความมันวาวและให้ผิวสัมผัสเนียน',
      en='Mattifying powder', kind='polymer'),
    I('Nylon-12', 'ไนลอน-12', 'absorbent', [S, M], 'ผงไนลอนทรงกลมละเอียด ช่วยเบลอรูขุมขนและให้สัมผัสแห้งนุ่ม',
      en='Soft-focus powder', kind='polymer'),
    I('Boron Nitride', 'โบรอนไนไตรด์', 'absorbent', [S], 'ผงแร่สีขาวลื่นมาก ช่วยให้เกลี่ยง่ายและผิวดูเรียบ',
      en='Slip-enhancing mineral powder', kind='mineral', f='BN'),
    I('Acrylates/C12-22 Alkyl Methacrylate Copolymer', 'อะคริเลต/ซี12-22 อัลคิลเมทาคริเลตโคพอลิเมอร์', 'filmFormer',
      [S], _FILM, aka=['water resistant', 'กันน้ำ'], en='Water-resistant film former', kind='polymer'),
    I('VP/Eicosene Copolymer', 'วีพี/ไอโคซีนโคพอลิเมอร์', 'filmFormer', [S], _FILM,
      aka=['water resistant', 'กันน้ำ'], en='Water-resistant film former', kind='polymer'),
    I('VP/Hexadecene Copolymer', 'วีพี/เฮกซะเดซีนโคพอลิเมอร์', 'filmFormer', [S], _FILM,
      aka=['water resistant', 'กันน้ำ'], en='Water-resistant film former', kind='polymer'),
    I('Trimethylsiloxysilicate', 'ไตรเมทิลไซลอกซีซิลิเกต', 'filmFormer', [S, C], _FILM + ' พบในเมคอัพกันน้ำด้วย',
      aka=['water resistant', 'กันน้ำ'], en='Long-wear silicone resin', kind='polymer'),
    I('Styrene/Acrylates Copolymer', 'สไตรีน/อะคริเลตโคพอลิเมอร์', ['filmFormer', 'other'], [S],
      'เม็ดพอลิเมอร์กลวงขนาดเล็กที่ช่วยกระจายแสงภายในชั้นกันแดด ทำให้ค่า SPF สูงขึ้น (SPF booster)',
      aka=['SPF booster', 'SunSpheres'], en='SPF booster (hollow spheres)', kind='polymer'),
    I('Polyester-8', 'โพลีเอสเตอร์-8', ['filmFormer', 'other'], [S], 'พอลิเมอร์ที่ช่วยให้อโวเบนโซนคงตัวและเพิ่มความกันน้ำ',
      en='Photostabilising polymer', kind='polymer'),
    I('Polyhydroxystearic Acid', 'โพลีไฮดรอกซีสเตียริกแอซิด', ['emulsifier', 'other'], [S],
      'สารช่วยกระจายตัว (dispersant) ทำให้ผงซิงค์/ไทเทเนียมไม่จับตัวเป็นก้อน การป้องกันจึงสม่ำเสมอ',
      en='Dispersant for mineral filters', kind='polymer'),
    I('Disteardimonium Hectorite', 'ไดสเตียร์ไดโมเนียมเฮกโทไรต์', 'thickener', [S, M], 'ดินแร่ที่ปรับให้ข้นในน้ำมัน ช่วยให้ผงกันแดดไม่ตกตะกอน',
      en='Oil-phase clay thickener', kind='mineral'),
    I('Dextrin Palmitate', 'เด็กซ์ทรินปาล์มิเตต', 'thickener', [S, C], 'สารทำให้น้ำมันข้นเป็นเจล ใช้ในกันแดดเนื้อน้ำมันและคลีนซิ่ง',
      en='Oil gelling agent', kind='polymer'),
    I('Lauryl PEG-9 Polydimethylsiloxyethyl Dimethicone', 'ลอริลพีอีจี-9 โพลีไดเมทิลไซลอกซีเอทิลไดเมทิโคน', 'emulsifier',
      [S], 'อิมัลซิไฟเออร์ซิลิโคนสำหรับสูตรน้ำในน้ำมัน (water-in-oil) ที่กันน้ำได้ดี', en='Silicone W/O emulsifier',
      kind='polymer'),
    I('PEG-10 Dimethicone', 'พีอีจี-10 ไดเมทิโคน', 'emulsifier', [S, M], 'อิมัลซิไฟเออร์ซิลิโคน ช่วยให้กันแดดเนื้อบางเบาและกันน้ำ',
      en='Silicone emulsifier', kind='polymer'),
    I('Cetyl PEG/PPG-10/1 Dimethicone', 'ซีทิลพีอีจี/พีพีจี-10/1 ไดเมทิโคน', 'emulsifier', [S, M], 'อิมัลซิไฟเออร์ซิลิโคนสำหรับสูตรน้ำในน้ำมัน',
      en='Silicone W/O emulsifier', kind='polymer'),
    I('Polyglyceryl-2 Dipolyhydroxystearate', 'โพลีกลีเซอริล-2 ไดโพลีไฮดรอกซีสเตียเรต', 'emulsifier', [S, M],
      'อิมัลซิไฟเออร์จากพืชสำหรับสูตรน้ำในน้ำมัน นิยมในกันแดดแร่', en='Plant-based W/O emulsifier', kind='polymer'),
    I('Potassium Cetyl Phosphate', 'โพแทสเซียมซีทิลฟอสเฟต', 'emulsifier', [S, M],
      'อิมัลซิไฟเออร์ที่ทำให้กันแดดคงตัวและกันน้ำดีขึ้น', en='Emulsifier for water-resistant sunscreens',
      smi='CCCCCCCCCCCCCCCCOP(=O)(O)[O-].[K+]', f='C16H34KO4P'),
    I('Methyl Trimethicone', 'เมทิลไตรเมทิโคน', ['emollient', 'solvent'], [S, M],
      'ซิลิโคนเหลวระเหยได้ ให้เนื้อบางเบา แห้งไว ไม่เหนอะ', en='Volatile light silicone',
      smi='C[Si](C)(C)O[Si](C)(O[Si](C)(C)C)O[Si](C)(C)C', f='C10H30O3Si4'),
    I('Caprylyl Methicone', 'แคพริลิลเมทิโคน', 'emollient', [S, M], 'ซิลิโคนเหลวเนื้อบาง ช่วยละลายสารกันแดดและให้สัมผัสนุ่มลื่น',
      en='Light silicone that blends with UV filters', kind='polymer'),
    I('Alcohol Denat.', 'แอลกอฮอล์ (ดีเนเจอร์)', 'solvent', [S, T, C],
      'เอทานอลที่เติมสารทำให้รสขมเพื่อไม่ให้ดื่มได้ ช่วยให้กันแดด/โทนเนอร์แห้งไว ซึมเร็ว และรู้สึกสดชื่น',
      aka=['alcohol', 'แอลกอฮอล์', 'SD alcohol'], note='alcohol', en='Denatured alcohol; quick-drying',
      kind='mixture'),
    I('Alcohol', 'เอทานอล', 'solvent', [S, T, C], 'เอทิลแอลกอฮอล์ ตัวทำละลายที่ระเหยเร็ว ช่วยให้เนื้อบางเบา',
      aka=['ethanol', 'แอลกอฮอล์'], note='alcohol', en='Ethanol; quick-drying solvent',
      smi='CCO', f='C2H6O'),
]
