"""More texture ingredients: esters, oils' derivatives, silicones, emulsifiers, thickeners."""
from common import ALL, C, E, I, M, S, T

_ESTER = 'เอสเทอร์ (emollient) ช่วยให้ผิวนุ่มเรียบลื่นและเนื้อผลิตภัณฑ์เกลี่ยง่าย'
_LIGHT = ' เนื้อบางเบา ไม่มันเยิ้ม'
_SIL = 'ซิลิโคนที่ให้สัมผัสลื่นนุ่ม เกลี่ยง่าย และช่วยให้ผิวดูเรียบเนียน'
_EMU = 'อิมัลซิไฟเออร์ ช่วยให้น้ำกับน้ำมันผสมกันเป็นเนื้อครีม/โลชั่นที่ไม่แยกชั้น'
_PG = _EMU + ' ทำจากกลีเซอรีนพืช ไม่มี PEG'
_THICK = 'สารเพิ่มความข้นและทำให้เนื้อสูตรคงตัว'
_SYN = 'พอลิเมอร์สังเคราะห์ที่ทำให้เนื้อเจล/ครีมข้น คงตัว ใช้ปริมาณน้อย'
_FILM = 'พอลิเมอร์สร้างฟิล์มบางๆ บนผิว ช่วยให้ติดทน/กันน้ำ หรือให้ผิวรู้สึกเรียบตึง'
_SOLUB = 'สารช่วยละลายน้ำมันหรือน้ำหอมปริมาณน้อยลงในสูตรที่เป็นน้ำ (solubiliser)'

ROWS = [
    # ---------- Esters ----------
    I('Isocetyl Stearate', 'ไอโซซีทิลสเตียเรต', 'emollient', [M], _ESTER, en='Emollient ester', kind='mixture'),
    I('Ethylhexyl Hydroxystearate', 'เอทิลเฮกซิลไฮดรอกซีสเตียเรต', 'emollient', [M, S], _ESTER + ' ช่วยกระจายเม็ดสี', en='Pigment-wetting ester',
      smi='CCCCCCC(O)CCCCCCCCCCC(=O)OCC(CC)CCCC', f='C26H52O3'),
    I('Isopropyl Lauroyl Sarcosinate', 'ไอโซโพรพิลลอรอยล์ซาร์โคซิเนต', ['emollient', 'solvent'], [S, M], _ESTER + ' ช่วยละลายสารกันแดดชนิดผงได้ดีมาก',
      en='Excellent UV-filter solvent', smi='CCCCCCCCCCCC(=O)N(C)CC(=O)OC(C)C', f='C18H35NO3'),
    I('Diethylhexyl Carbonate', 'ไดเอทิลเฮกซิลคาร์บอเนต', 'emollient', [S, M], _ESTER + _LIGHT, en='Light carbonate ester',
      smi='CCCCC(CC)COC(=O)OCC(CC)CCCC', f='C17H34O3'),
    I('Butylene Glycol Dicaprylate/Dicaprate', 'บิวทิลีนไกลคอลไดแคพริเลต/ไดแคพเรต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light ester', kind='mixture'),
    I('Propylene Glycol Dicaprylate/Dicaprate', 'โพรพิลีนไกลคอลไดแคพริเลต/ไดแคพเรต', 'emollient', [M, S], _ESTER + _LIGHT, en='Light ester', kind='mixture'),
    I('Pentaerythrityl Tetraethylhexanoate', 'เพนตะอีริทริทิลเตตระเอทิลเฮกซาโนเอต', 'emollient', [M, C], _ESTER + ' ให้ความชุ่มชื้นนาน', en='Rich ester'),
    I('Trimethylolpropane Triethylhexanoate', 'ไตรเมทิลอลโพรเพนไตรเอทิลเฮกซาโนเอต', 'emollient', [M], _ESTER, en='Emollient ester'),
    I('Tribehenin', 'ไตรบีเฮนิน', ['thickener', 'emollient'], [M], 'ไตรกลีเซอไรด์ของกรดบีเฮนิก ช่วยให้เนื้อบาล์ม/ครีมแข็งตัว', en='Waxy triglyceride', kind='mixture'),
    I('Glyceryl Dibehenate', 'กลีเซอริลไดบีเฮเนต', ['thickener', 'emollient'], [M], 'ไขมันที่ช่วยเพิ่มความข้นให้เฟสน้ำมัน', en='Oil thickener', kind='mixture'),
    I('Hydrogenated Coco-Glycerides', 'โคโคกลีเซอไรด์ไฮโดรจีเนต', ['emollient', 'thickener'], [M], 'ไขมันจากมะพร้าวที่เติมไฮโดรเจน ให้ความนุ่ม', en='Coconut glycerides', kind='mixture'),
    I('Cocoglycerides', 'โคโคกลีเซอไรด์', 'emollient', [M, C], 'ไขมันจากมะพร้าว ให้ความนุ่มชุ่มชื้น', en='Coconut glycerides', kind='mixture'),
    I('C10-18 Triglycerides', 'ซี10-18 ไตรกลีเซอไรด์', 'emollient', [M], 'ไตรกลีเซอไรด์จากพืช ให้ความนุ่ม', en='Plant triglycerides', kind='mixture'),
    I('Triisostearin', 'ไตรไอโซสเตียริน', 'emollient', [M], _ESTER + ' เนื้อหนืด ให้ความชุ่มชื้นสูง', en='Rich emollient', kind='mixture'),
    I('Isodecyl Neopentanoate', 'ไอโซเดซิลนีโอเพนทาโนเอต', 'emollient', [S, M], _ESTER + _LIGHT, en='Light ester'),
    I('Isostearyl Neopentanoate', 'ไอโซสเตียริลนีโอเพนทาโนเอต', 'emollient', [M], _ESTER, en='Emollient ester', kind='mixture'),
    I('Tridecyl Trimellitate', 'ไตรเดซิลไตรเมลลิเตต', 'emollient', [M], _ESTER + ' เงาและติดทน', en='Glossy ester', kind='mixture'),
    I('Octyldodecyl Myristate', 'ออกทิลโดเดซิลไมริสเตต', 'emollient', [M], _ESTER, en='Emollient ester',
      smi='CCCCCCCCCCCCCC(=O)OCC(CCCCCCCC)CCCCCCCCCC', f='C34H68O2'),
    I('Hexyl Laurate', 'เฮกซิลลอเรต', 'emollient', [M, C], _ESTER + _LIGHT, en='Light ester', smi='CCCCCCCCCCCC(=O)OCCCCCC', f='C18H36O2'),
    I('Decyl Cocoate', 'เดซิลโคโคเอต', 'emollient', [M, C], _ESTER + ' จากมะพร้าว', en='Coconut ester', kind='mixture'),
    I('Ethyl Linoleate', 'เอทิลไลโนลีเอต', ['emollient', 'barrier'], [M, E], 'เอสเทอร์ของกรดไลโนเลอิก ช่วยเสริมเกราะผิวและอาจช่วยลดสิวอุดตัน', en='Linoleic ester',
      smi='CCCCC/C=C\\C/C=C\\CCCCCCCC(=O)OCC', f='C20H36O2'),
    I('Ethyl Oleate', 'เอทิลโอลีเอต', 'emollient', [M], _ESTER, en='Oleic ester', smi='CCCCCCCC/C=C\\CCCCCCCC(=O)OCC', f='C20H38O2'),
    I('Isostearyl Alcohol', 'ไอโซสเตียริลแอลกอฮอล์', 'emollient', [M], 'แอลกอฮอล์ไขมันกิ่งที่เป็นของเหลว ให้ความนุ่ม (ไม่ใช่แอลกอฮอล์ที่ทำให้แห้ง)', en='Liquid fatty alcohol',
      kind='mixture'),
    I('Neopentyl Glycol Diethylhexanoate', 'นีโอเพนทิลไกลคอลไดเอทิลเฮกซาโนเอต', 'emollient', [S, M], _ESTER + _LIGHT, en='Light ester',
      smi='CCCCC(CC)C(=O)OCC(C)(C)COC(=O)C(CC)CCCC', f='C21H40O4'),
    I('Butyrospermum Parkii Oil', 'น้ำมันเชีย', 'emollient', [M, C], 'ส่วนที่เป็นของเหลวของเชียบัตเตอร์ เนื้อเบากว่า', aka=['Shea Oil', 'Shea Olein'], en='Liquid shea oil', kind='oil'),
    I('Hydrogenated Olive Oil', 'น้ำมันมะกอกไฮโดรจีเนต', ['emollient', 'thickener'], [M], 'น้ำมันมะกอกที่เติมไฮโดรเจนให้คงตัวและข้นขึ้น', en='Hardened olive oil', kind='oil'),
    I('Olea Europaea Oil Unsaponifiables', 'ส่วนที่ไม่เป็นสบู่ของน้ำมันมะกอก', ['emollient', 'antioxidant'], [M], 'ส่วนที่มีสควาลีน ไฟโตสเตอรอล และวิตามินอีจากน้ำมันมะกอก', en='Olive unsaponifiables',
      kind='mixture'),
    I('Hydrogenated Jojoba Oil', 'น้ำมันโจโจบาไฮโดรจีเนต', ['thickener', 'emollient'], [M], 'โจโจบาที่เติมไฮโดรเจนจนแข็ง ใช้ปรับเนื้อบาล์ม', en='Hardened jojoba', kind='oil'),
    I('Hydrogenated Rapeseed Oil', 'น้ำมันเรพซีดไฮโดรจีเนต', ['thickener', 'emollient'], [M], 'น้ำมันเรพซีดที่เติมไฮโดรเจน ใช้ปรับเนื้อ', en='Hardened rapeseed oil', kind='oil'),
    I('Hydrogenated Palm Oil', 'น้ำมันปาล์มไฮโดรจีเนต', ['thickener', 'emollient'], [M, C], 'น้ำมันปาล์มที่เติมไฮโดรเจน ใช้ปรับเนื้อ', en='Hardened palm oil', kind='oil'),
    I('Hydrogenated Coconut Oil', 'น้ำมันมะพร้าวไฮโดรจีเนต', ['thickener', 'emollient'], [M, C], 'น้ำมันมะพร้าวที่เติมไฮโดรเจน ใช้ปรับเนื้อ', en='Hardened coconut oil', kind='oil'),
    I('Elaeis Guineensis Kernel Oil', 'น้ำมันเมล็ดในปาล์ม', 'emollient', [C, M], 'น้ำมันจากเมล็ดในปาล์ม คล้ายน้ำมันมะพร้าว', aka=['Palm Kernel Oil'], en='Palm kernel oil', kind='oil'),
    I('Behenic Acid', 'กรดบีเฮนิก', ['thickener', 'emollient'], [M], 'กรดไขมันสายยาว ช่วยให้ครีมข้นและคงตัว', en='Long-chain fatty acid',
      smi='CCCCCCCCCCCCCCCCCCCCCC(=O)O', f='C22H44O2'),
    I('Arachidic Acid', 'กรดอะราคิดิก', ['thickener', 'emollient'], [M], 'กรดไขมันสายยาว ช่วยให้ครีมข้น', en='Long-chain fatty acid',
      smi='CCCCCCCCCCCCCCCCCCCC(=O)O', f='C20H40O2'),
    I('Hydroxystearic Acid', 'กรดไฮดรอกซีสเตียริก', ['thickener', 'emollient'], [M, S], 'กรดไขมันที่ช่วยให้น้ำมันข้นเป็นเจล', en='Oil-gelling fatty acid',
      smi='CCCCCCC(O)CCCCCCCCCCC(=O)O', f='C18H36O3'),
    # ---------- Silicones ----------
    I('Polysilicone-11', 'โพลีซิลิโคน-11', ['filmFormer', 'absorbent'], [S, M], _SIL + ' เป็นเจลซิลิโคนที่ช่วยเบลอรูขุมขน', aka=['silicone'], en='Silicone gel', kind='polymer'),
    I('Trimethylsiloxyphenyl Dimethicone', 'ไตรเมทิลไซลอกซีฟีนิลไดเมทิโคน', 'emollient', [M, S], _SIL, aka=['silicone'], en='Silicone', kind='polymer'),
    I('Stearyl Dimethicone', 'สเตียริลไดเมทิโคน', ['emollient', 'occlusive'], [M], _SIL + ' เนื้อแว็กซ์', aka=['silicone'], en='Waxy silicone', kind='polymer'),
    I('Diphenylsiloxy Phenyl Trimethicone', 'ไดฟีนิลไซลอกซีฟีนิลไตรเมทิโคน', 'emollient', [M], _SIL + ' ให้ความเงา', aka=['silicone'], en='Glossy silicone', kind='polymer'),
    I('Methicone', 'เมทิโคน', ['emollient', 'other'], [S, M], _SIL + ' ใช้เคลือบผงแป้ง/เม็ดสีด้วย', aka=['silicone'], en='Silicone coating', kind='polymer'),
    I('Dimethicone/PEG-10/15 Crosspolymer', 'ไดเมทิโคน/พีอีจี-10/15 ครอสพอลิเมอร์', ['emulsifier', 'thickener'], [S, M], _SIL + ' และช่วยให้น้ำในน้ำมันคงตัว', aka=['silicone'],
      en='Silicone emulsifying elastomer', kind='polymer'),
    I('PEG-12 Dimethicone', 'พีอีจี-12 ไดเมทิโคน', ['emulsifier', 'emollient'], [C, M, T], 'ซิลิโคนที่ละลายน้ำได้ ให้สัมผัสลื่นในสูตรเนื้อน้ำ', aka=['silicone'], en='Water-soluble silicone',
      kind='polymer'),
    I('PEG/PPG-18/18 Dimethicone', 'พีอีจี/พีพีจี-18/18 ไดเมทิโคน', 'emulsifier', [S, M], _EMU + ' ชนิดซิลิโคน', aka=['silicone'], en='Silicone emulsifier', kind='polymer'),
    I('Lauryl Polyglyceryl-3 Polydimethylsiloxyethyl Dimethicone', 'ลอริลโพลีกลีเซอริล-3 โพลีไดเมทิลไซลอกซีเอทิลไดเมทิโคน', 'emulsifier', [S],
      _EMU + ' ชนิดซิลิโคนสำหรับกันแดดกันน้ำ', aka=['silicone'], en='Silicone W/O emulsifier', kind='polymer'),
    I('Bis-PEG-18 Methyl Ether Dimethyl Silane', 'บิส-พีอีจี-18 เมทิลอีเทอร์ไดเมทิลไซเลน', ['humectant', 'emollient'], [T, E], 'ซิลิโคนละลายน้ำที่ให้สัมผัสลื่นไม่เหนียวในโทนเนอร์',
      en='Water-soluble silicone', kind='polymer'),
    I('Silica Silylate', 'ซิลิกาไซลิเลต', ['absorbent', 'thickener'], [S, M], 'ผงซิลิกาเคลือบที่ดูดซับความมัน ให้หน้าแมตต์', en='Mattifying silica', kind='mineral'),
    # ---------- Emulsifiers / solubilisers ----------
    I('Polyglyceryl-10 Stearate', 'โพลีกลีเซอริล-10 สเตียเรต', 'emulsifier', [M], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-10 Myristate', 'โพลีกลีเซอริล-10 ไมริสเตต', 'emulsifier', [M, T], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-10 Oleate', 'โพลีกลีเซอริล-10 โอลีเอต', 'emulsifier', [M, C], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-10 Dioleate', 'โพลีกลีเซอริล-10 ไดโอลีเอต', 'emulsifier', [C], _PG + ' ใช้ในคลีนซิ่งออยล์', en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-3 Diisostearate', 'โพลีกลีเซอริล-3 ไดไอโซสเตียเรต', 'emulsifier', [M, S], _PG + ' สำหรับครีมน้ำในน้ำมัน', en='PEG-free W/O emulsifier', kind='polymer'),
    I('Polyglyceryl-2 Triisostearate', 'โพลีกลีเซอริล-2 ไตรไอโซสเตียเรต', ['emulsifier', 'emollient'], [C, M], _PG + ' นิยมในคลีนซิ่งออยล์/บาล์ม', en='Cleansing-oil emulsifier',
      kind='polymer'),
    I('Polyglyceryl-2 Caprate', 'โพลีกลีเซอริล-2 แคพเรต', 'emulsifier', [C, M], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-4 Oleate', 'โพลีกลีเซอริล-4 โอลีเอต', 'emulsifier', [C, M], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Polyglyceryl-6 Laurate', 'โพลีกลีเซอริล-6 ลอเรต', ['emulsifier', 'surfactant'], [C], _PG, en='PEG-free emulsifier', kind='polymer'),
    I('Glyceryl Laurate', 'กลีเซอริลลอเรต', ['emulsifier', 'preservative'], [M, C], _EMU + ' และช่วยต้านเชื้ออ่อนๆ', en='Emulsifier with antimicrobial boost',
      smi='CCCCCCCCCCCC(=O)OCC(O)CO', f='C15H30O4'),
    I('Glyceryl Isostearate', 'กลีเซอริลไอโซสเตียเรต', 'emulsifier', [M], _EMU, en='Emulsifier', kind='mixture'),
    I('Sorbitan Laurate', 'ซอร์บิแทนลอเรต', 'emulsifier', [M, C], _EMU, aka=['Span 20'], en='Sorbitan emulsifier',
      smi='CCCCCCCCCCCC(=O)OCC(O)C1OCC(O)C1O', f='C18H34O6'),
    I('Sodium Stearoyl Lactylate', 'โซเดียมสเตียรอยล์แลคทิเลต', 'emulsifier', [M], _EMU + ' จากกรดสเตียริกกับกรดแลคติก อ่อนโยน', en='Gentle emulsifier',
      smi='CCCCCCCCCCCCCCCCCC(=O)OC(C)C(=O)OC(C)C(=O)[O-].[Na+]', f='C24H43NaO6'),
    I('PEG-30 Dipolyhydroxystearate', 'พีอีจี-30 ไดโพลีไฮดรอกซีสเตียเรต', 'emulsifier', [S, M], _EMU + ' สำหรับครีมน้ำในน้ำมัน', en='W/O emulsifier', kind='polymer'),
    I('Laureth-23', 'ลอเรท-23', ['surfactant', 'emulsifier'], [C, M], _SOLUB, en='Solubiliser', kind='polymer'),
    I('Oleth-10', 'โอเลท-10', ['emulsifier', 'surfactant'], [M, C], _EMU, en='Emulsifier', kind='polymer'),
    I('Ceteth-20', 'ซีเทท-20', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Isoceteth-20', 'ไอโซซีเทท-20', ['emulsifier', 'surfactant'], [M, T], _SOLUB, en='Solubiliser', kind='polymer'),
    I('Trideceth-6', 'ไตรเดเซท-6', ['emulsifier', 'surfactant'], [M], _EMU, en='Emulsifier', kind='polymer'),
    I('Steareth-100', 'สเตียเรท-100', 'emulsifier', [M], _EMU, en='Emulsifier', kind='polymer'),
    I('PEG-60 Glyceryl Isostearate', 'พีอีจี-60 กลีเซอริลไอโซสเตียเรต', ['emulsifier', 'surfactant'], [T, E], _SOLUB, en='Solubiliser', kind='polymer'),
    I('PPG-26-Buteth-26', 'พีพีจี-26-บิวเทท-26', ['emulsifier', 'surfactant'], [T, E], _SOLUB, en='Solubiliser', kind='polymer'),
    I('PEG/PPG-17/6 Copolymer', 'พีอีจี/พีพีจี-17/6 โคพอลิเมอร์', ['humectant', 'emollient'], [T, E], 'พอลิเมอร์ที่ให้ความชุ่มชื้นและสัมผัสลื่นในโทนเนอร์', en='Hydrating polymer', kind='polymer'),
    I('PEG-4', 'พีอีจี-4', ['humectant', 'solvent'], [C, M], 'พอลิเอทิลีนไกลคอลสายสั้น ดูดความชุ่มชื้นและเป็นตัวทำละลาย', en='Short PEG', kind='polymer'),
    I('PEG-32', 'พีอีจี-32', ['humectant', 'thickener'], [C, M], 'พอลิเอทิลีนไกลคอล ให้ความชุ่มชื้นและปรับเนื้อ', en='PEG', kind='polymer'),
    I('PEG-75', 'พีอีจี-75', ['humectant', 'thickener'], [C, M], 'พอลิเอทิลีนไกลคอลสายยาว ให้ความชุ่มชื้น', en='PEG', kind='polymer'),
    I('Lauryl Betaine', 'ลอริลบีเทน', 'surfactant', [C], 'สารทำความสะอาดชนิด amphoteric อ่อนโยน', en='Mild amphoteric cleanser',
      smi='CCCCCCCCCCCC[N+](C)(C)CC(=O)[O-]', f='C16H33NO2'),
    # ---------- Thickeners / gelling ----------
    I('Ammonium Acryloyldimethyltaurate/Beheneth-25 Methacrylate Crosspolymer', 'แอมโมเนียมอะคริโลอิลไดเมทิลทอเรต/บีเฮเนท-25 เมทาคริเลตครอสพอลิเมอร์',
      'thickener', [M, S], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer', 'โซเดียมอะคริเลต/โซเดียมอะคริโลอิลไดเมทิลทอเรตโคพอลิเมอร์', 'thickener', [M, E],
      _SYN, en='Synthetic thickener', kind='polymer'),
    I('Acrylates/Beheneth-25 Methacrylate Copolymer', 'อะคริเลต/บีเฮเนท-25 เมทาคริเลตโคพอลิเมอร์', 'thickener', [C, M], _SYN, en='Synthetic thickener', kind='polymer'),
    I('Hydroxypropyl Guar', 'ไฮดรอกซีโพรพิลกัวร์', 'thickener', [C, M], _THICK + ' จากถั่วกัวร์', en='Guar thickener', kind='polymer'),
    I('Hectorite', 'เฮกโทไรต์', 'thickener', [M, S], 'ดินแร่ที่ช่วยเพิ่มความข้นและแขวนลอยผง', en='Clay thickener', kind='mineral'),
    I('Sodium Magnesium Silicate', 'โซเดียมแมกนีเซียมซิลิเกต', 'thickener', [M, C], 'ดินแร่สังเคราะห์ที่ช่วยให้เจลข้นใส', en='Synthetic clay thickener', kind='mineral'),
    I('Glyceryl Polymethacrylate', 'กลีเซอริลโพลีเมทาคริเลต', ['humectant', 'filmFormer'], [M, E], 'พอลิเมอร์ที่อุ้มน้ำ ให้ความชุ่มชื้นและสัมผัสลื่น', en='Moisture-binding polymer',
      kind='polymer'),
    I('Glyceryl Polyacrylate', 'กลีเซอริลโพลีอะคริเลต', ['humectant', 'filmFormer'], [M, E], 'พอลิเมอร์ที่อุ้มน้ำ ให้ความชุ่มชื้น', en='Moisture-binding polymer', kind='polymer'),
    I('Hydrolyzed Corn Starch', 'แป้งข้าวโพดไฮโดรไลซ์', ['humectant', 'filmFormer'], [M, T], 'แป้งข้าวโพดที่ย่อยแล้ว ให้ความชุ่มชื้นและสัมผัสนุ่ม', en='Hydrolysed corn starch',
      kind='polymer'),
    I('Aluminum Starch Octenylsuccinate', 'อะลูมิเนียมสตาร์ชออกทีนิลซัคซิเนต', 'absorbent', [S, M], 'แป้งดัดแปรที่ดูดซับความมัน ให้สัมผัสแห้งนุ่ม', en='Oil-absorbing starch',
      kind='polymer'),
    I('Dextrin', 'เด็กซ์ทริน', ['thickener', 'filmFormer'], [M, C], 'แป้งที่ย่อยบางส่วน ช่วยปรับเนื้อ', en='Starch derivative', kind='polymer'),
    I('Maltodextrin', 'มอลโตเด็กซ์ทริน', ['filmFormer', 'absorbent'], [M, C], 'แป้งย่อยที่ช่วยสร้างฟิล์มและปรับเนื้อ', en='Starch derivative', kind='polymer'),
    I('Cyclodextrin', 'ไซโคลเด็กซ์ทริน', ['other', 'absorbent'], [E, M], 'น้ำตาลวงแหวนที่ห่อหุ้มสารสำคัญหรือกลิ่นไว้ ช่วยให้คงตัว', en='Encapsulating sugar ring',
      kind='polymer'),
    I('Hydroxypropyl Cyclodextrin', 'ไฮดรอกซีโพรพิลไซโคลเด็กซ์ทริน', ['other', 'solvent'], [E], 'ไซโคลเด็กซ์ทรินดัดแปรที่ช่วยละลายและห่อหุ้มสารสำคัญ', en='Solubilising cyclodextrin',
      kind='polymer'),
    I('Mannitol', 'แมนนิทอล', ['humectant', 'antioxidant'], [M, T], 'น้ำตาลแอลกอฮอล์ที่ดูดความชุ่มชื้นและดักจับอนุมูลอิสระ', en='Sugar alcohol',
      smi='OCC(O)C(O)C(O)C(O)CO', f='C6H14O6'),
    I('Dextran', 'เด็กซ์แทรน', ['humectant', 'filmFormer'], [M, E], 'พอลิแซ็กคาไรด์ที่ให้ความชุ่มชื้น', en='Polysaccharide', kind='polymer'),
    I('Polymethyl Methacrylate', 'โพลีเมทิลเมทาคริเลต', 'absorbent', [S, M], 'ผงพอลิเมอร์ทรงกลมที่เบลอรูขุมขนและลดความมันวาว', aka=['PMMA'], en='Soft-focus powder', kind='polymer'),
    # ---------- Film formers ----------
    I('Polyquaternium-11', 'โพลีควอเทอร์เนียม-11', 'filmFormer', [C], _FILM, en='Conditioning film former', kind='polymer'),
    I('Polyquaternium-37', 'โพลีควอเทอร์เนียม-37', ['thickener', 'filmFormer'], [M, C], _FILM, en='Cationic thickener', kind='polymer'),
    I('Polyquaternium-39', 'โพลีควอเทอร์เนียม-39', 'filmFormer', [C], _FILM, en='Conditioning polymer', kind='polymer'),
    I('Acrylates/Dimethicone Copolymer', 'อะคริเลต/ไดเมทิโคนโคพอลิเมอร์', 'filmFormer', [S], _FILM + ' ใช้ในกันแดดกันน้ำ', en='Water-resistant film former', kind='polymer'),
    I('Hydrogenated Styrene/Isoprene Copolymer', 'สไตรีน/ไอโซพรีนโคพอลิเมอร์ไฮโดรจีเนต', ['filmFormer', 'thickener'], [S], _FILM, en='Film former', kind='polymer'),
    I('Polyester-7', 'โพลีเอสเตอร์-7', ['filmFormer', 'other'], [S], 'พอลิเมอร์ที่ช่วยให้สูตรกันแดดคงตัวต่อแสง', en='Photostabilising polymer', kind='polymer'),
]
