"""More plant extracts (Korean/Japanese/Thai favourites), fruit waters and essential oils."""
from common import ALL, C, E, I, M, S, T


def ext(inci, th, what, fn='antioxidant', use=(M, E, T), aka=(), en=None, note=None, good=None):
    return I(inci, th, fn, list(use), what, aka=aka, en=en or 'Plant extract', note=note, good=good, kind='extract')


_AOX = ' มีสารต้านอนุมูลอิสระ'
_SOOTHE = ' ช่วยปลอบประโลมผิวและลดรอยแดง'
_BRIGHT = ' ช่วยให้ผิวดูกระจ่างใส'
_HYD = ' ให้ความชุ่มชื้น'
_TONE = ' มีแทนนินที่ช่วยกระชับรูขุมขนและลดความมัน'
_EO = 'น้ำมันหอมระเหยจาก'
_EO_TIPS = 'ให้กลิ่นหอม อาจมีฤทธิ์อ่อนๆ ต่อผิว แต่มีสารก่อภูมิแพ้ตามธรรมชาติ ผิวแพ้ง่ายควรหลีกเลี่ยง'


def eo(inci, th, source, aka=(), note='essential', fn='fragrance', use=(C, M)):
    return I(inci, th, fn, list(use), _EO + source, tips=_EO_TIPS, aka=aka, note=note, en='Essential oil', kind='extract')


ROWS = [
    # ---------- Korean / Japanese favourites ----------
    ext('Paeonia Suffruticosa Root Extract', 'สารสกัดรากโบตั๋น', 'สารสกัดรากโบตั๋นต้น มีพีโอนอล' + _BRIGHT + _AOX, fn=['brightening', 'antioxidant'], aka=['Peony']),
    ext('Paeonia Albiflora Root Extract', 'สารสกัดรากโบตั๋นขาว', 'สารสกัดรากโบตั๋น' + _SOOTHE, fn='soothing', aka=['White Peony']),
    ext('Pueraria Lobata Root Extract', 'สารสกัดรากคุดสุ', 'สารสกัดรากคุดสุ (kudzu) มีไอโซฟลาโวน' + _AOX, aka=['Kudzu']),
    ext('Cnidium Officinale Root Extract', 'สารสกัดรากชวนเกียง', 'สมุนไพรจีน/เกาหลีที่ใช้ในตำรับแบบดั้งเดิม' + _SOOTHE, fn='soothing'),
    ext('Angelica Gigas Root Extract', 'สารสกัดรากโสมตังกุยเกาหลี', 'สมุนไพรเกาหลีที่ช่วยการไหลเวียน' + _AOX, aka=['Korean Angelica']),
    ext('Lilium Candidum Flower Extract', 'สารสกัดดอกลิลลี่ขาว', 'สารสกัดดอกลิลลี่' + _SOOTHE + _HYD, fn='soothing', aka=['Madonna Lily']),
    ext('Rosa Centifolia Flower Water', 'น้ำดอกกุหลาบเซนติโฟเลีย', 'น้ำกลั่นดอกกุหลาบ' + _HYD + ' และให้กลิ่นหอมอ่อนๆ', fn=['soothing', 'fragrance'], use=(T,), aka=['Rose Water']),
    ext('Citrus Grandis Fruit Extract', 'สารสกัดส้มโอ/เกรปฟรุต', 'สารสกัดผลส้มโอ มีวิตามินซีและฟลาโวนอยด์' + _BRIGHT, fn=['antioxidant', 'brightening'], aka=['Grapefruit', 'ส้มโอ']),
    ext('Prunus Mume Fruit Extract', 'สารสกัดบ๊วย', 'สารสกัดผลบ๊วย มีกรดผลไม้อ่อนๆ' + _BRIGHT, fn=['exfoliant', 'brightening'], aka=['Japanese Apricot', 'บ๊วย']),
    ext('Diospyros Kaki Leaf Extract', 'สารสกัดใบพลับ', 'สารสกัดใบพลับ มีแทนนินและวิตามินซี' + _AOX, aka=['Persimmon', 'พลับ']),
    ext('Nymphaea Alba Flower Extract', 'สารสกัดดอกบัวขาว', 'สารสกัดดอกบัวสาย' + _SOOTHE + _HYD, fn='soothing', aka=['White Water Lily']),
    ext('Coptis Japonica Root Extract', 'สารสกัดรากโคปติส', 'สมุนไพรที่มีเบอร์เบอรีน ต้านเชื้อแบคทีเรีย', fn=['antiAcne', 'soothing']),
    ext('Sophora Flavescens Root Extract', 'สารสกัดรากโซโฟรา', 'สมุนไพรที่ช่วยลดการอักเสบและเชื้อแบคทีเรียสิว', fn=['antiAcne', 'soothing']),
    ext('Glycyrrhiza Uralensis Root Extract', 'สารสกัดรากชะเอมจีน', 'สารสกัดชะเอมอีกสายพันธุ์' + _SOOTHE + _BRIGHT, fn=['soothing', 'brightening'], aka=['Licorice', 'ชะเอม']),
    ext('Betula Alba Juice', 'น้ำเลี้ยงต้นเบิร์ช', 'น้ำจากลำต้นเบิร์ช มีแร่ธาตุและน้ำตาลธรรมชาติ ใช้แทนน้ำในสูตร' + _HYD, fn=['humectant', 'solvent'], aka=['Birch Sap']),
    ext('Acer Saccharum Sap', 'น้ำเลี้ยงต้นเมเปิล', 'น้ำเลี้ยงต้นเมเปิล' + _HYD, fn=['humectant', 'solvent'], aka=['Maple Sap']),
    ext('Cocos Nucifera Fruit Juice', 'น้ำมะพร้าว', 'น้ำมะพร้าว มีแร่ธาตุและน้ำตาล' + _HYD, fn='humectant', aka=['Coconut Water', 'น้ำมะพร้าว']),
    ext('Aloe Barbadensis Leaf Water', 'น้ำใบว่านหางจระเข้', 'น้ำจากใบว่านหางจระเข้ ใช้แทนน้ำในสูตร' + _SOOTHE, fn=['soothing', 'solvent'], aka=['Aloe Water']),
    ext('Rice Ferment Filtrate (Sake)', 'น้ำหมักข้าว (สาเก)', 'ของเหลวจากการหมักข้าวแบบสาเก มีกรดอะมิโน กรดอินทรีย์ และวิตามิน' + _BRIGHT + _HYD,
        fn=['brightening', 'humectant'], aka=['Sake', 'สาเก', 'Rice Ferment'], en='Sake rice ferment'),
    ext('Oryza Sativa Bran Extract', 'สารสกัดรำข้าว', 'สารสกัดรำข้าว มีแกมมาโอรีซานอลและกรดเฟรูลิก' + _AOX + _BRIGHT, fn=['antioxidant', 'brightening'], aka=['Rice Bran']),
    ext('Oryza Sativa Germ Extract', 'สารสกัดจมูกข้าว', 'สารสกัดจมูกข้าว มีวิตามินและกรดอะมิโน' + _HYD, fn='humectant', aka=['Rice Germ']),
    ext('Oryza Sativa Water', 'น้ำซาวข้าว', 'น้ำซาวข้าว มีแป้งและแร่ธาตุ ช่วยให้ผิวนุ่ม', fn=['soothing', 'solvent'], aka=['Rice Water', 'น้ำซาวข้าว']),
    ext('Saccharomyces/Rice Ferment Filtrate', 'ข้าวหมักยีสต์', 'ผลิตภัณฑ์จากการหมักข้าวด้วยยีสต์' + _BRIGHT + _HYD, fn=['brightening', 'humectant'], aka=['Rice Ferment']),
    ext('Bifida Ferment Filtrate', 'ไบฟิดาเฟอร์เมนต์ฟิลเทรต', 'ของเหลวจากการหมักเชื้อไบฟิโดแบคทีเรีย ช่วยเสริมเกราะผิว', fn='barrier', aka=['probiotic', 'โพรไบโอติก']),
    ext('Lactobacillus/Pumpkin Fruit Ferment Filtrate', 'ฟักทองหมักแลคโตบาซิลลัส', 'ฟักทองหมักที่มีเอนไซม์ช่วยผลัดเซลล์อ่อนๆ', fn='exfoliant', use=(C, E)),
    ext('Yeast Extract', 'สารสกัดยีสต์', 'สารสกัดจากยีสต์ มีกรดอะมิโน วิตามินบี และเบต้ากลูแคน' + _HYD, fn=['humectant', 'antiAging'], aka=['Faex Extract']),
    ext('Hydrolyzed Rice Protein', 'โปรตีนข้าวไฮโดรไลซ์', 'โปรตีนข้าวที่ย่อยแล้ว' + _HYD + ' และสร้างฟิล์มนุ่ม', fn=['humectant', 'filmFormer'], use=(M, C)),
    ext('Hydrolyzed Soy Protein', 'โปรตีนถั่วเหลืองไฮโดรไลซ์', 'โปรตีนถั่วเหลืองที่ย่อยแล้ว' + _HYD, fn=['humectant', 'filmFormer'], use=(M, C)),
    ext('Hydrolyzed Oat Protein', 'โปรตีนข้าวโอ๊ตไฮโดรไลซ์', 'โปรตีนข้าวโอ๊ตที่ย่อยแล้ว' + _HYD + _SOOTHE, fn=['humectant', 'soothing'], use=(M, C)),
    ext('Hydrolyzed Keratin', 'เคราตินไฮโดรไลซ์', 'โปรตีนเคราตินที่ย่อยแล้ว ช่วยเสริมผมและผิวให้นุ่มลื่น', fn='filmFormer', use=(C, M)),
    ext('Hydrolyzed Pea Protein', 'โปรตีนถั่วลันเตาไฮโดรไลซ์', 'โปรตีนถั่วลันเตา' + _HYD, fn=['humectant', 'filmFormer'], use=(M, E)),
    ext('Hydrolyzed Yeast Protein', 'โปรตีนยีสต์ไฮโดรไลซ์', 'โปรตีนจากยีสต์ที่ย่อยแล้ว' + _HYD, fn='humectant', use=(M, E)),
    ext('Honey Extract', 'สารสกัดน้ำผึ้ง', 'สารสกัดน้ำผึ้ง' + _HYD + ' และต้านเชื้ออ่อนๆ', fn=['humectant', 'soothing'], aka=['Honey']),
    # ---------- Thai herbs ----------
    ext('Boesenbergia Rotunda Root Extract', 'สารสกัดกระชาย', 'สารสกัดเหง้ากระชาย มีพิโนสโตรบินและแพนดูราทิน' + _AOX + _BRIGHT, fn=['antioxidant', 'brightening'], aka=['Fingerroot', 'กระชาย']),
    ext('Kaempferia Galanga Root Extract', 'สารสกัดเปราะหอม', 'สารสกัดเปราะหอม มีเอทิลพาราเมทอกซีซินนาเมตซึ่งดูดซับ UV ได้เล็กน้อย' + _AOX, aka=['Aromatic Ginger', 'เปราะหอม']),
    ext('Kaempferia Parviflora Root Extract', 'สารสกัดกระชายดำ', 'สารสกัดกระชายดำ มีฟลาโวนอยด์' + _AOX, aka=['Black Ginger', 'กระชายดำ']),
    ext('Pueraria Mirifica Root Extract', 'สารสกัดกวาวเครือขาว', 'สมุนไพรไทยที่มีไฟโตเอสโตรเจน เชื่อว่าช่วยความชุ่มชื้นและความยืดหยุ่นของผิว', fn='antiAging',
        aka=['White Kwao Krua', 'กวาวเครือ'], note='pregnancy'),
    ext('Limonia Acidissima Bark Extract', 'สารสกัดทานาคา', 'ผงเปลือกไม้ทานาคาของพม่า ใช้ทาหน้าแบบดั้งเดิมเพื่อป้องกันแดดและให้ผิวเย็นสบาย', fn=['soothing', 'absorbent'],
        aka=['Thanaka', 'ทานาคา'], use=(M, C)),
    ext('Andrographis Paniculata Extract', 'สารสกัดฟ้าทะลายโจร', 'สมุนไพรไทยที่มีแอนโดรกราโฟไลด์ ต้านการอักเสบและเชื้อแบคทีเรีย', fn=['antiAcne', 'soothing'], aka=['ฟ้าทะลายโจร']),
    ext('Psidium Guajava Leaf Extract', 'สารสกัดใบฝรั่ง', 'สารสกัดใบฝรั่ง' + _TONE + _AOX, fn=['antioxidant', 'antiAcne'], aka=['Guava', 'ฝรั่ง']),
    ext('Pandanus Amaryllifolius Leaf Extract', 'สารสกัดใบเตย', 'สารสกัดใบเตย กลิ่นหอม' + _AOX, fn=['antioxidant', 'fragrance'], aka=['Pandan', 'ใบเตย']),
    ext('Terminalia Chebula Fruit Extract', 'สารสกัดสมอไทย', 'สมุนไพรที่มีแทนนินและกรดแกลลิก' + _AOX + _TONE, aka=['Chebulic Myrobalan', 'สมอไทย']),
    ext('Azadirachta Indica Leaf Extract', 'สารสกัดใบสะเดา', 'สารสกัดใบสะเดา ต้านเชื้อแบคทีเรียและเชื้อรา', fn=['antiAcne', 'soothing'], aka=['Neem', 'สะเดา']),
    ext('Ocimum Sanctum Leaf Extract', 'สารสกัดใบกะเพรา', 'สารสกัดกะเพรา (holy basil)' + _AOX + ' และต้านเชื้อ', fn=['antioxidant', 'antiAcne'], aka=['Holy Basil', 'กะเพรา']),
    ext('Citrus Hystrix Fruit Extract', 'สารสกัดมะกรูด', 'สารสกัดผลมะกรูด กลิ่นหอมสดชื่น', fn=['antioxidant', 'fragrance'], aka=['Kaffir Lime', 'มะกรูด'], use=(C, T), note='citrus'),
    ext('Citrus Aurantifolia Fruit Extract', 'สารสกัดมะนาว', 'สารสกัดผลมะนาว มีวิตามินซีและกรดผลไม้', fn=['antioxidant', 'exfoliant'], aka=['Lime', 'มะนาว'], use=(C, T)),
    ext('Mangifera Indica Fruit Extract', 'สารสกัดมะม่วง', 'สารสกัดผลมะม่วง มีวิตามินและแมงจิเฟอริน' + _AOX, aka=['Mango', 'มะม่วง']),
    ext('Momordica Charantia Fruit Extract', 'สารสกัดมะระ', 'สารสกัดมะระ' + _AOX, aka=['Bitter Melon', 'มะระ']),
    # ---------- Fruits & vegetables ----------
    ext('Euterpe Oleracea Fruit Extract', 'สารสกัดอาซาอิ', 'สารสกัดอาซาอิเบอร์รี่ มีแอนโทไซยานินสูง' + _AOX, aka=['Acai']),
    ext('Vaccinium Macrocarpon Fruit Extract', 'สารสกัดแครนเบอร์รี่', 'สารสกัดแครนเบอร์รี่' + _AOX, aka=['Cranberry']),
    ext('Vaccinium Angustifolium Fruit Extract', 'สารสกัดบลูเบอร์รี่', 'สารสกัดบลูเบอร์รี่' + _AOX, aka=['Blueberry']),
    ext('Rubus Fruticosus Fruit Extract', 'สารสกัดแบล็คเบอร์รี่', 'สารสกัดแบล็คเบอร์รี่' + _AOX, aka=['Blackberry']),
    ext('Fragaria Ananassa Fruit Extract', 'สารสกัดสตรอว์เบอร์รี่', 'สารสกัดสตรอว์เบอร์รี่ มีวิตามินซีและกรดผลไม้', fn=['antioxidant', 'exfoliant'], aka=['Strawberry']),
    ext('Actinidia Chinensis Fruit Extract', 'สารสกัดกีวี', 'สารสกัดกีวี มีวิตามินซี' + _BRIGHT, fn=['antioxidant', 'brightening'], aka=['Kiwi']),
    ext('Pyrus Malus Fruit Extract', 'สารสกัดแอปเปิล', 'สารสกัดแอปเปิล มีกรดมาลิกและโพลีฟีนอล', fn=['antioxidant', 'exfoliant'], aka=['Apple', 'แอปเปิล']),
    ext('Prunus Persica Fruit Extract', 'สารสกัดลูกพีช', 'สารสกัดลูกพีช' + _HYD, fn='humectant', aka=['Peach']),
    ext('Musa Sapientum Fruit Extract', 'สารสกัดกล้วย', 'สารสกัดกล้วย' + _HYD, fn='humectant', aka=['Banana', 'กล้วย']),
    ext('Cucumis Melo Fruit Extract', 'สารสกัดเมลอน', 'สารสกัดเมลอน มีเอนไซม์ SOD' + _AOX, aka=['Melon']),
    ext('Citrus Aurantium Dulcis Fruit Extract', 'สารสกัดส้ม', 'สารสกัดผลส้ม มีวิตามินซีและกรดผลไม้', fn=['antioxidant', 'brightening'], aka=['Orange', 'ส้ม']),
    ext('Citrus Reticulata Fruit Extract', 'สารสกัดส้มเขียวหวาน', 'สารสกัดส้มเขียวหวาน' + _AOX, aka=['Tangerine']),
    ext('Ficus Carica Fruit Extract', 'สารสกัดมะเดื่อฝรั่ง', 'สารสกัดลูกฟิก' + _HYD + _AOX, fn=['humectant', 'antioxidant'], aka=['Fig']),
    ext('Solanum Tuberosum Extract', 'สารสกัดมันฝรั่ง', 'สารสกัดมันฝรั่ง' + _SOOTHE, fn='soothing', aka=['Potato']),
    ext('Ipomoea Batatas Root Extract', 'สารสกัดมันเทศ', 'สารสกัดมันเทศ' + _AOX, aka=['Sweet Potato']),
    ext('Phaseolus Radiatus Seed Extract', 'สารสกัดถั่วเขียว', 'สารสกัดถั่วเขียว ใช้ในมาส์กและโฟมล้างหน้าเกาหลี' + _SOOTHE, fn='soothing', use=(C, M), aka=['Mung Bean', 'ถั่วเขียว']),
    ext('Spinacia Oleracea Leaf Extract', 'สารสกัดผักโขม', 'สารสกัดผักโขม' + _AOX, aka=['Spinach']),
    ext('Brassica Oleracea Italica Extract', 'สารสกัดบรอกโคลี', 'สารสกัดบรอกโคลี มีซัลโฟราเฟน' + _AOX, aka=['Broccoli']),
    ext('Beta Vulgaris Root Extract', 'สารสกัดบีทรูท', 'สารสกัดหัวบีท มีบีเทนธรรมชาติ' + _HYD, fn='humectant', aka=['Beet']),
    ext('Hordeum Vulgare Extract', 'สารสกัดข้าวบาร์เลย์', 'สารสกัดข้าวบาร์เลย์' + _SOOTHE, fn='soothing', aka=['Barley']),
    ext('Zea Mays Kernel Extract', 'สารสกัดข้าวโพด', 'สารสกัดเมล็ดข้าวโพด' + _HYD, fn='humectant', aka=['Corn']),
    ext('Vanilla Planifolia Fruit Extract', 'สารสกัดวานิลลา', 'สารสกัดฝักวานิลลา ให้กลิ่นหอม', fn=['fragrance', 'antioxidant'], aka=['Vanilla']),
    # ---------- Western botanicals ----------
    ext('Leontopodium Alpinum Extract', 'สารสกัดดอกเอเดลไวส์', 'สารสกัดดอกไม้บนเทือกเขาแอลป์' + _AOX, aka=['Edelweiss']),
    ext('Iris Florentina Root Extract', 'สารสกัดรากไอริส', 'สารสกัดรากไอริส' + _AOX, aka=['Orris']),
    ext('Rosa Canina Fruit Extract', 'สารสกัดผลโรสฮิป', 'สารสกัดผลกุหลาบป่า มีวิตามินซี' + _BRIGHT, fn=['antioxidant', 'brightening'], aka=['Rosehip']),
    ext('Sambucus Nigra Flower Extract', 'สารสกัดดอกเอลเดอร์', 'สารสกัดดอกเอลเดอร์' + _SOOTHE + _AOX, fn=['soothing', 'antioxidant'], aka=['Elderflower']),
    ext('Urtica Dioica Extract', 'สารสกัดตำแยฝรั่ง', 'สารสกัดตำแย ช่วยลดความมัน', fn=['antiAcne', 'antioxidant'], aka=['Nettle']),
    ext('Taraxacum Officinale Extract', 'สารสกัดแดนดิไลออน', 'สารสกัดแดนดิไลออน' + _AOX, aka=['Dandelion']),
    ext('Plantago Lanceolata Leaf Extract', 'สารสกัดใบหญ้าเอ็นยืด', 'สารสกัดพืชตระกูลหญ้าเอ็นยืด' + _SOOTHE, fn='soothing', aka=['Plantain']),
    ext('Symphytum Officinale Leaf Extract', 'สารสกัดใบคอมฟรีย์', 'สารสกัดคอมฟรีย์ มีอัลลันโทอินตามธรรมชาติ' + _SOOTHE, fn='soothing', aka=['Comfrey']),
    ext('Hypericum Perforatum Extract', 'สารสกัดเซนต์จอห์นสเวิร์ต', 'สารสกัดเซนต์จอห์นสเวิร์ต' + _SOOTHE, fn='soothing', aka=["St John's Wort"],
        note=('อาจทำให้ผิวไวต่อแสง', 'May increase sun sensitivity')),
    ext('Melissa Officinalis Leaf Extract', 'สารสกัดใบเลมอนบาล์ม', 'สารสกัดเลมอนบาล์ม' + _SOOTHE + _AOX, fn=['soothing', 'antioxidant'], aka=['Lemon Balm']),
    ext('Ocimum Basilicum Leaf Extract', 'สารสกัดใบโหระพา', 'สารสกัดโหระพา' + _AOX, aka=['Basil', 'โหระพา']),
    ext('Origanum Vulgare Leaf Extract', 'สารสกัดออริกาโน', 'สารสกัดออริกาโน ต้านเชื้อแบคทีเรีย', fn=['antiAcne', 'antioxidant'], aka=['Oregano']),
    ext('Cinnamomum Cassia Bark Extract', 'สารสกัดอบเชยจีน', 'สารสกัดเปลือกอบเชย ต้านเชื้อแบคทีเรีย', fn=['antiAcne', 'fragrance'], aka=['Cinnamon', 'อบเชย'], note='allergen'),
    ext('Lavandula Angustifolia Flower Extract', 'สารสกัดดอกลาเวนเดอร์', 'สารสกัดดอกลาเวนเดอร์' + _SOOTHE, fn=['soothing', 'fragrance'], aka=['Lavender']),
    ext('Rosa Damascena Flower Extract', 'สารสกัดดอกกุหลาบ', 'สารสกัดดอกกุหลาบดามัสก์' + _SOOTHE + _AOX, fn=['soothing', 'antioxidant'], aka=['Rose', 'กุหลาบ']),
    ext('Jasminum Officinale Flower Extract', 'สารสกัดดอกมะลิ', 'สารสกัดดอกมะลิ' + _SOOTHE, fn=['soothing', 'fragrance'], aka=['Jasmine', 'มะลิ']),
    ext('Chrysanthemum Indicum Flower Extract', 'สารสกัดดอกเก๊กฮวย', 'สารสกัดดอกเก๊กฮวย' + _SOOTHE + _AOX, fn=['soothing', 'antioxidant'], aka=['Chrysanthemum', 'เก๊กฮวย']),
    ext('Helianthus Annuus Seed Extract', 'สารสกัดเมล็ดทานตะวัน', 'สารสกัดเมล็ดทานตะวัน' + _AOX, aka=['Sunflower']),
    ext('Hedera Helix Extract', 'สารสกัดไอวี่', 'สารสกัดไอวี่ ช่วยลดบวม', fn='soothing', aka=['Ivy']),
    ext('Ruscus Aculeatus Root Extract', 'สารสกัดรากบุชเชอร์บรูม', 'สารสกัดที่ช่วยการไหลเวียนและลดบวม นิยมในอายครีม', fn='soothing', aka=["Butcher's Broom"]),
    ext('Aesculus Hippocastanum Seed Extract', 'สารสกัดเมล็ดเกาลัดม้า', 'สารสกัดที่มีเอสซิน ช่วยลดบวมและเสริมหลอดเลือดฝอย', fn='soothing', aka=['Horse Chestnut']),
    ext('Centaurea Cyanus Flower Water', 'น้ำดอกคอร์นฟลาวเวอร์', 'น้ำกลั่นดอกคอร์นฟลาวเวอร์' + _SOOTHE + ' นิยมใช้รอบดวงตา', fn='soothing', use=(T, E), aka=['Cornflower']),
    ext('Tilia Cordata Flower Extract', 'สารสกัดดอกลินเดน', 'สารสกัดดอกลินเดน' + _SOOTHE, fn='soothing', aka=['Linden']),
    ext('Achillea Millefolium Extract', 'สารสกัดยาร์โรว์', 'สารสกัดยาร์โรว์' + _SOOTHE + _TONE, fn=['soothing', 'antiAcne'], aka=['Yarrow']),
    ext('Vitex Agnus-Castus Extract', 'สารสกัดไวเท็กซ์', 'สารสกัดไวเท็กซ์ ใช้ในผลิตภัณฑ์สำหรับสิวฮอร์โมน', fn='antiAcne', aka=['Chasteberry']),
    ext('Pinus Palustris Leaf Extract', 'สารสกัดใบสน', 'สารสกัดใบสน' + _AOX, aka=['Pine Needle']),
    ext('Eclipta Prostrata Extract', 'สารสกัดกะเม็ง', 'สารสกัดกะเม็ง สมุนไพรบำรุงผมและผิว' + _AOX, aka=['กะเม็ง']),
    ext('Theobroma Cacao Seed Extract', 'สารสกัดเมล็ดโกโก้', 'สารสกัดเมล็ดโกโก้ มีฟลาโวนอยด์' + _AOX, aka=['Cocoa']),
    # ---------- More essential oils ----------
    eo('Pogostemon Cablin Oil', 'น้ำมันพิมเสนต้น (แพทชูลี่)', 'ใบแพทชูลี่ กลิ่นหอมเข้มแบบดิน', aka=['Patchouli Oil']),
    eo('Salvia Sclarea Oil', 'น้ำมันแคลรี่เสจ', 'แคลรี่เสจ', aka=['Clary Sage Oil']),
    eo('Cupressus Sempervirens Oil', 'น้ำมันไซเปรส', 'ต้นไซเปรส', aka=['Cypress Oil']),
    eo('Juniperus Communis Fruit Oil', 'น้ำมันจูนิเปอร์เบอร์รี่', 'ผลจูนิเปอร์', aka=['Juniper Oil']),
    eo('Citrus Nobilis Peel Oil', 'น้ำมันผิวส้มแมนดาริน', 'ผิวส้มแมนดาริน', aka=['Mandarin Oil'], note='citrus'),
    eo('Anthemis Nobilis Flower Oil', 'น้ำมันโรมันคาโมมายล์', 'ดอกโรมันคาโมมายล์', aka=['Roman Chamomile Oil']),
    eo('Chamomilla Recutita Flower Oil', 'น้ำมันคาโมมายล์เยอรมัน', 'ดอกคาโมมายล์เยอรมัน มีคามาซูลีนสีน้ำเงิน', aka=['Blue Chamomile Oil']),
    eo('Leptospermum Scoparium Branch/Leaf Oil', 'น้ำมันมานูก้า', 'ต้นมานูก้าของนิวซีแลนด์ ต้านเชื้อแบคทีเรีย', aka=['Manuka Oil'], fn=['antiAcne', 'fragrance']),
    eo('Origanum Vulgare Leaf Oil', 'น้ำมันออริกาโน', 'ใบออริกาโน ฤทธิ์แรง', aka=['Oregano Oil']),
    eo('Thymus Vulgaris Oil', 'น้ำมันไธม์', 'ไธม์ มีไทมอล', aka=['Thyme Oil']),
    eo('Ocimum Basilicum Oil', 'น้ำมันโหระพา', 'โหระพา', aka=['Basil Oil']),
    eo('Vetiveria Zizanoides Root Oil', 'น้ำมันแฝกหอม', 'รากหญ้าแฝก กลิ่นหอมเย็นแบบดิน', aka=['Vetiver Oil', 'แฝกหอม']),
    eo('Litsea Cubeba Fruit Oil', 'น้ำมันตะไคร้ต้น', 'ผลตะไคร้ต้น มีซิทรัลสูง', aka=['May Chang Oil', 'ตะไคร้ต้น']),
    eo('Zingiber Officinale Root Oil', 'น้ำมันขิง', 'เหง้าขิง', aka=['Ginger Oil', 'ขิง']),
    eo('Mentha Spicata Leaf Oil', 'น้ำมันสเปียร์มินต์', 'ใบสเปียร์มินต์', aka=['Spearmint Oil'], note='menthol'),
    eo('Mentha Arvensis Leaf Oil', 'น้ำมันสะระแหน่', 'ใบสะระแหน่ญี่ปุ่น มีเมนทอลสูง', aka=['Cornmint Oil', 'สะระแหน่'], note='menthol'),
    eo('Lavandula Hybrida Oil', 'น้ำมันลาวานดิน', 'ลาวานดิน (ลาเวนเดอร์ลูกผสม)', aka=['Lavandin Oil']),
    eo('Cinnamomum Camphora Bark Oil', 'น้ำมันการบูร', 'ไม้การบูร', aka=['Camphor Oil'], note='menthol'),
    eo('Michelia Alba Flower Oil', 'น้ำมันดอกจำปี', 'ดอกจำปี กลิ่นหอมหวาน', aka=['White Champaca', 'จำปี']),
    eo('Aquilaria Agallocha Wood Oil', 'น้ำมันกฤษณา', 'ไม้กฤษณา กลิ่นหอมลึกแบบไม้', aka=['Agarwood', 'Oud', 'กฤษณา']),
]
