"""More actives: vitamins, amino acids, peptides, brightening, soothing, antioxidants."""
from common import ALL, C, E, I, M, S, T

_AA = 'กรดอะมิโนชนิดหนึ่ง เป็นส่วนหนึ่งของสารชุ่มชื้นตามธรรมชาติของผิว (NMF) ช่วยให้ผิวชุ่มชื้นและแข็งแรง มักใส่รวมกันเป็นชุดกรดอะมิโน'
_PEP = 'เปปไทด์ (กรดอะมิโนหลายตัวต่อกัน) ที่ทำหน้าที่ส่งสัญญาณให้เซลล์ผิว'
_PEP_TIPS = 'อ่อนโยน ใช้ได้ทั้งเช้าเย็นและร่วมกับสารอื่นได้ ผลลัพธ์ค่อยเป็นค่อยไป'
_VITC = 'อนุพันธ์วิตามินซีที่คงตัวกว่ารูปแบบบริสุทธิ์ ช่วยต้านอนุมูลอิสระ ลดจุดด่างดำ และสนับสนุนการสร้างคอลลาเจน แต่ฤทธิ์อ่อนกว่า'
_FLAV = 'ฟลาโวนอยด์จากพืช ต้านอนุมูลอิสระและลดการอักเสบ'
_EYE = ' นิยมในอายครีมเพื่อช่วยลดถุงใต้ตาและรอยคล้ำ'

ROWS = [
    # ---------- Amino acids ----------
    I('Valine', 'วาลีน', 'humectant', [M, E], _AA, en='Amino acid (NMF)', smi='CC(C)C(N)C(=O)O', f='C5H11NO2'),
    I('Leucine', 'ลิวซีน', 'humectant', [M, E], _AA, en='Amino acid', smi='CC(C)CC(N)C(=O)O', f='C6H13NO2'),
    I('Isoleucine', 'ไอโซลิวซีน', 'humectant', [M, E], _AA, en='Amino acid', smi='CCC(C)C(N)C(=O)O', f='C6H13NO2'),
    I('Phenylalanine', 'ฟีนิลอะลานีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(Cc1ccccc1)C(=O)O', f='C9H11NO2'),
    I('Tyrosine', 'ไทโรซีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(Cc1ccc(O)cc1)C(=O)O', f='C9H11NO3'),
    I('Cysteine', 'ซิสเทอีน', ['humectant', 'antioxidant'], [M, E], _AA + ' มีหมู่กำมะถันที่ต้านอนุมูลอิสระ', en='Sulfur amino acid',
      smi='NC(CS)C(=O)O', f='C3H7NO2S'),
    I('Methionine', 'เมไทโอนีน', 'humectant', [M, E], _AA, en='Amino acid', smi='CSCCC(N)C(=O)O', f='C5H11NO2S'),
    I('Tryptophan', 'ทริปโตเฟน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(Cc1c[nH]c2ccccc12)C(=O)O', f='C11H12N2O2'),
    I('Asparagine', 'แอสพาราจีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(=O)CC(N)C(=O)O', f='C4H8N2O3'),
    I('Glutamine', 'กลูตามีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(=O)CCC(N)C(=O)O', f='C5H10N2O3'),
    I('Hydroxyproline', 'ไฮดรอกซีโพรลีน', ['humectant', 'antiAging'], [M, E], _AA + ' และเป็นองค์ประกอบเฉพาะของคอลลาเจน', en='Collagen amino acid',
      smi='OC1CNC(C1)C(=O)O', f='C5H9NO3'),
    I('Ornithine', 'ออร์นิทีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NCCCC(N)C(=O)O', f='C5H12N2O2'),
    I('Citrulline', 'ซิทรูลลีน', 'humectant', [M, E], _AA, en='Amino acid', smi='NC(=O)NCCCC(N)C(=O)O', f='C6H13N3O3'),
    I('Sarcosine', 'ซาร์โคซีน', ['antiAcne', 'humectant'], [E, T], 'กรดอะมิโนอนุพันธ์ที่ช่วยควบคุมความมัน', en='Oil-balancing amino acid',
      smi='CNCC(=O)O', f='C3H7NO2'),
    I('Capryloyl Glycine', 'แคพรีโลอิลไกลซีน', ['antiAcne', 'preservative'], [E, T, C], 'กรดอะมิโนที่จับกับกรดไขมันสายกลาง ช่วยควบคุมความมันและต้านเชื้อแบคทีเรีย',
      en='Sebum-regulating lipoamino acid', smi='CCCCCCCC(=O)NCC(=O)O', f='C10H19NO3'),
    I('Magnesium PCA', 'แมกนีเซียมพีซีเอ', 'humectant', [M, T], 'เกลือแมกนีเซียมของ PCA ให้ความชุ่มชื้นและแร่ธาตุแก่ผิว', en='Hydrating mineral salt'),
    I('Copper PCA', 'คอปเปอร์พีซีเอ', ['antiAcne', 'antiAging'], [E, T], 'เกลือทองแดงของ PCA ช่วยต้านเชื้อแบคทีเรียและสนับสนุนการสร้างคอลลาเจน', en='Copper salt'),
    I('Methylsulfonylmethane', 'เอ็มเอสเอ็ม', 'soothing', [M, E], 'สารประกอบกำมะถันอินทรีย์ที่ช่วยลดการอักเสบ', aka=['MSM', 'Dimethyl Sulfone'],
      en='MSM, soothing sulfur compound', smi='CS(C)(=O)=O', f='C2H6O2S'),
    # ---------- Vitamins & derivatives ----------
    I('Sodium Ascorbate', 'โซเดียมแอสคอร์เบต', ['antioxidant', 'brightening'], [E, M], 'เกลือโซเดียมของวิตามินซี ต้านอนุมูลอิสระ แต่เสื่อมได้ง่ายเหมือนวิตามินซีบริสุทธิ์',
      aka=['Vitamin C', 'วิตามินซี'], en='Vitamin C salt', smi='OCC(O)C1OC(=O)C(O)=C1[O-].[Na+]', f='C6H7NaO6'),
    I('Aminopropyl Ascorbyl Phosphate', 'อะมิโนโพรพิลแอสคอร์บิลฟอสเฟต', ['antioxidant', 'brightening'], [E, M], _VITC, aka=['Vitamin C', 'วิตามินซี'],
      en='Stable vitamin C derivative'),
    I('Ascorbyl Methylsilanol Pectinate', 'แอสคอร์บิลเมทิลไซลานอลเพคติเนต', ['antioxidant', 'brightening'], [E], _VITC, aka=['Vitamin C'],
      en='Vitamin C derivative', kind='polymer'),
    I('Retinyl Linoleate', 'เรตินิลไลโนลีเอต', 'retinoid', [M, E], 'เอสเทอร์ของเรตินอลกับกรดไลโนเลอิก อ่อนโยน ผิวค่อยๆ เปลี่ยนเป็นเรตินอล', aka=['Vitamin A'],
      en='Gentle retinyl ester', smi='CC1=C(C(C)(C)CCC1)/C=C/C(C)=C/C=C/C(C)=C/COC(=O)CCCCCCC/C=C\\C/C=C\\CCCCC', f='C38H60O2'),
    I('Retinyl Retinoate', 'เรตินิลเรติโนเอต', 'retinoid', [E, M], 'เรตินอยด์ลูกผสม (เรตินอล + กรดเรติโนอิก) พัฒนาในเกาหลี คงตัวกว่าเรตินอล', aka=['Vitamin A'],
      note='retinoid', en='Retinol–retinoic acid hybrid'),
    I('Tocopheryl Linoleate', 'โทโคฟีริลไลโนลีเอต', 'antioxidant', [M], 'วิตามินอีจับกับกรดไลโนเลอิก ต้านอนุมูลอิสระและบำรุงเกราะผิว', aka=['Vitamin E'],
      en='Vitamin E ester'),
    I('Tocotrienols', 'โทโคไทรอีนอล', 'antioxidant', [M, E], 'วิตามินอีอีกกลุ่มหนึ่ง (จากน้ำมันปาล์ม/รำข้าว) ต้านอนุมูลอิสระได้แรง', aka=['Vitamin E'],
      en='Tocotrienol vitamin E', kind='mixture'),
    I('Tocopheryl Glucoside', 'โทโคฟีริลกลูโคไซด์', 'antioxidant', [M, E], 'วิตามินอีที่ละลายน้ำได้ ใส่ในเซรั่มน้ำได้', aka=['Vitamin E'], en='Water-soluble vitamin E'),
    I('Thiamine HCl', 'ไทอามีน (วิตามินบี 1)', 'other', [M], 'วิตามินบี 1 ช่วยบำรุงผิว', aka=['Vitamin B1'], en='Vitamin B1'),
    I('Riboflavin', 'ไรโบฟลาวิน (วิตามินบี 2)', ['antioxidant', 'colorant'], [M], 'วิตามินบี 2 สีเหลือง ต้านอนุมูลอิสระ', aka=['Vitamin B2'], en='Vitamin B2',
      smi='Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(CC(O)C(O)C(O)CO)c2cc1C', f='C17H20N4O6'),
    I('Cyanocobalamin', 'ไซยาโนโคบาลามิน (วิตามินบี 12)', ['soothing', 'colorant'], [M, E], 'วิตามินบี 12 สีชมพูแดง ช่วยปลอบประโลมผิวอักเสบ', aka=['Vitamin B12'],
      en='Vitamin B12'),
    I('Folic Acid', 'กรดโฟลิก (วิตามินบี 9)', 'antiAging', [M, E], 'วิตามินบี 9 สนับสนุนการสร้างเซลล์ผิวใหม่', aka=['Vitamin B9'], en='Vitamin B9',
      smi='Nc1nc2ncc(CNc3ccc(cc3)C(=O)NC(CCC(=O)O)C(=O)O)nc2c(=O)[nH]1', f='C19H19N7O6'),
    I('Calcium Pantothenate', 'แคลเซียมแพนโทเทเนต', ['soothing', 'humectant'], [M, C], 'เกลือของวิตามินบี 5 ให้ความชุ่มชื้นและปลอบประโลมผิว', aka=['Vitamin B5'],
      en='Vitamin B5 salt'),
    I('Panthenyl Ethyl Ether', 'แพนทีนิลเอทิลอีเทอร์', ['soothing', 'humectant'], [M, C], 'อนุพันธ์ของแพนทีนอล ให้ความชุ่มชื้น', aka=['Vitamin B5'],
      en='Panthenol derivative', smi='CCOCCCNC(=O)C(O)C(C)(C)CO', f='C11H23NO4'),
    I('Nicotinamide Mononucleotide', 'เอ็นเอ็มเอ็น', 'antiAging', [E], 'สารตั้งต้นของ NAD+ ที่เกี่ยวกับพลังงานเซลล์ นิยมในผลิตภัณฑ์ชะลอวัย หลักฐานการทาภายนอกยังจำกัด',
      aka=['NMN'], en='NAD+ precursor (limited topical evidence)'),
    # ---------- Peptides ----------
    I('Acetyl Tetrapeptide-5', 'อะซิทิลเตตระเปปไทด์-5', 'antiAging', [E, M], _PEP + _EYE, tips=_PEP_TIPS, aka=['peptide', 'Eyeseryl'],
      en='Eye-puffiness peptide', kind='peptide'),
    I('Acetyl Tetrapeptide-9', 'อะซิทิลเตตระเปปไทด์-9', 'antiAging', [E], _PEP + ' กระตุ้นการสร้างคอลลาเจน', tips=_PEP_TIPS, aka=['peptide'],
      en='Collagen peptide', kind='peptide'),
    I('Acetyl Tetrapeptide-11', 'อะซิทิลเตตระเปปไทด์-11', 'antiAging', [E], _PEP + ' ช่วยความแน่นของผิว', tips=_PEP_TIPS, aka=['peptide'],
      en='Firming peptide', kind='peptide'),
    I('Tripeptide-1', 'ไตรเปปไทด์-1', 'antiAging', [E], _PEP + ' (GHK) ช่วยฟื้นฟูผิว', tips=_PEP_TIPS, aka=['peptide', 'GHK'], en='GHK peptide', kind='peptide'),
    I('Hexapeptide-9', 'เฮกซะเปปไทด์-9', 'antiAging', [E], _PEP + ' กระตุ้นการสร้างคอลลาเจน', tips=_PEP_TIPS, aka=['peptide'], en='Collagen peptide', kind='peptide'),
    I('Hexapeptide-11', 'เฮกซะเปปไทด์-11', 'antiAging', [E], _PEP + ' ช่วยความยืดหยุ่นของผิว', tips=_PEP_TIPS, aka=['peptide'], en='Elasticity peptide', kind='peptide'),
    I('Palmitoyl Dipeptide-7', 'ปาล์มิทอยล์ไดเปปไทด์-7', 'antiAging', [E], _PEP + ' ลดริ้วรอย', tips=_PEP_TIPS, aka=['peptide'], en='Anti-wrinkle peptide', kind='peptide'),
    I('Palmitoyl Oligopeptide', 'ปาล์มิทอยล์โอลิโกเปปไทด์', 'antiAging', [E, M], _PEP + ' กระตุ้นการสร้างคอลลาเจน', tips=_PEP_TIPS, aka=['peptide'],
      en='Collagen peptide', kind='peptide'),
    I('Palmitoyl Tripeptide-8', 'ปาล์มิทอยล์ไตรเปปไทด์-8', 'soothing', [E, M], _PEP + ' ลดการอักเสบและรอยแดง', tips=_PEP_TIPS, aka=['peptide'],
      en='Soothing peptide', kind='peptide'),
    I('Acetyl Dipeptide-1 Cetyl Ester', 'อะซิทิลไดเปปไทด์-1 ซีทิลเอสเทอร์', 'soothing', [M], _PEP + ' ลดความรู้สึกแสบร้อนในผิวแพ้ง่าย', tips=_PEP_TIPS,
      aka=['peptide'], en='Anti-sensitivity peptide', kind='peptide'),
    I('Dipeptide-2', 'ไดเปปไทด์-2', 'antiAging', [E], _PEP + _EYE, tips=_PEP_TIPS, aka=['peptide'], en='Eye peptide', kind='peptide'),
    I('Nonapeptide-1', 'โนนะเปปไทด์-1', 'brightening', [E], _PEP + ' ยับยั้งสัญญาณกระตุ้นการสร้างเม็ดสี ช่วยให้ผิวกระจ่างใส', tips=_PEP_TIPS, aka=['peptide', 'Melanostatine'],
      en='Brightening peptide', kind='peptide'),
    I('Oligopeptide-68', 'โอลิโกเปปไทด์-68', 'brightening', [E], _PEP + ' ช่วยลดการสร้างเม็ดสี', tips=_PEP_TIPS, aka=['peptide'], en='Brightening peptide', kind='peptide'),
    I('Tetrapeptide-30', 'เตตระเปปไทด์-30', 'brightening', [E], _PEP + ' ช่วยให้สีผิวสม่ำเสมอ', tips=_PEP_TIPS, aka=['peptide'], en='Brightening peptide', kind='peptide'),
    I('Decapeptide-12', 'เดคะเปปไทด์-12', 'brightening', [E], _PEP + ' ยับยั้งไทโรซิเนส', tips=_PEP_TIPS, aka=['peptide'], en='Brightening peptide', kind='peptide'),
    I('Trifluoroacetyl Tripeptide-2', 'ไตรฟลูออโรอะซิทิลไตรเปปไทด์-2', 'antiAging', [E], _PEP + ' ช่วยความกระชับ', tips=_PEP_TIPS, aka=['peptide'],
      en='Firming peptide', kind='peptide'),
    I('sh-Oligopeptide-2', 'ไอจีเอฟ (โอลิโกเปปไทด์-2)', 'antiAging', [E], 'ปัจจัยการเจริญเติบโตชนิด IGF ผลิตด้วยเทคโนโลยีชีวภาพ', aka=['IGF', 'growth factor'],
      en='Growth factor', kind='protein'),
    I('sh-Decapeptide-7', 'เดคะเปปไทด์-7', 'antiAging', [E], 'โปรตีนเทคโนโลยีชีวภาพที่เลียนแบบปัจจัยการเจริญเติบโต', aka=['growth factor'], en='Growth factor peptide',
      kind='protein'),
    # ---------- Eye-area actives ----------
    I('Hesperidin Methyl Chalcone', 'เฮสเพอริดินเมทิลชาลโคน', ['antioxidant', 'soothing'], [E, M], 'สารจากผิวส้มที่ช่วยเรื่องการไหลเวียน' + _EYE, en='Under-eye circulation helper'),
    I('N-Hydroxysuccinimide', 'เอ็น-ไฮดรอกซีซัคซินิไมด์', 'brightening', [E], 'ช่วยกำจัดเม็ดสีที่เกิดจากเลือดคั่ง' + _EYE, aka=['Haloxyl'], en='Dark-circle active',
      smi='ON1C(=O)CCC1=O', f='C4H5NO3'),
    I('Chrysin', 'ไครซิน', 'antioxidant', [E], _FLAV + _EYE, en='Flavonoid for dark circles', smi='O=c1cc(-c2ccccc2)oc2cc(O)cc(O)c12', f='C15H10O4'),
    I('Escin', 'เอสซิน', 'soothing', [E, M], 'สารจากเมล็ดเกาลัดม้า ช่วยลดบวมและสนับสนุนหลอดเลือดฝอย' + _EYE, aka=['Aescin'], en='Anti-puffiness saponin'),
    # ---------- Brightening ----------
    I('Cetyl Tranexamate Mesylate', 'ซีทิลทราเนซาเมตเมซิเลต', 'brightening', [E, M], 'อนุพันธ์ของกรดทราเนซามิกที่ซึมผ่านผิวได้ดีขึ้น ช่วยลดฝ้าและรอยดำ', aka=['TXA'],
      en='Penetrating tranexamic acid derivative'),
    I('Diacetyl Boldine', 'ไดอะซิทิลโบลดีน', 'brightening', [E], 'สารจากต้นโบลโด ช่วยลดการสร้างเม็ดสี', aka=['Lumiskin'], en='Pigment-regulating active'),
    I('Galactoarabinan', 'กาแลคโตอาราบิแนน', ['exfoliant', 'humectant'], [E, T], 'พอลิแซ็กคาไรด์จากต้นสน ช่วยเสริมการผลัดเซลล์ของกรดและให้ความชุ่มชื้น', en='Larch polysaccharide',
      kind='polymer'),
    I('Resorcinol', 'รีซอร์ซินอล', ['antiAcne', 'exfoliant'], [C], 'สารผลัดเซลล์และฆ่าเชื้อที่ใช้ในผลิตภัณฑ์สิวรุ่นเก่า', note='sensitize', en='Older acne/peeling agent',
      smi='Oc1cccc(O)c1', f='C6H6O2'),
    I('Methyl Gentisate', 'เมทิลเจนทิเซต', 'brightening', [E], 'สารลดการสร้างเม็ดสีจากรากพืชเจนเชียน', en='Gentian-derived brightener',
      smi='COC(=O)c1cc(O)ccc1O', f='C8H8O4'),
    # ---------- Antioxidants ----------
    I('Hesperidin', 'เฮสเพอริดิน', 'antioxidant', [E, M], _FLAV + ' จากผิวส้ม', en='Citrus flavonoid'),
    I('Rutin', 'รูติน', 'antioxidant', [E, M], _FLAV + ' ช่วยความแข็งแรงของหลอดเลือดฝอย', en='Flavonoid'),
    I('Baicalin', 'ไบคาลิน', ['antioxidant', 'soothing'], [E, T], _FLAV + ' จากรากแบคคาล สคัลแคป', en='Skullcap flavonoid'),
    I('Apigenin', 'อะพิจีนิน', ['antioxidant', 'soothing'], [E, M], _FLAV + ' พบมากในคาโมมายล์', en='Chamomile flavonoid',
      smi='O=c1cc(-c2ccc(O)cc2)oc2cc(O)cc(O)c12', f='C15H10O5'),
    I('Luteolin', 'ลูทีโอลิน', ['antioxidant', 'soothing'], [E], _FLAV, en='Flavonoid', smi='O=c1cc(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12', f='C15H10O6'),
    I('Silymarin', 'ซิลิมาริน', 'antioxidant', [E], 'กลุ่มสารต้านอนุมูลอิสระจากเมล็ดมิลค์ทิสเซิล', aka=['Milk Thistle'], en='Milk thistle antioxidants', kind='mixture'),
    I('Lycopene', 'ไลโคปีน', 'antioxidant', [E, M], 'แคโรทีนอยด์สีแดงจากมะเขือเทศ ต้านอนุมูลอิสระ', en='Tomato carotenoid',
      smi='CC(C)=CCC/C(C)=C/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C=C(C)/CCC=C(C)C', f='C40H56'),
    I('Lutein', 'ลูทีน', 'antioxidant', [E, M], 'แคโรทีนอยด์สีเหลือง ช่วยกรองแสงสีฟ้าและต้านอนุมูลอิสระ', en='Blue-light filtering carotenoid'),
    I('Fullerenes', 'ฟูลเลอรีน', 'antioxidant', [E], 'โมเลกุลคาร์บอนทรงกลม (C60) ที่ดักจับอนุมูลอิสระได้มาก', en='C60 antioxidant', kind='mineral', f='C60'),
    I('Ethyl Ferulate', 'เอทิลเฟรูเลต', 'antioxidant', [E, S], 'อนุพันธ์ของกรดเฟรูลิกที่ละลายในน้ำมัน', en='Oil-soluble ferulic ester',
      smi='CCOC(=O)/C=C/c1ccc(O)c(OC)c1', f='C12H14O4'),
    I('Bis-Ethylhexyl Hydroxydimethoxy Benzylmalonate', 'บิสเอทิลเฮกซิลไฮดรอกซีไดเมทอกซีเบนซิลมาโลเนต', ['antioxidant', 'other'], [S],
      'สารต้านอนุมูลอิสระที่ช่วยให้สูตรกันแดดคงตัว', aka=['RonaCare AP'], en='Photostabilising antioxidant'),
    I('Polypodium Leucotomos Extract', 'สารสกัดเฟิร์นโพลีโพเดียม', 'antioxidant', [E, S], 'สารสกัดเฟิร์นที่มีงานวิจัยว่าช่วยปกป้องผิวจากแสงแดด', en='Photoprotective fern',
      kind='extract'),
    I('Pinus Pinaster Bark Extract', 'สารสกัดเปลือกสนทะเล', 'antioxidant', [E, M], 'สารสกัดเปลือกสน (pycnogenol) มีโพรแอนโทไซยานิดินต้านอนุมูลอิสระสูง',
      aka=['Pycnogenol'], en='Pine bark antioxidant', kind='extract'),
    I('Vitis Vinifera Seed Extract', 'สารสกัดเมล็ดองุ่น', 'antioxidant', [E, M], 'สารสกัดเมล็ดองุ่น มีโพรแอนโทไซยานิดิน', aka=['Grape Seed Extract'],
      en='Grape seed antioxidant', kind='extract'),
    # ---------- Soothing synthetics ----------
    I('Hydroxyphenyl Propamidobenzoic Acid', 'ไฮดรอกซีฟีนิลโพรพามิโดเบนโซอิกแอซิด', 'soothing', [M, E], 'สารสังเคราะห์เลียนแบบสารในข้าวโอ๊ต (อเวแนนทราไมด์) ลดอาการคันและรอยแดง',
      aka=['SymCalmin'], en='Oat-like anti-itch active', smi='OC(=O)c1ccccc1NC(=O)CCc1ccc(O)cc1', f='C16H15NO4'),
    I('4-t-Butylcyclohexanol', 'บิวทิลไซโคลเฮกซานอล', 'soothing', [M, E], 'สารที่ลดความรู้สึกแสบร้อนและคันในผิวแพ้ง่าย', aka=['SymSitive'],
      en='Anti-stinging active', smi='CC(C)(C)C1CCC(O)CC1', f='C10H20O'),
    I('Avenanthramides', 'อเวแนนทราไมด์', 'soothing', [M], 'สารสำคัญในข้าวโอ๊ตที่ลดอาการคันและการอักเสบ', en='Oat anti-itch actives', kind='mixture'),
    I('Stearyl Glycyrrhetinate', 'สเตียริลไกลไซร์เรทิเนต', 'soothing', [M, S], 'อนุพันธ์จากชะเอมที่ละลายในน้ำมัน ลดการระคายเคือง', aka=['licorice'], en='Licorice anti-irritant'),
    I('Copper Gluconate', 'คอปเปอร์กลูโคเนต', ['soothing', 'antiAcne'], [E, T], 'เกลือทองแดงที่ช่วยต้านเชื้อและสมานผิว', en='Copper salt'),
    I('Magnesium Aspartate', 'แมกนีเซียมแอสพาร์เตต', 'soothing', [M, E], 'เกลือแร่แมกนีเซียมที่ช่วยเรื่องพลังงานเซลล์และความชุ่มชื้น', en='Magnesium salt'),
    I('Sea Water', 'น้ำทะเล', ['humectant', 'soothing'], [T, M], 'น้ำทะเลที่ผ่านการกรอง มีแร่ธาตุหลายชนิด', aka=['Maris Aqua'], en='Mineral-rich sea water', kind='mineral'),
    I('Hydrolyzed Algin', 'อัลจินไฮโดรไลซ์', ['humectant', 'soothing'], [M, E], 'สารจากสาหร่ายสีน้ำตาลที่ย่อยแล้ว ให้ความชุ่มชื้น', en='Algae hydrator', kind='polymer'),
]
