"""Brightening / anti-pigmentation actives."""
from common import C, E, I, M, S, T

_TYR = 'ยับยั้งเอนไซม์ไทโรซิเนส (tyrosinase) ที่ใช้สร้างเม็ดสีเมลานิน'
_SPOTS = 'ช่วยให้ฝ้า กระ จุดด่างดำ และรอยดำจากสิวดูจางลง ผิวกระจ่างใสสม่ำเสมอ'
_SPOT_TIPS = 'ต้องใช้ต่อเนื่องอย่างน้อย 8–12 สัปดาห์ และทากันแดดทุกวัน มิฉะนั้นรอยดำจะกลับมา'

ROWS = [
    I('Niacinamide', 'ไนอะซินาไมด์ (วิตามินบี 3)', ['brightening', 'barrier', 'antiAcne'], [C, S, M, E, T],
      'วิตามินบี 3 รูปแบบที่ละลายน้ำ คงตัวดี เป็นหนึ่งในสารบำรุงผิวที่มีงานวิจัยรองรับมากที่สุด',
      good='ลดการส่งเม็ดสีไปยังผิวชั้นบน (ทำให้รอยดำจาง) ช่วยสร้างเซราไมด์เสริมเกราะผิว ควบคุมความมัน ลดรอยแดงและรูขุมขนดูเล็กลง',
      tips='ความเข้มข้น 2–5% ได้ผลดีและอ่อนโยน ความเข้มข้นสูง 10–20% อาจทำให้แดงหรือคันในบางคน ใช้คู่กับสารอื่นได้แทบทุกตัว',
      aka=['Vitamin B3', 'วิตามินบี 3', 'B3', 'Nicotinamide'], en='Versatile vitamin B3: brightening, barrier, oil control',
      smi='NC(=O)c1cccnc1', f='C6H6N2O'),
    I('Tranexamic Acid', 'กรดทราเนซามิก', 'brightening', [E, M],
      'อนุพันธ์ของกรดอะมิโนไลซีน เดิมใช้เป็นยาห้ามเลือด ต่อมาพบว่าช่วยลดฝ้า',
      good='ลดการกระตุ้นเซลล์สร้างเม็ดสีจากการอักเสบและแสงแดด เด่นเรื่องฝ้าและรอยแดง/ดำหลังสิว', tips='อ่อนโยน ใช้ได้ทั้งเช้าเย็น ใช้คู่กับไนอะซินาไมด์ได้ดี ' + _SPOT_TIPS,
      aka=['TXA'], en='Gentle anti-melasma active', smi='NCC1CCC(CC1)C(=O)O', f='C8H15NO2'),
    I('Alpha-Arbutin', 'อัลฟาอาร์บูติน', 'brightening', [E, M], 'สารที่พบในพืชตระกูลแบร์เบอร์รี่ สังเคราะห์ให้ได้รูปแบบอัลฟาที่ออกฤทธิ์ดีกว่าอาร์บูตินธรรมดา',
      good=_TYR + ' ' + _SPOTS, tips='ใช้ความเข้มข้นไม่เกิน 2% ในหน้า ' + _SPOT_TIPS, aka=['arbutin', 'อาร์บูติน'],
      en='Tyrosinase-inhibiting brightener', smi='OCC1OC(Oc2ccc(O)cc2)C(O)C(O)C1O', f='C12H16O7'),
    I('Arbutin', 'อาร์บูติน', 'brightening', [E, M], 'สารจากธรรมชาติในใบแบร์เบอร์รี่ (เบต้าอาร์บูติน)', good=_TYR + ' ' + _SPOTS,
      tips=_SPOT_TIPS, aka=['Beta-Arbutin'], en='Natural brightener', smi='OCC1OC(Oc2ccc(O)cc2)C(O)C(O)C1O', f='C12H16O7'),
    I('Kojic Acid', 'กรดโคจิก', 'brightening', [E, M, C], 'สารที่ได้จากการหมักเชื้อราโคจิในการทำสาเกและซีอิ๊ว',
      good=_TYR + ' ' + _SPOTS, tips='อาจระคายเคืองหรือแพ้ได้ และเสื่อมง่าย ' + _SPOT_TIPS, note='sensitize',
      en='Fermentation-derived brightener', smi='OCc1cc(=O)c(O)co1', f='C6H6O4'),
    I('Glutathione', 'กลูตาไธโอน', ['brightening', 'antioxidant'], [E, M], 'สารต้านอนุมูลอิสระที่ร่างกายสร้างเอง ประกอบด้วยกรดอะมิโน 3 ตัว',
      good='ต้านอนุมูลอิสระ อาจช่วยเปลี่ยนการสร้างเม็ดสีให้เป็นสีอ่อนลง', tips='การทาภายนอกมีหลักฐานจำกัด และเสื่อมง่ายในสูตร',
      en='Antioxidant tripeptide', smi='NC(CCC(=O)NC(CS)C(=O)NCC(=O)O)C(=O)O', f='C10H17N3O6S'),
    I('Hexylresorcinol', 'เฮกซิลรีซอร์ซินอล', ['brightening', 'antioxidant'], [E, M], 'อนุพันธ์รีซอร์ซินอลที่ยับยั้งการสร้างเม็ดสีได้แรง',
      good=_TYR + ' และต้านอนุมูลอิสระ ' + _SPOTS, tips=_SPOT_TIPS, en='Potent resorcinol brightener',
      smi='CCCCCCc1ccc(O)cc1O', f='C12H18O2'),
    I('4-Butylresorcinol', 'บิวทิลรีซอร์ซินอล', 'brightening', [E, M], 'อนุพันธ์รีซอร์ซินอลที่ยับยั้งไทโรซิเนสได้แรงที่สุดตัวหนึ่ง',
      good=_TYR + ' ' + _SPOTS, tips=_SPOT_TIPS, aka=['Rucinol'], en='Very potent resorcinol brightener',
      smi='CCCCc1ccc(O)cc1O', f='C10H14O2'),
    I('Phenylethyl Resorcinol', 'ฟีนิลเอทิลรีซอร์ซินอล', ['brightening', 'antioxidant'], [E, M], 'อนุพันธ์รีซอร์ซินอลที่ยับยั้งการสร้างเม็ดสีได้แรง',
      good=_TYR + ' ' + _SPOTS, tips='อาจไวต่อแสง ควรใช้ในขวดทึบ ' + _SPOT_TIPS, aka=['SymWhite 377'], en='Potent resorcinol brightener',
      smi='CC(c1ccccc1)c1ccc(O)cc1O', f='C14H14O2'),
    I('Isobutylamido Thiazolyl Resorcinol', 'ไทอะมิดอล', 'brightening', [E, M, S],
      'สารยับยั้งไทโรซิเนสของมนุษย์ที่พัฒนาโดยไบเออร์สด๊อร์ฟ (ยูเซอริน) มีงานวิจัยว่าได้ผลดีกับฝ้า', good=_TYR + ' ' + _SPOTS,
      tips=_SPOT_TIPS, aka=['Thiamidol'], en='Thiamidol; strong human-tyrosinase inhibitor',
      smi='CC(C)C(=O)Nc1csc(n1)-c1ccc(O)cc1O', f='C13H14N2O3S'),
    I('Cysteamine', 'ซิสเทอามีน', 'brightening', [E], 'สารต้านอนุมูลอิสระที่ร่างกายสร้างเอง ใช้เป็นครีมลดฝ้าแบบทาทิ้งไว้ระยะสั้นแล้วล้างออก',
      tips='มีกลิ่นกำมะถัน และอาจแดง/แสบ ทำตามเวลาที่ฉลากกำหนด', en='Short-contact melasma treatment',
      smi='NCCS', f='C2H7NS'),
    I('Hydroquinone', 'ไฮโดรควิโนน', 'brightening', [E], 'สารลดเม็ดสีที่แรงที่สุดตัวหนึ่ง ใช้เป็นยาลดฝ้าภายใต้การดูแลของแพทย์',
      note='hydroquinone', en='Prescription depigmenting agent', smi='Oc1ccc(O)cc1', f='C6H6O2'),
    I('Undecylenoyl Phenylalanine', 'อันเดซิลีโนอิลฟีนิลอะลานีน', 'brightening', [E, M], 'สารที่ยับยั้งการส่งสัญญาณกระตุ้นการสร้างเม็ดสี (α-MSH)',
      good=_SPOTS, tips=_SPOT_TIPS, aka=['Sepiwhite'], en='α-MSH antagonist brightener',
      smi='C=CCCCCCCCCC(=O)NC(Cc1ccccc1)C(=O)O', f='C20H29NO3'),
    I('Acetyl Glucosamine', 'อะซิทิลกลูโคซามีน', ['brightening', 'humectant'], [E, M], 'น้ำตาลอะมิโนที่ช่วยลดการสร้างเม็ดสีและให้ความชุ่มชื้น',
      good='ใช้ร่วมกับไนอะซินาไมด์ช่วยลดจุดด่างดำได้ดีขึ้น', aka=['NAG', 'N-Acetylglucosamine'], en='Brightening amino sugar',
      smi='CC(=O)NC1C(O)OC(CO)C(O)C1O', f='C8H15NO6'),
    I('Dimethylmethoxy Chromanol', 'ไดเมทิลเมทอกซีโครมานอล', ['antioxidant', 'brightening'], [E, M],
      'สารต้านอนุมูลอิสระที่แรงและคงตัว ช่วยลดจุดด่างดำ', aka=['Lipochroman'], en='Potent stable antioxidant',
      smi='CC1(C)CCc2cc(O)c(OC)cc2O1', f='C12H16O3'),
    I('Ellagic Acid', 'กรดเอลลาจิก', ['brightening', 'antioxidant'], [E], 'โพลีฟีนอลจากทับทิมและเบอร์รี่ ต้านอนุมูลอิสระและลดการสร้างเม็ดสี',
      en='Polyphenol brightener', smi='O=C1Oc2c(O)c(O)cc3c(=O)oc4c(O)c(O)cc1c4c23', f='C14H6O8'),
    I('Glabridin', 'กลาบริดิน', ['brightening', 'soothing'], [E], 'สารสำคัญจากรากชะเอมเทศ ยับยั้งไทโรซิเนสและลดการอักเสบ',
      good=_SPOTS + ' และลดรอยแดง', en='Licorice brightener', smi='CC1(C)C=Cc2c(O1)ccc1c2OCC(C1)c1ccc(O)cc1O', f='C20H20O4'),
    I('Licochalcone A', 'ลิโคชาลโคน เอ', ['soothing', 'antiAcne'], [E, M], 'สารจากรากชะเอมเทศ ช่วยลดการอักเสบ รอยแดง และควบคุมความมัน',
      en='Soothing licorice compound', smi='CC(C)(C=C)c1cc(/C=C/C(=O)c2ccc(O)cc2)c(OC)cc1O', f='C21H22O4'),
    I('Tetrahydrocurcuminoids', 'เตตระไฮโดรเคอร์คูมินอยด์', ['antioxidant', 'brightening'], [E, M],
      'อนุพันธ์ไร้สีของเคอร์คูมินจากขมิ้น ต้านอนุมูลอิสระและช่วยให้ผิวกระจ่างใส โดยไม่ทิ้งสีเหลือง', en='Colourless turmeric antioxidant',
      smi='COc1cc(CCC(=O)CC(=O)CCc2ccc(O)c(OC)c2)ccc1O', f='C21H24O6'),
    I('Glycyrrhiza Glabra Root Extract', 'สารสกัดรากชะเอมเทศ', ['brightening', 'soothing'], [M, E, T],
      'สารสกัดจากรากชะเอมเทศ มีกลาบริดินและลิโคชาลโคน', good=_SPOTS + ' และลดรอยแดง ผิวระคายเคือง', aka=['Licorice', 'ชะเอม'],
      en='Licorice root: brightening and soothing', kind='extract'),
    I('Glycyrrhiza Inflata Root Extract', 'สารสกัดรากชะเอมจีน', ['soothing', 'brightening'], [M, E], 'สารสกัดชะเอมอีกสายพันธุ์ที่มีลิโคชาลโคน เอ สูง ช่วยลดการอักเสบ',
      aka=['Licorice'], en='Licorice (licochalcone-rich)', kind='extract'),
    I('Morus Alba Root Extract', 'สารสกัดรากหม่อน', 'brightening', [E, T], 'สารสกัดจากรากต้นหม่อน ยับยั้งการสร้างเม็ดสี', good=_SPOTS,
      aka=['Mulberry', 'หม่อน'], en='Mulberry root brightener', kind='extract'),
    I('Broussonetia Kazinoki Root Extract', 'สารสกัดรากต้นสา (เปเปอร์มัลเบอร์รี่)', 'brightening', [E], 'สารสกัดที่ยับยั้งไทโรซิเนสได้ดี', good=_SPOTS,
      aka=['Paper Mulberry'], en='Paper mulberry brightener', kind='extract'),
    I('Arctostaphylos Uva-Ursi Leaf Extract', 'สารสกัดใบแบร์เบอร์รี่', 'brightening', [E, M], 'สารสกัดที่มีอาร์บูตินตามธรรมชาติ', good=_SPOTS,
      aka=['Bearberry'], en='Natural arbutin source', kind='extract'),
    I('Phyllanthus Emblica Fruit Extract', 'สารสกัดมะขามป้อม', ['antioxidant', 'brightening'], [E, M, T], 'สารสกัดจากมะขามป้อม มีวิตามินซีและแทนนินสูง ต้านอนุมูลอิสระ',
      aka=['Amla', 'มะขามป้อม'], en='Amla: antioxidant brightener', kind='extract'),
    I('Bellis Perennis Flower Extract', 'สารสกัดดอกเดซี่', 'brightening', [E, M], 'สารสกัดดอกเดซี่ที่ช่วยลดการสร้างเม็ดสี', aka=['Daisy'],
      en='Daisy flower brightener', kind='extract'),
    I('Saxifraga Sarmentosa Extract', 'สารสกัดแซกซิฟรากา', 'brightening', [E, T], 'สารสกัดพืชที่ช่วยให้ผิวกระจ่างใส', aka=['Strawberry Begonia'],
      en='Brightening plant extract', kind='extract'),
    I('Oryza Sativa Extract', 'สารสกัดข้าว', ['brightening', 'humectant'], [C, M, T], 'สารสกัดจากข้าว มีกรดอะมิโนและวิตามิน ช่วยให้ผิวนุ่มกระจ่างใส',
      aka=['Rice', 'ข้าว'], en='Rice extract', kind='extract'),
    I('Galactomyces Ferment Filtrate', 'กาแลคโตไมซิสเฟอร์เมนต์', ['brightening', 'humectant'], [E, T],
      'ผลิตภัณฑ์จากการหมักยีสต์กาแลคโตไมซิส (คล้ายพิเทร่า) มีกรดอะมิโน แร่ธาตุ และกรดอินทรีย์',
      good='ช่วยให้ผิวดูใส เนียน ชุ่มชื้น', aka=['Galactomyces', 'กาแลคโตมัยเซส', 'Pitera'], en='Yeast ferment for radiance', kind='ferment'),
    I('Pearl Powder', 'ผงไข่มุก', ['brightening', 'colorant'], [M], 'ผงจากไข่มุกบด มีแคลเซียมคาร์บอเนตและโปรตีน ให้ผิวดูเปล่งประกาย',
      en='Pearl powder; luminous', kind='mineral'),
]
