"""Cleansing agents (surfactants), soaps, cleansing-oil emulsifiers, scrubs."""
from common import ALL, C, E, I, M, S, T

_SULFATE = 'สารทำความสะอาดกลุ่มซัลเฟต (anionic) ให้ฟองเยอะ ล้างคราบมันได้ดี'
_AMINO = ('สารทำความสะอาดที่ได้จากกรดอะมิโนรวมกับกรดไขมันจากมะพร้าว/ปาล์ม '
          'ให้ฟองนุ่ม ค่า pH ใกล้ผิว จึงอ่อนโยนกว่ากลุ่มซัลเฟต')
_AMINO_GOOD = 'ล้างสะอาดโดยผิวไม่ตึง เหมาะกับผิวแห้ง ผิวแพ้ง่าย และคนที่ใช้กรดหรือเรตินอยด์'
_GLUCOSIDE = ('สารทำความสะอาดชนิด non-ionic ทำจากน้ำตาลกลูโคสกับแอลกอฮอล์ไขมันจากพืช '
              'อ่อนโยน ย่อยสลายได้ง่าย')
_BETAINE = ('สารทำความสะอาดชนิด amphoteric (มีทั้งประจุบวกและลบ) มักใช้คู่กับสารหลักเพื่อ'
            'ให้ฟองนุ่มขึ้น เพิ่มความหนืด และลดความระคายเคืองของซัลเฟต')
_SOAP = ('สบู่ที่เกิดจากกรดไขมันทำปฏิกิริยากับด่าง (โพแทสเซียมไฮดรอกไซด์) ให้ฟองแน่น '
         'ล้างสะอาดมาก แต่ค่า pH เป็นด่าง (ประมาณ 9–10)')
_SOAP_TIPS = ('พบมากในโฟมล้างหน้าเนื้อครีมสูตรสบู่ ถ้าผิวแห้งตึงหลังล้าง '
              'ลองเปลี่ยนเป็นสูตรกรดอะมิโนหรือเจลอ่อนโยน')
_FATTY = ('กรดไขมันอิ่มตัวที่พบในน้ำมันพืช ในโฟมล้างหน้าจะทำปฏิกิริยากับด่างกลายเป็นสบู่ '
          'ส่วนในครีมช่วยให้เนื้อข้นและคงตัว')
_PEG_OIL = ('สารลดแรงตึงผิวที่ทำให้น้ำมันละลายน้ำได้ จึงเปลี่ยนคลีนซิ่งออยล์/บาล์มให้กลายเป็น'
            'น้ำนมเมื่อโดนน้ำ (emulsify) และล้างออกได้หมด')
_SCRUB = 'เม็ดสครับขัดผิวทางกายภาพ ช่วยขัดเซลล์ผิวเก่าออก'
_SCRUB_TIPS = 'ขัดเบาๆ ไม่เกิน 1–2 ครั้งต่อสัปดาห์ หลีกเลี่ยงบริเวณที่เป็นสิวอักเสบ'
_CLAY = 'ดินแร่ธรรมชาติที่ดูดซับความมันและสิ่งสกปรกได้ดี พบในมาส์กโคลนและโฟมล้างหน้า'
_CLAY_TIPS = 'เหมาะกับผิวมัน/ผสม ไม่ควรปล่อยให้มาส์กแห้งจนตึงแตก ล้างออกแล้วตามด้วยมอยส์เจอไรเซอร์'

ROWS = [
    # ---------- Sulfates & other anionics ----------
    I('Sodium Lauryl Sulfate', 'โซเดียมลอริลซัลเฟต', 'surfactant', [C],
      _SULFATE + ' เป็นตัวที่แรงที่สุดในกลุ่ม',
      good='ล้างคราบมันและสิ่งสกปรกได้หมดจด ให้ฟองมากและราคาถูก',
      tips='ถ้าเป็นผิวแห้ง/แพ้ง่าย เลือกสูตรที่มีตัวนี้ไม่อยู่อันดับต้นๆ หรือมีสารอ่อนโยนอย่างเบทาอีนช่วย',
      aka=['SLS'], note='harsh', en='Strong, foamy anionic cleanser',
      smi='CCCCCCCCCCCCOS(=O)(=O)[O-].[Na+]', f='C12H25NaO4S'),
    I('Sodium Laureth Sulfate', 'โซเดียมลอเรทซัลเฟต', 'surfactant', [C],
      _SULFATE + ' เป็น SLS ที่ผ่านการเติมหมู่เอทอกซี (ethoxylation) ทำให้โมเลกุลใหญ่ขึ้นและอ่อนโยนกว่า SLS',
      good='ให้ฟองดี ล้างสะอาด อ่อนกว่า SLS จึงพบได้ทั่วไปในเจลล้างหน้าและครีมอาบน้ำ',
      tips='ส่วนใหญ่ใช้คู่กับโคคามิโดโพรพิลบีเทนเพื่อลดความระคายเคือง',
      aka=['SLES'], en='Milder ethoxylated sulfate cleanser', kind='mixture'),
    I('Ammonium Lauryl Sulfate', 'แอมโมเนียมลอริลซัลเฟต', 'surfactant', [C],
      _SULFATE + ' คล้าย SLS แต่ใช้แอมโมเนียมเป็นประจุคู่',
      good='ฟองเยอะ ล้างมันได้ดี', aka=['ALS'], note='harsh',
      en='Strong sulfate cleanser similar to SLS',
      smi='CCCCCCCCCCCCOS(=O)(=O)[O-].[NH4+]', f='C12H29NO4S'),
    I('Ammonium Laureth Sulfate', 'แอมโมเนียมลอเรทซัลเฟต', 'surfactant', [C],
      _SULFATE + ' แบบเอทอกซีเลต อ่อนกว่า ALS', en='Ethoxylated sulfate cleanser',
      kind='mixture'),
    I('Sodium Myreth Sulfate', 'โซเดียมไมเรทซัลเฟต', 'surfactant', [C],
      _SULFATE + ' สายไขมันยาวกว่าลอเรทเล็กน้อย ฟองครีมมี่', en='Ethoxylated sulfate cleanser',
      kind='mixture'),
    I('Sodium Trideceth Sulfate', 'โซเดียมไตรเดเซทซัลเฟต', 'surfactant', [C],
      _SULFATE + ' แบบเอทอกซีเลต ค่อนข้างอ่อนโยน', en='Mild ethoxylated sulfate', kind='mixture'),
    I('Magnesium Laureth Sulfate', 'แมกนีเซียมลอเรทซัลเฟต', 'surfactant', [C],
      _SULFATE + ' ใช้แมกนีเซียมเป็นประจุคู่ อ่อนโยนกว่าแบบโซเดียม', en='Mild sulfate cleanser',
      kind='mixture'),
    I('TEA-Lauryl Sulfate', 'ทีอีเอ-ลอริลซัลเฟต', 'surfactant', [C],
      _SULFATE + ' ใช้ไตรเอทาโนลามีนเป็นประจุคู่ อ่อนกว่า SLS เล็กน้อย', en='Sulfate cleanser',
      smi='CCCCCCCCCCCCOS(=O)(=O)[O-].OCC[NH+](CCO)CCO', f='C18H41NO7S'),
    I('Sodium Coco-Sulfate', 'โซเดียมโคโคซัลเฟต', 'surfactant', [C],
      _SULFATE + ' ทำจากกรดไขมันมะพร้าวหลายความยาว ความแรงใกล้เคียง SLS',
      aka=['SCS'], note='harsh', en='Coconut-derived sulfate, close to SLS', kind='mixture'),
    I('Sodium C14-16 Olefin Sulfonate', 'โซเดียมซี14-16 โอเลฟินซัลโฟเนต', 'surfactant', [C],
      'สารทำความสะอาดชนิดซัลโฟเนต ไม่ใช่ซัลเฟตแต่ความแรงใกล้เคียงกัน ฟองเยอะ ล้างมันดี',
      tips='มักพบในสูตรที่เขียนว่า "sulfate-free" แต่ยังล้างแรงอยู่', note='harsh',
      en='Sulfonate cleanser; "sulfate-free" but still strong', kind='mixture'),
    I('Sodium Lauryl Sulfoacetate', 'โซเดียมลอริลซัลโฟอะซิเตต', 'surfactant', [C],
      'สารทำความสะอาดที่อ่อนกว่า SLS ให้ฟองนุ่มแน่น มักใช้แทนซัลเฟต',
      en='Gentler foaming alternative to sulfates',
      smi='CCCCCCCCCCCCOC(=O)CS(=O)(=O)[O-].[Na+]', f='C14H27NaO5S'),
    I('Disodium Lauryl Sulfosuccinate', 'ไดโซเดียมลอริลซัลโฟซัคซิเนต', 'surfactant', [C],
      'สารทำความสะอาดกลุ่มซัลโฟซัคซิเนต อ่อนโยน ฟองดี มักใช้ในสูตรเด็กและสูตรอ่อนโยน',
      en='Mild sulfosuccinate cleanser',
      smi='CCCCCCCCCCCCOC(=O)CC(C(=O)[O-])S(=O)(=O)[O-].[Na+].[Na+]', f='C16H28Na2O7S'),
    I('Disodium Laureth Sulfosuccinate', 'ไดโซเดียมลอเรทซัลโฟซัคซิเนต', 'surfactant', [C],
      'สารทำความสะอาดกลุ่มซัลโฟซัคซิเนตแบบเอทอกซีเลต อ่อนโยนมาก ช่วยลดการระคายเคืองของซัลเฟต',
      en='Very mild sulfosuccinate cleanser', kind='mixture'),
    I('Sodium Lauroyl Sarcosinate', 'โซเดียมลอรอยล์ซาร์โคซิเนต', 'surfactant', [C],
      'สารทำความสะอาดจากกรดอะมิโนซาร์โคซีน ฟองนุ่มละเอียด อ่อนกว่าซัลเฟต',
      good=_AMINO_GOOD, en='Mild amino-acid based cleanser',
      smi='CCCCCCCCCCCC(=O)N(C)CC(=O)[O-].[Na+]', f='C15H28NNaO3'),
    I('Sodium Cocoyl Sarcosinate', 'โซเดียมโคคอยล์ซาร์โคซิเนต', 'surfactant', [C],
      'สารทำความสะอาดจากกรดอะมิโนซาร์โคซีนกับกรดไขมันมะพร้าว ฟองนุ่ม อ่อนโยน',
      en='Mild amino-acid based cleanser', kind='mixture'),
    I('Sodium Cocoyl Isethionate', 'โซเดียมโคคอยล์ไอเซไทโอเนต', 'surfactant', [C],
      'สารทำความสะอาดอ่อนโยนที่นิยมในสบู่ก้อนแบบ syndet (ไม่ใช่สบู่ด่าง) ฟองครีมมี่ ไม่ทำให้ผิวตึง',
      good='ล้างสะอาดแต่คงความชุ่มชื้น ค่า pH ใกล้ผิว', aka=['SCI'],
      en='Gentle, creamy cleanser used in syndet bars', kind='mixture'),
    I('Sodium Lauroyl Methyl Isethionate', 'โซเดียมลอรอยล์เมทิลไอเซไทโอเนต', 'surfactant', [C],
      'สารทำความสะอาดกลุ่มไอเซไทโอเนต อ่อนโยน ละลายน้ำง่าย ให้ฟองนุ่ม พบมากในเจลล้างหน้าสูตรอ่อนโยน',
      good='ล้างสะอาดโดยไม่ทำลายเกราะผิว', aka=['SLMI'], en='Gentle isethionate cleanser'),
    I('Sodium Isethionate', 'โซเดียมไอเซไทโอเนต', 'surfactant', [C],
      'เกลือที่เป็นส่วนประกอบของสารทำความสะอาดกลุ่มไอเซไทโอเนต ช่วยเรื่องเนื้อสัมผัสและความคงตัวของสบู่ก้อน',
      en='Isethionate salt used in syndet bars',
      smi='OCCS(=O)(=O)[O-].[Na+]', f='C2H5NaO4S'),
    I('Sodium Methyl Cocoyl Taurate', 'โซเดียมเมทิลโคคอยล์ทอเรต', 'surfactant', [C],
      'สารทำความสะอาดจากกรดอะมิโนทอรีน อ่อนโยนมาก ฟองนุ่ม ล้างออกง่าย',
      good=_AMINO_GOOD, en='Very mild taurate cleanser', kind='mixture'),
    I('Sodium Methyl Oleoyl Taurate', 'โซเดียมเมทิลโอลีโอยล์ทอเรต', 'surfactant', [C],
      'สารทำความสะอาดกลุ่มทอเรตจากกรดโอเลอิก อ่อนโยน', en='Mild taurate cleanser',
      kind='mixture'),
    I('Sodium Cocoyl Glutamate', 'โซเดียมโคคอยล์กลูตาเมต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, tips='มักเขียนว่า "amino acid cleanser" บนฉลาก',
      aka=['amino acid cleanser', 'กรดอะมิโน'], en='Gentle amino-acid cleanser', kind='mixture'),
    I('Sodium Lauroyl Glutamate', 'โซเดียมลอรอยล์กลูตาเมต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, aka=['amino acid cleanser'], en='Gentle amino-acid cleanser',
      smi='CCCCCCCCCCCC(=O)NC(CCC(=O)O)C(=O)[O-].[Na+]', f='C17H30NNaO5'),
    I('Disodium Cocoyl Glutamate', 'ไดโซเดียมโคคอยล์กลูตาเมต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, aka=['amino acid cleanser'], en='Gentle amino-acid cleanser',
      kind='mixture'),
    I('TEA-Cocoyl Glutamate', 'ทีอีเอ-โคคอยล์กลูตาเมต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, en='Gentle amino-acid cleanser', kind='mixture'),
    I('Potassium Cocoyl Glycinate', 'โพแทสเซียมโคคอยล์ไกลซิเนต', 'surfactant', [C],
      _AMINO + ' ตัวนี้ให้ฟองแน่นคล้ายโฟมสบู่แต่ไม่ตึงเท่า',
      good=_AMINO_GOOD, aka=['amino acid cleanser'], en='Rich-foaming amino-acid cleanser',
      kind='mixture'),
    I('Sodium Cocoyl Glycinate', 'โซเดียมโคคอยล์ไกลซิเนต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, aka=['amino acid cleanser'], en='Gentle amino-acid cleanser',
      kind='mixture'),
    I('Sodium Cocoyl Alaninate', 'โซเดียมโคคอยล์อะลานิเนต', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, aka=['amino acid cleanser'], en='Gentle amino-acid cleanser',
      kind='mixture'),
    I('Sodium Cocoyl Apple Amino Acids', 'โซเดียมโคคอยล์แอปเปิลอะมิโนแอซิด', 'surfactant', [C],
      _AMINO + ' ใช้กรดอะมิโนจากแอปเปิล', good=_AMINO_GOOD,
      en='Gentle amino-acid cleanser', kind='mixture'),
    I('Sodium Cocoyl Amino Acids', 'โซเดียมโคคอยล์อะมิโนแอซิด', 'surfactant', [C], _AMINO,
      good=_AMINO_GOOD, en='Gentle amino-acid cleanser', kind='mixture'),
    I('Sodium Lauroyl Oat Amino Acids', 'โซเดียมลอรอยล์โอ๊ตอะมิโนแอซิด', 'surfactant', [C],
      _AMINO + ' ใช้กรดอะมิโนจากข้าวโอ๊ต', good=_AMINO_GOOD, en='Oat amino-acid cleanser',
      kind='mixture'),
    I('Sodium Lauroyl Lactylate', 'โซเดียมลอรอยล์แลคทิเลต', ['surfactant', 'emulsifier'], [C, M],
      'อิมัลซิไฟเออร์/สารทำความสะอาดอ่อนๆ จากกรดลอริกกับกรดแลคติก ช่วยให้เนื้อครีมนุ่ม',
      good='ช่วยทำความสะอาดเบาๆ และให้ความรู้สึกชุ่มชื้น', en='Mild lactylate emulsifier/cleanser',
      smi='CCCCCCCCCCCC(=O)OC(C)C(=O)OC(C)C(=O)[O-].[Na+]', f='C18H31NaO6'),
    I('Sodium Laureth-5 Carboxylate', 'โซเดียมลอเรท-5 คาร์บอกซิเลต', 'surfactant', [C],
      'สารทำความสะอาดชนิดคาร์บอกซิเลต อ่อนโยนมาก ช่วยลดการระคายเคืองของสูตร',
      en='Very mild carboxylate cleanser', kind='polymer'),
    I('Sodium Lauryl Glucose Carboxylate', 'โซเดียมลอริลกลูโคสคาร์บอกซิเลต', 'surfactant', [C],
      'สารทำความสะอาดอ่อนโยนจากน้ำตาลกลูโคส มักมาคู่กับลอริลกลูโคไซด์', en='Mild sugar-based cleanser',
      kind='mixture'),
    # ---------- Amphoterics ----------
    I('Cocamidopropyl Betaine', 'โคคามิโดโพรพิลบีเทน', 'surfactant', [C], _BETAINE,
      good='ทำให้เจลล้างหน้าอ่อนโยนขึ้นและฟองนุ่ม',
      tips='พบในโฟม/เจลล้างหน้าเกือบทุกสูตร บางคนแพ้สารตกค้างจากการผลิต (เช่น DMAPA) แต่พบไม่บ่อย',
      aka=['CAPB'], en='Mild amphoteric co-cleanser', kind='mixture'),
    I('Lauramidopropyl Betaine', 'ลอรามิโดโพรพิลบีเทน', 'surfactant', [C], _BETAINE,
      en='Mild amphoteric co-cleanser',
      smi='CCCCCCCCCCCC(=O)NCCC[N+](C)(C)CC(=O)[O-]', f='C19H38N2O3'),
    I('Coco-Betaine', 'โคโคบีเทน', 'surfactant', [C], _BETAINE, en='Mild amphoteric co-cleanser',
      kind='mixture'),
    I('Cocamidopropyl Hydroxysultaine', 'โคคามิโดโพรพิลไฮดรอกซีซัลเทน', 'surfactant', [C],
      _BETAINE + ' ทนต่อน้ำกระด้างและให้ฟองดีกว่าบีเทนเล็กน้อย', en='Mild amphoteric co-cleanser',
      kind='mixture'),
    I('Lauryl Hydroxysultaine', 'ลอริลไฮดรอกซีซัลเทน', 'surfactant', [C], _BETAINE,
      en='Mild amphoteric co-cleanser',
      smi='CCCCCCCCCCCC[N+](C)(C)CC(O)CS(=O)(=O)[O-]', f='C17H37NO4S'),
    I('Sodium Cocoamphoacetate', 'โซเดียมโคโคแอมโฟอะซิเตต', 'surfactant', [C],
      'สารทำความสะอาดชนิด amphoteric ที่อ่อนโยนมาก ไม่ค่อยแสบตา จึงนิยมในสูตรเด็ก', 
      en='Very mild amphoteric cleanser (baby formulas)', kind='mixture'),
    I('Sodium Lauroamphoacetate', 'โซเดียมลอโรแอมโฟอะซิเตต', 'surfactant', [C],
      'สารทำความสะอาดชนิด amphoteric อ่อนโยน ไม่ค่อยแสบตา', en='Very mild amphoteric cleanser',
      kind='mixture'),
    I('Disodium Cocoamphodiacetate', 'ไดโซเดียมโคโคแอมโฟไดอะซิเตต', 'surfactant', [C],
      'สารทำความสะอาดชนิด amphoteric อ่อนโยน ช่วยลดความระคายเคืองของสารหลัก',
      en='Mild amphoteric cleanser', kind='mixture'),
    I('Lauramine Oxide', 'ลอรามีนออกไซด์', 'surfactant', [C],
      'สารเสริมฟองและเพิ่มความหนืดในเจลล้างหน้า/สบู่เหลว', en='Foam booster and thickener',
      smi='CCCCCCCCCCCC[N+](C)(C)[O-]', f='C14H31NO'),
    I('Cocamidopropylamine Oxide', 'โคคามิโดโพรพิลอะมีนออกไซด์', 'surfactant', [C],
      'สารเสริมฟองและเพิ่มความหนืด อ่อนโยน', en='Mild foam booster', kind='mixture'),
    I('Cocamide MEA', 'โคคาไมด์ เอ็มอีเอ', ['surfactant', 'thickener'], [C],
      'สารเพิ่มความหนืดและทำให้ฟองคงตัว ทำจากกรดไขมันมะพร้าว', en='Foam stabiliser and thickener',
      kind='mixture'),
    I('Cocamide DEA', 'โคคาไมด์ ดีอีเอ', ['surfactant', 'thickener'], [C],
      'สารเพิ่มความหนืดและฟอง ปัจจุบันใช้น้อยลงเพราะอาจมีสารปนเปื้อนกลุ่มไนโตรซามีน',
      note=('มีข้อกังวลเรื่องสารปนเปื้อนไนโตรซามีน หลายแบรนด์เลิกใช้แล้ว',
            'Concerns over nitrosamine impurities; many brands have dropped it'),
      en='Thickener/foam booster, now less used', kind='mixture'),
    # ---------- Non-ionics ----------
    I('Decyl Glucoside', 'เดซิลกลูโคไซด์', 'surfactant', [C], _GLUCOSIDE,
      good='ล้างสะอาดอย่างอ่อนโยน เหมาะกับผิวแพ้ง่ายและสูตรธรรมชาติ',
      tips='บางคนแพ้กลุ่มกลูโคไซด์ได้ แม้จะพบไม่บ่อย', en='Gentle sugar-based cleanser',
      smi='CCCCCCCCCCOC1OC(CO)C(O)C(O)C1O', f='C16H32O6'),
    I('Lauryl Glucoside', 'ลอริลกลูโคไซด์', 'surfactant', [C], _GLUCOSIDE,
      en='Gentle sugar-based cleanser',
      smi='CCCCCCCCCCCCOC1OC(CO)C(O)C(O)C1O', f='C18H36O6'),
    I('Coco-Glucoside', 'โคโคกลูโคไซด์', 'surfactant', [C], _GLUCOSIDE,
      en='Gentle sugar-based cleanser', kind='mixture'),
    I('Caprylyl/Capryl Glucoside', 'แคพริลิล/แคพริลกลูโคไซด์', 'surfactant', [C], _GLUCOSIDE,
      en='Gentle sugar-based cleanser', kind='mixture'),
    I('Sucrose Cocoate', 'ซูโครสโคโคเอต', ['surfactant', 'emollient'], [C],
      'สารจากน้ำตาลซูโครสกับกรดไขมันมะพร้าว ช่วยทำความสะอาดอ่อนๆ และเติมความชุ่มชื้นให้สูตร',
      en='Sugar ester; mild cleanser and moisturising additive', kind='mixture'),
    I('Sucrose Laurate', 'ซูโครสลอเรต', ['surfactant', 'emulsifier'], [C, M],
      'อิมัลซิไฟเออร์/สารทำความสะอาดอ่อนโยนจากน้ำตาลซูโครส', en='Mild sugar-ester emulsifier',
      kind='mixture'),
    I('Laureth-4', 'ลอเรท-4', ['surfactant', 'emulsifier'], [C],
      'สารลดแรงตึงผิวชนิด non-ionic จากแอลกอฮอล์ไขมันที่ผ่านการเอทอกซีเลต', en='Non-ionic surfactant',
      kind='polymer'),
    I('Laureth-7', 'ลอเรท-7', ['surfactant', 'emulsifier'], [C, M],
      'สารลดแรงตึงผิวชนิด non-ionic มักพบคู่กับสารเพิ่มความหนืดในเซรั่ม/ครีม', en='Non-ionic surfactant',
      kind='polymer'),
    I('PEG-7 Glyceryl Cocoate', 'พีอีจี-7 กลีเซอริลโคโคเอต', ['emollient', 'surfactant'], [C],
      'สารให้ความนุ่มที่ละลายน้ำได้ ใส่ในเจลล้างหน้าเพื่อลดความแห้งตึงหลังล้าง',
      en='Water-soluble emollient for cleansers', kind='polymer'),
    I('PEG-6 Caprylic/Capric Glycerides', 'พีอีจี-6 แคพริลิก/แคพริกกลีเซอไรด์', 'surfactant', [C],
      'สารลดแรงตึงผิวที่ละลายน้ำ เป็นตัวหลักของไมเซลล่าวอเตอร์ จับเครื่องสำอางและน้ำมันได้โดยไม่ต้องล้างน้ำ',
      good='เช็ดเครื่องสำอางได้อ่อนโยน', aka=['micellar', 'ไมเซลล่า'], en='Micellar water cleanser',
      kind='polymer'),
    I('Poloxamer 184', 'โพลอกซาเมอร์ 184', 'surfactant', [C],
      'พอลิเมอร์ลดแรงตึงผิวที่อ่อนโยนมาก ใช้ในไมเซลล่าวอเตอร์และน้ำยาทำความสะอาดคอนแทคเลนส์',
      aka=['micellar', 'ไมเซลล่า'], en='Very mild polymeric surfactant (micellar)', kind='polymer'),
    I('Poloxamer 407', 'โพลอกซาเมอร์ 407', ['surfactant', 'thickener'], [C, E],
      'พอลิเมอร์ลดแรงตึงผิวอ่อนโยน ใช้ในไมเซลล่าและเป็นเจลเนื้อใส', en='Mild polymeric surfactant/gel former',
      kind='polymer'),
    I('Polysorbate 20', 'โพลีซอร์เบต 20', ['emulsifier', 'surfactant'], [C, T, E],
      'อิมัลซิไฟเออร์ชนิด non-ionic ที่ช่วยละลายน้ำหอม/น้ำมันปริมาณน้อยๆ ลงในสูตรที่เป็นน้ำ (solubiliser)',
      aka=['Tween 20'], en='Solubiliser for oils and fragrance in water-based products', kind='polymer'),
    I('Polysorbate 60', 'โพลีซอร์เบต 60', 'emulsifier', [M, S],
      'อิมัลซิไฟเออร์ชนิด non-ionic ช่วยให้น้ำกับน้ำมันในครีมผสมกันได้', aka=['Tween 60'],
      en='Oil-in-water emulsifier', kind='polymer'),
    I('Polysorbate 80', 'โพลีซอร์เบต 80', ['emulsifier', 'surfactant'], [C, M],
      'อิมัลซิไฟเออร์ชนิด non-ionic ใช้ละลายน้ำมันและเป็นตัวช่วยให้คลีนซิ่งล้างออกง่าย',
      aka=['Tween 80'], en='Solubiliser and emulsifier', kind='polymer'),
    I('PEG-40 Hydrogenated Castor Oil', 'พีอีจี-40 น้ำมันละหุ่งไฮโดรจีเนต', ['emulsifier', 'surfactant'],
      [C, T, E], 'สารช่วยละลายน้ำหอมและน้ำมันหอมระเหยในโทนเนอร์และเซรั่มน้ำ ทำให้สูตรใส',
      en='Solubiliser for fragrance in clear products', kind='polymer'),
    I('PEG-60 Hydrogenated Castor Oil', 'พีอีจี-60 น้ำมันละหุ่งไฮโดรจีเนต', ['emulsifier', 'surfactant'],
      [T, E], 'สารช่วยละลายน้ำมันในสูตรน้ำ คล้าย PEG-40 แต่ละลายน้ำได้ดีกว่า', en='Solubiliser',
      kind='polymer'),
    I('Polyglyceryl-10 Laurate', 'โพลีกลีเซอริล-10 ลอเรต', ['emulsifier', 'surfactant'], [C],
      'อิมัลซิไฟเออร์จากกลีเซอรีนและกรดลอริก ไม่มี PEG ใช้ในไมเซลล่าและคลีนซิ่ง', en='PEG-free solubiliser',
      kind='polymer'),
    I('Polyglyceryl-4 Caprate', 'โพลีกลีเซอริล-4 แคพเรต', ['emulsifier', 'surfactant'], [C],
      'อิมัลซิไฟเออร์ไม่มี PEG ช่วยให้คลีนซิ่งออยล์ล้างออกเป็นน้ำนม', en='PEG-free emulsifier',
      kind='polymer'),
    I('Polyglyceryl-6 Caprylate', 'โพลีกลีเซอริล-6 แคพริเลต', ['emulsifier', 'surfactant'], [C],
      'อิมัลซิไฟเออร์ไม่มี PEG ใช้ในคลีนซิ่งออยล์/บาล์มและไมเซลล่า', en='PEG-free emulsifier',
      kind='polymer'),
    I('Polyglyceryl-2 Oleate', 'โพลีกลีเซอริล-2 โอลีเอต', ['emulsifier', 'emollient'], [C],
      'อิมัลซิไฟเออร์แบบละลายในน้ำมัน พบในคลีนซิ่งบาล์ม', en='Oil-soluble emulsifier', kind='polymer'),
    I('Sorbeth-30 Tetraoleate', 'ซอร์เบท-30 เตตระโอลีเอต', ['emulsifier', 'surfactant'], [C],
      _PEG_OIL, aka=['cleansing oil', 'คลีนซิ่งออยล์'], en='Emulsifier that makes cleansing oils rinse off',
      kind='polymer'),
    I('PEG-20 Glyceryl Triisostearate', 'พีอีจี-20 กลีเซอริลไตรไอโซสเตียเรต', ['emulsifier', 'surfactant'],
      [C], _PEG_OIL, aka=['cleansing oil', 'คลีนซิ่งออยล์'], en='Emulsifier for cleansing oils',
      kind='polymer'),
    I('PEG-8 Glyceryl Isostearate', 'พีอีจี-8 กลีเซอริลไอโซสเตียเรต', ['emulsifier', 'surfactant'], [C],
      _PEG_OIL, en='Emulsifier for cleansing oils', kind='polymer'),
    I('Cetyl Ethylhexanoate', 'ซีทิลเอทิลเฮกซาโนเอต', 'emollient', [C, M, S],
      'เอสเทอร์ให้ความลื่นเบาสบาย ละลายเมคอัพและครีมกันแดดกันน้ำได้ดี จึงเป็นน้ำมันหลักในคลีนซิ่งออยล์หลายตัว',
      en='Light ester that dissolves makeup',
      smi='CCCCCCCCCCCCCCCCOC(=O)C(CC)CCCC', f='C24H48O2'),
    I('Hexylene Glycol', 'เฮกซิลีนไกลคอล', ['solvent', 'surfactant'], [C, T],
      'ตัวทำละลายที่ช่วยละลายคราบมันและเพิ่มประสิทธิภาพการทำความสะอาดในไมเซลล่าวอเตอร์',
      en='Solvent used in micellar waters',
      smi='CC(O)CC(C)(C)O', f='C6H14O2'),
    # ---------- Soaps & fatty acids ----------
    I('Potassium Myristate', 'โพแทสเซียมไมริสเตต', 'surfactant', [C], _SOAP, tips=_SOAP_TIPS,
      aka=['soap', 'สบู่'], note='harsh', en='Potassium soap; foamy and alkaline',
      smi='CCCCCCCCCCCCCC(=O)[O-].[K+]', f='C14H27KO2'),
    I('Potassium Laurate', 'โพแทสเซียมลอเรต', 'surfactant', [C], _SOAP, tips=_SOAP_TIPS,
      aka=['soap', 'สบู่'], note='harsh', en='Potassium soap; foamy and alkaline',
      smi='CCCCCCCCCCCC(=O)[O-].[K+]', f='C12H23KO2'),
    I('Potassium Stearate', 'โพแทสเซียมสเตียเรต', 'surfactant', [C], _SOAP, tips=_SOAP_TIPS,
      aka=['soap', 'สบู่'], en='Potassium soap', smi='CCCCCCCCCCCCCCCCCC(=O)[O-].[K+]',
      f='C18H35KO2'),
    I('Potassium Palmitate', 'โพแทสเซียมปาล์มิเตต', 'surfactant', [C], _SOAP, tips=_SOAP_TIPS,
      aka=['soap', 'สบู่'], en='Potassium soap', smi='CCCCCCCCCCCCCCCC(=O)[O-].[K+]',
      f='C16H31KO2'),
    I('Potassium Cocoate', 'โพแทสเซียมโคโคเอต', 'surfactant', [C], _SOAP + ' ทำจากน้ำมันมะพร้าว',
      tips=_SOAP_TIPS, aka=['soap', 'สบู่'], note='harsh', en='Coconut potassium soap', kind='mixture'),
    I('Sodium Cocoate', 'โซเดียมโคโคเอต', 'surfactant', [C],
      'สบู่ก้อนจากน้ำมันมะพร้าวทำปฏิกิริยากับโซดาไฟ ฟองเยอะ ล้างสะอาดมาก ค่า pH เป็นด่าง',
      aka=['soap', 'สบู่'], note='harsh', en='Coconut soap (bar)', kind='mixture'),
    I('Sodium Palmate', 'โซเดียมปาล์มเมต', 'surfactant', [C],
      'สบู่ก้อนจากน้ำมันปาล์ม ทำให้ก้อนสบู่แข็ง ฟองครีมมี่ ค่า pH เป็นด่าง', aka=['soap', 'สบู่'],
      en='Palm oil soap (bar)', kind='mixture'),
    I('Sodium Palm Kernelate', 'โซเดียมปาล์มเคอร์เนเลต', 'surfactant', [C],
      'สบู่ก้อนจากน้ำมันเมล็ดในปาล์ม ฟองเยอะ ค่า pH เป็นด่าง', aka=['soap', 'สบู่'],
      en='Palm kernel soap (bar)', kind='mixture'),
    I('Sodium Stearate', 'โซเดียมสเตียเรต', ['surfactant', 'thickener'], [C],
      'สบู่จากกรดสเตียริก ทำให้สบู่ก้อนและดีโอสติ๊กแข็งตัว', aka=['soap', 'สบู่'],
      en='Hard soap; gives bars their structure',
      smi='CCCCCCCCCCCCCCCCCC(=O)[O-].[Na+]', f='C18H35NaO2'),
    I('Sodium Laurate', 'โซเดียมลอเรต', 'surfactant', [C], 'สบู่จากกรดลอริก ฟองเยอะ ค่า pH เป็นด่าง',
      aka=['soap', 'สบู่'], note='harsh', en='Foamy soap',
      smi='CCCCCCCCCCCC(=O)[O-].[Na+]', f='C12H23NaO2'),
    I('Myristic Acid', 'กรดไมริสติก', ['surfactant', 'emollient'], [C], _FATTY,
      tips='ถ้าอยู่คู่กับโพแทสเซียมไฮดรอกไซด์ในโฟมล้างหน้า แปลว่าเป็นสูตรสบู่',
      aka=['soap base', 'โฟมสบู่'], en='Fatty acid; becomes soap with alkali',
      smi='CCCCCCCCCCCCCC(=O)O', f='C14H28O2'),
    I('Lauric Acid', 'กรดลอริก', ['surfactant', 'emollient'], [C], _FATTY + ' มีฤทธิ์ต้านเชื้อแบคทีเรียบางชนิดด้วย',
      aka=['soap base'], en='Fatty acid; becomes soap with alkali',
      smi='CCCCCCCCCCCC(=O)O', f='C12H24O2'),
    I('Palmitic Acid', 'กรดปาล์มิติก', ['surfactant', 'emollient'], [C, M], _FATTY,
      aka=['soap base'], en='Fatty acid; soap base and thickener',
      smi='CCCCCCCCCCCCCCCC(=O)O', f='C16H32O2'),
    I('Stearic Acid', 'กรดสเตียริก', ['emulsifier', 'surfactant', 'thickener'], [C, M, S], _FATTY,
      aka=['soap base'], en='Fatty acid; soap base, thickener and co-emulsifier',
      smi='CCCCCCCCCCCCCCCCCC(=O)O', f='C18H36O2'),
    # ---------- Conditioning / pearlising / thickening in cleansers ----------
    I('Glycol Distearate', 'ไกลคอลไดสเตียเรต', ['other', 'thickener'], [C],
      'สารที่ทำให้เจลล้างหน้า/แชมพูมีประกายมุกขาวขุ่น และช่วยเพิ่มความหนืด', aka=['pearlizer', 'เนื้อมุก'],
      en='Pearlising agent', smi='CCCCCCCCCCCCCCCCCC(=O)OCCOC(=O)CCCCCCCCCCCCCCCCC', f='C38H74O4'),
    I('Glycol Stearate', 'ไกลคอลสเตียเรต', ['other', 'emulsifier'], [C, M],
      'สารให้ประกายมุกและช่วยให้เนื้อครีม/โลชั่นคงตัว', en='Pearliser and co-emulsifier',
      smi='CCCCCCCCCCCCCCCCCC(=O)OCCO', f='C20H40O3'),
    I('PEG-150 Distearate', 'พีอีจี-150 ไดสเตียเรต', 'thickener', [C],
      'สารเพิ่มความหนืดให้เจลล้างหน้าและแชมพู', en='Thickener for cleansers', kind='polymer'),
    I('PEG-120 Methyl Glucose Dioleate', 'พีอีจี-120 เมทิลกลูโคสไดโอลีเอต', 'thickener', [C],
      'สารเพิ่มความหนืดที่อ่อนโยน ช่วยลดการระคายเคืองตาในสูตรล้างหน้า', en='Gentle thickener for cleansers',
      kind='polymer'),
    I('Acrylates Copolymer', 'อะคริเลตโคพอลิเมอร์', ['thickener', 'filmFormer'], [C, S],
      'พอลิเมอร์สังเคราะห์ที่ช่วยให้เจลข้น แขวนลอยเม็ดสครับ หรือสร้างฟิล์มบางๆ บนผิว',
      en='Synthetic polymer thickener/film former', kind='polymer'),
    I('Acrylates/Steareth-20 Methacrylate Copolymer', 'อะคริเลต/สเตียเรท-20 เมทาคริเลตโคพอลิเมอร์', 'thickener',
      [C, M], 'พอลิเมอร์เพิ่มความหนืดและทำให้เนื้อครีม/เจลคงตัว', en='Polymer thickener', kind='polymer'),
    I('Polyquaternium-7', 'โพลีควอเทอร์เนียม-7', 'filmFormer', [C],
      'พอลิเมอร์ประจุบวกที่เกาะผิวเบาๆ หลังล้าง ทำให้ผิวลื่นนุ่มไม่ตึง', en='Conditioning polymer',
      kind='polymer'),
    I('Polyquaternium-10', 'โพลีควอเทอร์เนียม-10', 'filmFormer', [C],
      'พอลิเมอร์ประจุบวกจากเซลลูโลส ช่วยให้ผิว/ผมนุ่มลื่นหลังล้าง', en='Conditioning polymer',
      kind='polymer'),
    I('Guar Hydroxypropyltrimonium Chloride', 'กัวร์ไฮดรอกซีโพรพิลไตรโมเนียมคลอไรด์', 'filmFormer', [C],
      'สารปรับสภาพจากถั่วกัวร์ ทำให้ผิวรู้สึกนุ่มชุ่มหลังล้าง', en='Guar-based conditioning agent',
      kind='polymer'),
    I('Sodium Chloride', 'โซเดียมคลอไรด์', 'thickener', [C],
      'เกลือแกง ใช้เพิ่มความหนืดให้เจลล้างหน้าที่ใช้สารกลุ่มซัลเฟต', aka=['เกลือ', 'salt'],
      en='Table salt; thickens surfactant gels', kind='mineral', f='NaCl'),
    # ---------- Scrubs, enzymes, clays ----------
    I('Microcrystalline Cellulose', 'ไมโครคริสตัลลีนเซลลูโลส', ['exfoliant', 'absorbent'], [C],
      'ผงเซลลูโลสจากพืช ใช้เป็นเม็ดสครับเนื้อละเอียดหรือช่วยดูดซับความมัน', en='Plant cellulose powder',
      kind='polymer'),
    I('Jojoba Esters', 'โจโจบาเอสเทอร์', ['exfoliant', 'emollient'], [C, M],
      'เม็ดสครับกลมเล็กจากน้ำมันโจโจบา ละลายได้ขณะนวด ขัดเบาและไม่บาดผิว', tips=_SCRUB_TIPS,
      en='Soft, round jojoba wax beads', kind='mixture'),
    I('Perlite', 'เพอร์ไลต์', 'exfoliant', [C], _SCRUB + ' จากหินภูเขาไฟ', tips=_SCRUB_TIPS,
      en='Volcanic glass scrub particle', kind='mineral'),
    I('Pumice', 'หินภูเขาไฟ (พัมมิซ)', 'exfoliant', [C], _SCRUB + ' เนื้อค่อนข้างหยาบ', tips=_SCRUB_TIPS,
      en='Coarse volcanic scrub', kind='mineral'),
    I('Juglans Regia Shell Powder', 'ผงเปลือกวอลนัท', 'exfoliant', [C],
      _SCRUB + ' ขอบคมไม่สม่ำเสมอ อาจทำให้เกิดรอยขีดข่วนเล็กๆ ได้', tips=_SCRUB_TIPS,
      aka=['Walnut Shell Powder'], en='Walnut shell scrub (can be harsh)', kind='extract'),
    I('Oryza Sativa Bran Powder', 'ผงรำข้าว', 'exfoliant', [C], _SCRUB + ' เนื้อละเอียดอ่อนโยน',
      tips=_SCRUB_TIPS, aka=['Rice Bran Powder', 'รำข้าว'], en='Gentle rice bran scrub', kind='extract'),
    I('Oryza Sativa Powder', 'ผงข้าว', ['exfoliant', 'absorbent'], [C],
      'ผงแป้งข้าวละเอียด ใช้ในผงล้างหน้าเอนไซม์ (enzyme powder wash) ขัดเบาและดูดซับความมัน',
      aka=['Rice Powder', 'แป้งข้าว'], en='Rice powder for powder washes', kind='extract'),
    I('Zea Mays Starch', 'แป้งข้าวโพด', 'absorbent', [C, M],
      'แป้งจากข้าวโพด ช่วยดูดซับความมัน ให้สัมผัสแห้งนุ่ม', aka=['Corn Starch'], en='Corn starch',
      kind='polymer'),
    I('Polyethylene', 'โพลีเอทิลีน', ['exfoliant', 'thickener'], [C, M],
      'พลาสติกที่เคยใช้ทำเม็ดสครับไมโครบีดส์ ปัจจุบันหลายประเทศรวมถึงไทยห้ามใช้เป็นเม็ดสครับแล้วเพราะเป็นไมโครพลาสติก',
      en='Plastic; banned as microbeads in many countries', kind='polymer'),
    I('Papain', 'ปาเปน (เอนไซม์มะละกอ)', 'exfoliant', [C, E],
      'เอนไซม์จากยางมะละกอที่ย่อยโปรตีนในเซลล์ผิวเก่า ช่วยผลัดเซลล์แบบอ่อนโยน',
      good='ผิวเรียบเนียน สิวเสี้ยนหลุดง่ายขึ้น', tips='พบมากในผงล้างหน้าเอนไซม์ ไม่ควรถูแรง',
      aka=['enzyme', 'เอนไซม์', 'มะละกอ'], en='Papaya enzyme exfoliant', kind='protein'),
    I('Bromelain', 'โบรมีเลน (เอนไซม์สับปะรด)', 'exfoliant', [C, E],
      'เอนไซม์จากสับปะรดที่ย่อยโปรตีน ช่วยผลัดเซลล์ผิวอย่างอ่อนโยน', aka=['enzyme', 'สับปะรด'],
      en='Pineapple enzyme exfoliant', kind='protein'),
    I('Subtilisin', 'ซับทิลิซิน', 'exfoliant', [C],
      'เอนไซม์ย่อยโปรตีนจากจุลินทรีย์ ใช้ในผงล้างหน้าเอนไซม์', aka=['enzyme', 'protease'],
      en='Protease enzyme exfoliant', kind='protein'),
    I('Kaolin', 'ดินขาวเคาลิน', 'absorbent', [C, M], _CLAY + ' เป็นดินที่อ่อนโยนที่สุด',
      tips=_CLAY_TIPS, aka=['clay', 'โคลน', 'ดิน', 'China clay'], en='Gentle white clay',
      kind='mineral', f='Al2Si2O5(OH)4'),
    I('Bentonite', 'ดินเบนโทไนท์', 'absorbent', [C], _CLAY + ' ดูดน้ำ/น้ำมันได้มาก ฤทธิ์แรงกว่าเคาลิน',
      tips=_CLAY_TIPS, aka=['clay', 'โคลน'], en='Highly absorbent clay', kind='mineral'),
    I('Montmorillonite', 'มอนต์มอริลโลไนต์', 'absorbent', [C], _CLAY, tips=_CLAY_TIPS,
      aka=['clay', 'French green clay'], en='Absorbent clay', kind='mineral'),
    I('Illite', 'อิลไลต์', 'absorbent', [C], _CLAY + ' มักเรียกว่าดินเขียวฝรั่งเศส', tips=_CLAY_TIPS,
      aka=['clay', 'green clay'], en='Green clay', kind='mineral'),
    I('Moroccan Lava Clay', 'ดินลาวาโมร็อกโก (ราสซูล)', 'absorbent', [C], _CLAY, tips=_CLAY_TIPS,
      aka=['Rhassoul', 'Ghassoul'], en='Rhassoul clay', kind='mineral'),
    I('Charcoal Powder', 'ผงถ่าน', 'absorbent', [C],
      'ผงถ่านกัมมันต์ที่มีรูพรุนมาก ดูดซับความมันและสิ่งสกปรก', tips='ส่วนใหญ่ช่วยแค่ระหว่างล้าง ไม่ได้ "ดูดสารพิษ" อย่างที่โฆษณา',
      aka=['charcoal', 'ชาร์โคล', 'ถ่าน', 'Activated Charcoal'], en='Activated charcoal powder',
      kind='mineral'),
    I('Silt', 'ตะกอนโคลน', 'absorbent', [C], 'โคลนตะกอนจากแหล่งน้ำแร่ ใช้ในมาส์กโคลน ช่วยดูดซับความมัน',
      aka=['mud', 'โคลน'], en='Mineral mud', kind='mineral'),
]
