"""Key ingredients suggested per product category (most typical first)."""

POPULAR = {
    'cleanser': ['Glycerin', 'Cocamidopropyl Betaine', 'Sodium Cocoyl Glutamate', 'Potassium Cocoyl Glycinate',
                 'Sodium Laureth Sulfate', 'Sodium Lauroyl Methyl Isethionate', 'Sodium Methyl Cocoyl Taurate',
                 'Decyl Glucoside', 'Coco-Glucoside', 'Myristic Acid', 'Potassium Hydroxide', 'Stearic Acid',
                 'Lauric Acid', 'Salicylic Acid', 'Centella Asiatica Extract', 'Panthenol', 'Niacinamide', 'Kaolin',
                 'PEG-6 Caprylic/Capric Glycerides', 'Cetyl Ethylhexanoate', 'Phenoxyethanol', 'Disodium EDTA'],
    'sunscreen': ['Zinc Oxide', 'Titanium Dioxide', 'Ethylhexyl Methoxycinnamate', 'Homosalate',
                  'Ethylhexyl Salicylate', 'Octocrylene', 'Butyl Methoxydibenzoylmethane',
                  'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', 'Methylene Bis-Benzotriazolyl Tetramethylbutylphenol',
                  'Ethylhexyl Triazone', 'Diethylamino Hydroxybenzoyl Hexyl Benzoate', 'Diethylhexyl Butamido Triazone',
                  'Terephthalylidene Dicamphor Sulfonic Acid', 'Drometrizole Trisiloxane',
                  'Phenylbenzimidazole Sulfonic Acid', 'Tris-Biphenyl Triazine', 'Alcohol Denat.', 'Niacinamide',
                  'Centella Asiatica Extract', 'Tocopheryl Acetate', 'Silica', 'Iron Oxides'],
    'moisturizer': ['Glycerin', 'Ceramide NP', 'Squalane', 'Niacinamide', 'Panthenol', 'Sodium Hyaluronate',
                    'Butyrospermum Parkii Butter', 'Dimethicone', 'Cetearyl Alcohol', 'Allantoin',
                    'Centella Asiatica Extract', 'Petrolatum', 'Urea', 'Cholesterol', 'Caprylic/Capric Triglyceride',
                    'Madecassoside', 'Beta-Glucan', 'Ectoin'],
    'serum': ['Niacinamide', 'Ascorbic Acid', '3-O-Ethyl Ascorbic Acid', 'Sodium Hyaluronate', 'Retinol', 'Retinal',
              'Tranexamic Acid', 'Alpha-Arbutin', 'Ferulic Acid', 'Palmitoyl Tripeptide-1', 'Acetyl Hexapeptide-8',
              'Copper Tripeptide-1', 'Azelaic Acid', 'Bakuchiol', 'Galactomyces Ferment Filtrate',
              'Snail Secretion Filtrate', 'Sodium Polyglutamate', 'Adenosine'],
    'toner': ['Glycerin', 'Butylene Glycol', 'Niacinamide', 'Sodium Hyaluronate', 'Panthenol', 'Glycolic Acid',
              'Salicylic Acid', 'Lactic Acid', 'Gluconolactone', 'Centella Asiatica Extract', 'Hamamelis Virginiana Water',
              'Rosa Damascena Flower Water', 'Houttuynia Cordata Extract', 'Artemisia Princeps Extract'],
    'treatment': ['Salicylic Acid', 'Benzoyl Peroxide', 'Adapalene', 'Azelaic Acid', 'Sulfur', 'Niacinamide',
                  'Melaleuca Alternifolia Leaf Oil', 'Zinc PCA', 'Tranexamic Acid', 'Hydroquinone', 'Retinoic Acid',
                  'Centella Asiatica Extract', 'Allantoin'],
    'mask': ['Kaolin', 'Bentonite', 'Charcoal Powder', 'Glycerin', 'Sodium Hyaluronate', 'Centella Asiatica Extract',
             'Niacinamide', 'Panthenol', 'Glycolic Acid', 'Papain', 'Algin', 'Polyvinyl Alcohol', 'Petrolatum'],
}
